### ISSUE TITLE
Receiving empty messages on AMQP GELF input will result in requeueing and inifinite message processing loop

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#1018]
It seems that the GELF AMQP input will [basicNack](https://github.com/Graylog2/graylog2-server/blob/a5cec6ee646044d55789cd516569fb7a56a478fd/graylog2-inputs/src/main/java/org/graylog2/inputs/transports/AmqpConsumer.java#L125) unhandled messages while procesing. On empty messages (where e.g. only an AMQP header is set) this will result in requeueing the same message. However this same message will subsequently be processed by the input plugin again and again resulting in a message loop.
This behaviour occurred with a message sent via RabbitMQ with only AMQP headers set (but with an empty message body) on a Graylog v1.0.0 server.

**Comment by bernd** [comment]
Thanks for the report!

**Comment by bernd** [comment]
Any GELF input requires a valid GELF message. Sending a GELF message with an empty body is an error.

I guess the problem here is that the `AmqpConsumer` is re-queueing messages that cannot be parsed. Maybe we should not re-queue the messages in case of an error and use `channel.basicNack(deliveryTag, false, false);` instead. (maybe make that configurable?)

Running into the same error with the same message sounds wrong to me.

Comments? /cc @dennisoelkers @joschi @kroepke

**Comment by dfch** [comment]
Hi Bernd, this is exactly what I mean. As the GELF AMQP plugin cannot enforce the format of the message that is sent by a publisher, this will lead to a re-processing of the message (in most cases). As an addition to just providing a flag whether or not to requeue, you could also write a qualified "warning" message to the system log (instead of just writing a full stack trace), like you do when a plugin fails or any other system event occurs.

**Comment by joschi** [comment]
+1 for adding a configuration flag for the handling of invalid messages.
