### ISSUE TITLE
Cisco switches showing up on Graylog with the date as a source.

### ISSUE THREAD

**Issue by Tobatsu** [Graylog2/graylog2-server#1031]
Hi,

We bumbed into an interesting problem. Our Cisco switches show up with the current date (day) as a source.. So yesterday the source would have been "3" and today it is "4".
Sources list looks like this now:
- 4
- 3
- 2
And so on.

Tried sending the logs through Rsyslog but it didn't help this time (earlier this worked).

With Plaintext/Raw UDP Input they show up with IP as source but with Syslog UDP Input it is as mentioned. The goal is to have them with hostnames.

Here are some example messages captured with tcpdump (source changed):

<189>23064: cisco-sw2: Mar 4 2015 07:03:59.338 UTC: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/0/9, changed state to up

<187>23063: cisco-sw2: Mar 4 2015 07:03:58.336 UTC: %LINK-3-UPDOWN: Interface GigabitEthernet1/0/9, changed state to up

<189>16255: cisco-sw1: Mar 4 2015 06:16:00.870 UTC: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up

<187>16250: cisco-sw1: Mar 4 2015 06:15:54.956 UTC: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up

**Comment by edmundoa** [comment]
Hi,

It looks like those switches do not send RFC compliant syslog messages, so Graylog can't make sense out of them. You can read more about this problem here: http://docs.graylog.org/en/1.0/pages/sending_data.html#syslog

The easier way of solving this issue is to use extractors. There is already a [Cisco Catalyst extractor](https://www.graylog.org/resource/extractor/53791b99e4b0b8f13c3d2ce2/) that can parse messages from those switches and may help you. In other case, you can create your own extractor and share it with us, so more people can benefit from it.

If you have any further questions about it, don't hesitate asking in our mailing list or IRC channel: https://www.graylog.org/community-support/
