### ISSUE TITLE
graylog time format error

### ISSUE THREAD

**Issue by ajieup** [Graylog2/graylog2-server#10452]
My graylog time zone setting is Asia/Shanghai.

But the time displayed by graylog is UTC time, and the login user is root. why is that?
Graylog is the latest version

**Comment by ajieup** [comment]
![image](https://user-images.githubusercontent.com/79831323/115098841-ee63dc80-9f64-11eb-9686-32a383d4aff4.png)
![image](https://user-images.githubusercontent.com/79831323/115098853-ff145280-9f64-11eb-8d73-a3b3fbbfaa6b.png)

**Comment by ajieup** [comment]
Can someone help me?

**Comment by sebbele** [comment]
Steps we've made to reproduce the issue:

1) Go to the main search page
2) Make any search that modifies the URI (i.e. type any search, or change time to absolute). The time is displayed in browser time.
3) Refresh the page. The time displayed is now the same as the timestamp (Zulu time instead of local +2). Just loading any search with a modified URI seems to recreate the issue as well.

**Comment by dennisoelkers** [comment]
Hey @sebbele, what Graylog version are you using? Which user are you logged in as, when you are seeing this?

**Comment by sebbele** [comment]
> what Graylog version are you using? Which user are you logged in as, when you are seeing this?

Hi @dennisoelkers!
Current running version: 4.0.7+c3e766c, codename Noir
All users are experiencing this from what I've seen.
