### ISSUE TITLE
Create a setting in Graylog.conf for "prefer_netprotocol = ipv4"

### ISSUE THREAD

**Issue by tristanbob** [Graylog2/graylog2-server#1050]
My Graylog input was binding to IPv6, when I wanted it to use IPv4.  Graylog documentation has information about this:

"Add the java.net.preferIPv4Stack flag in your graylogctl script..."
http://docs.graylog.org/en/1.0/pages/installation.html

The graylogctl script references a variable called  "$(JAVA_OPTS)", but I don't know where that is set.

My request is to create a new Graylog.conf setting that tells it which network protocol to use.  Something like:

"network_protocol = ipv4"
or
"prefer_ipv4 = true"

Thanks!

**Comment by joschi** [comment]
Since this is a JVM-level setting, it can't be changed after the JVM has been started (i. e. after Graylog has been loaded and is parsing the configuration file).

You can add the required setting (`-Djava.net.preferIPv4Stack=true`) to the `DEFAULT_JAVA_OPTS` variable in the `graylogctl` script (https://github.com/Graylog2/graylog2-server/blob/1.0.0/bin/graylogctl#L54) or set `JAVA_OPTS` (which should contain the recommended options from `DEFAULT_JAVA_OPTS`) outside of the `graylogctl` script.
