### ISSUE TITLE
Messages are routed to many streams.

### ISSUE THREAD

**Issue by carloselectro** [Graylog2/graylog2-server#10626]
I’m using Graylog 4.06 and for some reason Graylog is not routing to the right stream with my regex.
We are using the SNMP plugin without MIBS installed.
I have 2 Streams:
Stream_Reseaux_Critique
Stream_Reseau_Info

As you can see in the screenshots below, it should be routed to Stream_Reseau_Info because the regex matches, but I cannot find any events for this stream and it all goes to Stream_Reseaux_Critique.

![Stream_reseau_critique](https://user-images.githubusercontent.com/16227744/118010811-5f58a300-b31d-11eb-99e0-671e6b9cde98.png)
![Stream_reseau_info](https://user-images.githubusercontent.com/16227744/118010812-5f58a300-b31d-11eb-842d-d3527316dd05.png)

I can reproduce the problem with other stream also.

Graylog Version: 4.06
Operating System: Ubuntu

**Comment by bernd** [comment]
@carloselectro Thank you for the report! Is this a new 4.0.6 setup or did you update to that version and now see the problem? Thank you

**Comment by carloselectro** [comment]
I am not sure because we did not use many streams before updating.

**Comment by carloselectro** [comment]
Any update on our bugs?

**Comment by AntonEbel** [comment]
Just to be sure. The streams were saved like in your screenshots and after a new message of "Security: SSH logout ..." arrived the wrong routing happened? I'm only asking because updating or creating rules for a stream doesn't affect messages that have already been processed. So it is possible that the following message was processed by older rules.
<img width="1321" alt="routed_into_streams" src="https://user-images.githubusercontent.com/25727579/129042426-065181e8-c14b-4807-9574-4a053850558e.png">

**Comment by carloselectro** [comment]
I am closing the ticket because the bug was the snmp plugins. As soon as we stopped using it it worked great
