### ISSUE TITLE
Pipeline Rule page sometimes empty

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#10737]
Created pipeline rule page sometimes does not show pipeline rule in "Rule source." If opened in a new tab, via the direct opening of the URL or if the page gets completely reloaded with F5 or Refresh button

## Expected Behavior

After every refresh/F5, it should show the pipeline rule instead of the empty Rule source

![image](https://user-images.githubusercontent.com/62546449/119974895-8b2e8680-bfb5-11eb-856d-5f59e4dbfe06.png)

## Current Behavior

https://user-images.githubusercontent.com/62546449/119974708-46a2eb00-bfb5-11eb-84c2-55bc40d3667d.mov

## Steps to Reproduce (for bugs)

1. Open your Graylog Web UI --> System/Pipeline
2. Select one pipeline rule --> allocated pipeline rule 
3. Refresh the page same or copy-paste the link to a new browser tab

## Context

HS-428423348

## Your Environment

* Graylog Version:4.0.7
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: Firefox ESR / Chrome 90.0.4430.212

**Comment by edmundoa** [comment]
I have been trying to reproduce this on the 4.2 pre-release and I couldn't.

Looking through file changes, I found this other issue, which seems to describe the same behaviour: https://github.com/Graylog2/graylog2-server/issues/9341. The issue was fixed in https://github.com/Graylog2/graylog2-server/pull/10070 and released as part of 4.1, so I think we can close this issue now.

Please reopen if you still see this issue or if a fix for 4.0.x is necessary. Thank you!
