### ISSUE TITLE
Logging out as admin after enabling Okta results in error message

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#10832]
## Current Behavior

After configuring Okta auth, logging out the admin user ends up on an okta page (`https://xxxx.okta.com//oauth2/default/v1/logout?id_token_hint=...`) showing the following error message:
```
{"errorCode":"invalid_client","errorSummary":"Invalid value for 'client_id' parameter.","errorLink":"invalid_client","errorId":"oaeUY598N6JRKG-UMZFUjQ85Q","errorCauses":[]}
```

This does not happen when I login as admin after Okta is configured and logging out again.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
I have tried to reproduce this issue both locally and in the 4.1 test instance but so far I couldn't. I will try creating a whole new instance and see if it happens there. @dennisoelkers have you seen the error again since you wrote the issue?

While testing this I have seen a different issue, where logging out after setting up Okta does not load the Okta login form but a loading spinner:

<img width="523" alt="Screenshot 2021-06-15 at 17 25 39" src="https://user-images.githubusercontent.com/716185/122080635-b5c66f00-cdfe-11eb-824b-8e84c964a142.png">

The workaround seems to be doing a full page reload.

**Comment by edmundoa** [comment]
@dennisoelkers I have tried to reproduce this today again but I could not, do you have any more information that can help us reproduce the issue? If not I would vote for closing until we can reproduce it in some way.

**Comment by dennisoelkers** [comment]
Hey @edmundoa, I just tried to reproduce it and this time I am seeing the same as you described [here](https://github.com/Graylog2/graylog2-server/issues/10832#issuecomment-861600056) - no error, but the login form is not loading. Therefore I am closing this issue in favor of the one you created. Thanks! :)
