### ISSUE TITLE
Node IP Address not shown?

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#10868]
## Expected Behavior
Next to the Hostname, the IP-Address should be shown according to the testing documentation.
I am not able to find it. The REST-API Transport shows an IP, but I'm not sure if that's what I'm looking for and it can be set via graylog.conf.

## Current Behavior
see the screenshot
![IP](https://user-images.githubusercontent.com/1190735/122197361-65035480-ce98-11eb-8ff1-4eb7c20a177f.png)

## Steps to Reproduce (for bugs)

1. select "System->Nodes"
2. select the details for a node
3.
4.

## Your Environment

* Graylog Version: 4.1.0-beta1

* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by thll** [comment]
@janheise are you sure this is a bug? The `nodes` collection in MongoDB doesn't have a distinct field for the IP address, so unless the frontend is doing some magic, I don't think that the IP address would be visible.

I checked version `3.3` and it also doesn't show the IP address.

I think the only case where we might end up showing an IP address instead of a hostname would be when we are unable to resolve the IP address to a hostname [here](https://github.com/Graylog2/graylog2-server/blob/9809b9a1b7c9d4612d9dde8e6eb3dc1e3876d36d/graylog2-server/src/main/java/org/graylog2/plugin/Tools.java#L285).

**Comment by thll** [comment]
@bernd, @kroepke: do you know if we were ever showing IP addresses here? Otherwise, I think we should close this issue.

**Comment by janheise** [comment]
only as additional info, the old testplan states: 'Hostnames/IPs are shown and correct'

**Comment by bernd** [comment]
@thll @janheise The transport address is shown on the right side of the hostname. I guess that's what this is about.

I would say we can close this issue. :slightly_smiling_face:
