### ISSUE TITLE
Allowed TLS Cipher Suites too tight

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#10944]
## Expected Behavior

Configurable TLS Cipher Suites or a 'common' list of allowed cipher suites

## Current Behavior

Only some TLS Ciphers are active since: https://github.com/Graylog2/graylog2-server/pull/10653
```

* TLS 1.0 Cipher suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * SSL 2.0 Cipher suites:
     Attempted to connect using 7 cipher suites; the server rejected all cipher suites.

 * TLS 1.2 Cipher suites:
     Attempted to connect using 158 cipher suites.

     The server accepted the following 6 cipher suites:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      
        TLS_RSA_WITH_AES_128_GCM_SHA256                   128                      
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             128       ECDH: prime256v1 (256 bits)
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               256       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               128       DH (2048 bits) 

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported

     The server has no preferred cipher suite.


 * TLS 1.1 Cipher suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * OpenSSL CCS Injection:
                                          OK - Not vulnerable to OpenSSL CCS injection

 * TLS 1.3 Cipher suites:
     Attempted to connect using 5 cipher suites.

     The server accepted the following 2 cipher suites:
        TLS_AES_256_GCM_SHA384                            256       ECDH: x25519 (253 bits)
        TLS_AES_128_GCM_SHA256                            128       ECDH: x25519 (253 bits)

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported

     The server is configured to prefer the following cipher suite:
        TLS_AES_256_GCM_SHA384                            256       ECDH: x25519 (253 bits)
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Communication to LDAP or ES is interrupted because of strict TLS Ciphers. 
## Your Environment

* Graylog Version: 4.1.0
* Java Version: JDK 11 Adopt Open JDK
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
@HenryTheSir Thanks for the report. We will check if we can introduce an option to make this possible again.

**Comment by mpfz0r** [comment]
As some users already noticed, the problem comes from
this change introduced in 4.1: https://github.com/Graylog2/graylog2-server/pull/10653

Unfortunately, the default cipher list in Elastic 6.8 does not include any cipher considered secure by
modern standards.

https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility

We are working on a fix, that allows Graylog users to use older (not considered secure) ciphers.

As a workaround, the default cipher list of ES 6.8.x can be extended by
`TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` which should work for newer Java versions.
The config option for ES would look like this:

`xpack.ssl.cipher_suites=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`


Older Java versions might still need a security property to allow key lenghts > 128bit:

 `crypto.policy=unlimited`

**Comment by HenryTheSir** [comment]
Hi @mpfz0r 

I am aware that it would be ideal to use only the secure cipher suites. As changing the cipher suites for ES would be possible as it is under my maintenance there are circumstances where this is not possible, e.g. LDAP dependencys where the maintenance is in another department and the underlying software is not able to use this secure ciphers. As for now this would mean we need to change to unencrypted ldap querys. 

Your suggestion to make a fix/configuration to allow unsecure ciphers would be great!

Thanks in advance
