### ISSUE TITLE
X_FORWARDED_FOR

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1102]
Hi,

We are hosting Graylog behind a reverse proxy (Squid3 in our case). The Gelf HTTP listener is going through that machine also, but now every message is received from the same IP in Graylog. Could you please add an option to use the X_FORWARDED_FOR header if it's there?

**Comment by mrfreezer** [comment]
you can just do this inside apache config...

this goes to your apache2.conf

LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined_px
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded

the conditional logging is since we have several calls from internal machines as well, for example nagios polling the websites.

this goes into the websites config:

CustomLog ${APACHE_LOG_DIR}/access.log combined env=!forwarded
CustomLog ${APACHE_LOG_DIR}/access.log combined_px env=forwarded

of course you can omit the conditional logging if you do not have machines accesing the servers while circumventing the proxy. then just change the "%h" in the combined definition into %{X-Forwarded-For}i

**Comment by bernd** [comment]
I started to investigate the possibility to check the `X-Forwarded-For` HTTP header for this. I see several problems:

* The header only provides an ip address but we also need the port.
* If we implement this, we should also implement the [RFC7239](http://tools.ietf.org/html/rfc7239) `Forwarded` header which complicates the implementation.
* Parsing this should not be needed because the [GELF](https://www.graylog.org/resources/gelf-2/) specification already requires a `host` field to be set by the client library.

So a simple solution for you is to provide a `host` field in the GELF message. This will show up as `source` in the web interface.

I hope that helps. Please re-open if you still have problems. Thank you!
