### ISSUE TITLE
Quick Value splits strings for log message

### ISSUE THREAD

**Issue by veilig2000** [Graylog2/graylog2-server#1119]
I'm utilizing v1.0.1 of the AWS EC2 image.  When I try to get "quick values" off the log message value, it splits by space

Here's a screenshot of the query results
![screen shot 2015-04-16 at 9 44 05 am](https://cloud.githubusercontent.com/assets/240543/7182098/3b058002-e41d-11e4-8cf1-c319416d4bcb.png)

And then when I try to get quick values of this field, expecting one value to be "Authentication Required", I actually get two values "Authentication" & "Required"
![screen shot 2015-04-16 at 9 44 20 am](https://cloud.githubusercontent.com/assets/240543/7182101/408a63a8-e41d-11e4-8992-3936ef384e28.png)

This appears to work correctly on other context fields that are strings, but I wasn't sure if it was supposed to do this for the log message or was some other issue with my index or perhaps another reason?

**Comment by bernd** [comment]
This is because the `message` field is configured to be analyzed by Elasticsearch. Because of that, the message gets split into terms depending on the analyzer that is used.

It does not happen for other fields because those are not configured to be analyzed. So that behavior is normal.

I hope that helps. Please re-open the ticket if you have further questions. Thank you!
