### ISSUE TITLE
404 error  when click the "delete from stream" button

### ISSUE THREAD

**Issue by guilongyang** [Graylog2/graylog2-server#11531]
in outpus menu, i created one output,  and i click the "delete from stream" button, an 404 error occurred

## Expected Behavior
it will delete the relation of stream

## Current Behavior
an 404 error 

## Possible Solution
provide an delete request url

## Steps to Reproduce (for bugs)
1. create an output
2. click the "delete from stream" button from outputs menu

## Your Environment

* Graylog Version: 4.1
* Java Version: jdk8
* Elasticsearch Version: 7.10.0
* MongoDB Version:4.2
* Operating System: win10
* Browser version:chrome 67.0.3396.62

**Comment by thll** [comment]
For now, we have removed the button, because it was never intended to be shown on the outputs overview page.

@guilongyang: thanks for your contribution with #11533. If we ever decide to show a button to un-assign an output from all streams, I think we should include a little more context about which streams an output is going to be un-assigned from. At the moment I don't see a reason to add that functionality though.
