### ISSUE TITLE
Graylog Setup spits out the wrong command to run graylog, as does README

### ISSUE THREAD

**Issue by boardstretcher** [Graylog2/graylog2-server#1155]
java -Xms1g -Xmx1g -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Djava.net.preferIPv4Stack=true -Djava.library.path=lib/sigar -jar graylog/graylog.jar server -p run/graylog.pid -f conf/graylog.conf

will not work - you need a - dash - before "XX:+CMSConcurrentMTEnabled" like this:

-XX:+CMSConcurrentMTEnabled

Just an FYI that setup and the README are incorrect. Graylog-setup-1.0.0

**Comment by joschi** [comment]
Thanks for reporting this!

We currently don't plan to update the Graylog Quick Setup Application anymore. It will basically be deprecated with the release of Graylog 1.1.0 because the [virtual machine images](http://docs.graylog.org/en/1.0/pages/installation.html#virtual-machine-appliances) are a better way to try out Graylog in our opinion.
