### ISSUE TITLE
[doc] The syntax page ill-formated

### ISSUE THREAD

**Issue by wxiaoguang** [Graylog2/graylog2-server#11630]
https://docs.graylog.org/v1/docs/query-language

The wrong format is quite misleading:

`/ ethernet [ 0 - 9 ] +/ ` => `/ethernet[0-9]+/ `

`"ssh login" AND NOT source : example . org ` => `"ssh login" AND NOT source:example.org `

`http_response_code : > 400` => `http_response_code:>400`

**Comment by dulanism** [comment]
Hi @wxiaoguang, thanks for catching this. I was just recently alerted about this issue, and I'll take care of it today.

Also, we have a new place to post issues and start conversations about our documentation since moving our platform away from read the docs/GH. Please drop comments about docs in our Documentation Campfire: https://community.graylog.org/c/documentation-campfire/30.

This repo is now retired. 

We appreciate your contributions to making our content better.

**Comment by bernd** [comment]
Thanks for the report!
