### ISSUE TITLE
Description is not being saved when creating pipeline rule

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#11812]
When creating a pipeline rule, the provided description is ignored.

This only seems to happen when the last action is editing the rule, not the description field.

I think the problem lies here:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/rules/RuleContext.jsx#L88
This line clears a previously provided description.

This probably also happens when updating pipeline rules. Haven't verified this.

**Comment by linuspahl** [comment]
@mpfz0r I saw this bug today as well. Can you may change the title to something like "Description is not being saved when creating pipeline rule"

Currently the title sounds like the problem is only that the description field is not required.

This problem does not occur when updating a pipeline rule.

**Comment by mpfz0r** [comment]
@linuspahl sure, that sounds better :+1: thank you
