### ISSUE TITLE
Log4j again - CVE-2021-45046 and CVE-2021-45105

### ISSUE THREAD

**Issue by molaeiali** [Graylog2/graylog2-server#11856]
Looks like Log4j has some more DoS vulnerabilities, and according to [snyk.io - CVE-2021-45046](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2320014) [snyk.io - CVE-2021-45105](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2321524), adding Environment variables and jvm options used [here](https://github.com/Graylog2/graylog-docker/commit/82fec0094bc98aedd59e5f6538d819178ff77056) are not enough to fix them, and it's needed to upgrade to log4j 2.17.0

## Expected Behavior
Updating log4j version to 2.17.0

## Current Behavior
Just added jvm options to mitigate [CVE-2021-44228](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720)

## Possible Solution
Updating log4j version to 2.17.0

## Context
I'm not sure if graylog is vulnerable or not, but i assume it is, because it's using log4j

**Comment by loganmarchione** [comment]
See more talk in #11804

**Comment by DaVukovic** [comment]
AFAICT #11804 has nothing to do with this issue. Graylog itself (at least in a docker) ships its own log4j2 version. With the leatest releases (3.3.16, 4.1.10 and 4.2.4) Graylog released a version which includes log4j 2.16.0 which now is vulnerable again. 

Thankfully the release with Log4j 2.16.0 came out pretty quick. So let's hope the Graylog-ppl will release something including Log4j 2.17.0 soon. :+1:

**Comment by kroepke** [comment]
We will be releasing a regular bug fix release with log4j 2.17.0 on January 5th, but won't be issuing an emergency release for this one, because Graylog does not use any thread context maps, and the default configuration also does not include any patterns with it.
Thus a user would need to add them themselves and log a value that gets passed from the request itself (e.g. user agent or other headers), which is extremely unlikely to happen.
The rationale here is that Graylog in its default config, and any reasonable configuration likely to occur, is *not* vulnerable to the infinite loop bug addressed in 2.17.0.

**Comment by mayrstefan** [comment]
There was even more log4j fixing needed. Everyone would like to see version 2.17.1 now

**Comment by bernd** [comment]
@mayrstefan We will release new 4.2 and 4.1 stable versions tomorrow, including Log4j 2.17.1.

**Comment by nkovacs** [comment]
@bernd will 3.3 be updated to log4j 2.17.1 or is that version of graylog no longer supported?

**Comment by bernd** [comment]
@nkovacs Unfortunately, 3.3 and 4.0 are no longer supported and will not be updated anymore.

**Comment by molaeiali** [comment]
I think this issue can be closed? @kroepke

**Comment by bernd** [comment]
@molaeiali Yes, thanks for the reminder! :slightly_smiling_face:
