### ISSUE TITLE
Manually run index ranges cleanup through the GUI and api endpoint

### ISSUE THREAD

**Issue by ed-graylog** [Graylog2/graylog2-server#11919]
## What?

As a Graylog user I would like to manually run indices cleanup via the GUI rather than periodically through a job. Being able to hit an API endpoint would also be helpful.

## Why?

This would be helpful when reindexing things directly into Elasticsearch or when restoring archives for example. Currently when we let the job run, we have to wait by default one hour unless we specify otherwise in the config file.

See HS-575331695 for further context.

**Comment by bernd** [comment]
@edward-marrufo We have buttons and API endpoints for rotating the active write index and recalculating the index ranges.

![image](https://user-images.githubusercontent.com/461/148772379-0315b12b-8107-43a9-9489-2dcf06eddf4a.png)

Does that help?

**Comment by bernd** [comment]
@edward-marrufo Yes, @mpfz0r is right. I thought the "Recalculate index ranges" action also removes stale index ranges. But that's not the case.

I think instead of creating a new API endpoint, we should extend the "Recalculate index ranges" action also to clean up stale index ranges. What do you think, @mpfz0r?

**Comment by mpfz0r** [comment]
> I think instead of creating a new API endpoint, we should extend the "Recalculate index ranges" action also to clean up stale index ranges. What do you think, @mpfz0r?

Sure, that would work as well :+1:
