### ISSUE TITLE
Cannot load drools file: Parser returned a null Package

### ISSUE THREAD

**Issue by javierjeronimo** [Graylog2/graylog2-server#1213]
Hello,

I have the following drools file (https://github.com/javierjeronimo/graylog-drool-rules/blob/master/src/main/resources/rules.drl):
```java
package com.gx;

import org.graylog2.plugin.Message

rule "Convert executionTime from string to integer"
when
	m : Message( getField("executionTime") != null && getField("executionTime").toString().length() > 0 )
then
 	m.addField("executionTime", Integer.valueOf(m.getField("executionTime").toString()));
end
```

I have created a Maven project using archtype in github.com:droolsjbpm/droolsjbpm-knowledge.git and this test passes ok: https://github.com/javierjeronimo/graylog-drool-rules/blob/master/src/test/java/com/gx/RuleTest.java

But I get this error in server.log:
```
2015-06-04T13:40:08.301+02:00 ERROR [AbstractKieModule] Unable to build KieBaseModel:defaultKieBase
[5,0]: [ERR 107] Line 5:0 mismatched input 'package' expecting one of the following tokens: '[package, import, global, declare, function, rule, query]'.
[0,0]: Parser returned a null Package

2015-06-04T13:40:08.302+02:00 WARN  [DroolsEngine] Unable to add rules due to compilation errors.
org.graylog2.rules.RulesCompilationException: Message [id=1, level=ERROR, path=r1.drl, line=5, column=0
   text=[ERR 107] Line 5:0 mismatched input 'package' expecting one of the following tokens: '[package, import, global, declare, function, rule, query]'.]
Message [id=2, level=ERROR, path=r1.drl, line=0, column=0
   text=Parser returned a null Package]

        at org.graylog2.rules.DroolsEngine.createKJar(DroolsEngine.java:221)
        at org.graylog2.rules.DroolsEngine.createAndDeployJar(DroolsEngine.java:190)
...
```

Why parser fails to load rules file if it seems to be ok?

Thank you.

**Comment by kroepke** [comment]
Hi!

The drools engine in graylog always adds these lines automatically, so you can't add another package definition currently.

```
// the following header lines are automatically added by graylog2-server
//package org.graylog2.rules
//import org.graylog2.plugin.Message

//global org.slf4j.Logger log
```

Please also check the `graylog2.drl` example file.

**Comment by codeitdandy** [comment]
kroepke, 

I am facing the same problem when i try to import a java class into my drl file , the import fails with error returning null package/java class cannot be resolved to a type. I will let you know the details but can you please let me know is there any restrictions within the graylog drl rule execution engine which prevents access to external java classes being invoked from drl.

**Comment by joschi** [comment]
@codeitdandy Kay already wrote in his last comment which lines are being added automatically at the top of the rules file.

If you're really facing the same problem, it's because of the duplicate `package` declaration (which is already done in the prolog added by Graylog).

**Comment by codeitdandy** [comment]
thanks @joschi for your insights.I am actually new to graylog and frankly not quite aware of how graylog is triggering the  drools rule engine so it might be a very simple question with an obvious solution which is somehow escaping me . I am just trying to improve an already existing (drl code) by invoking another java class , which is residing within the same directory as my drl file. Understood by kay and your comment that i may not be add another package, but when i try to invoke this java class which is within the same package from my drl it fails with the following exception `Rule Compilation error : [Rule name='BPTM logs filter']
	org/graylog2/rules/Rule_BPTM_logs_filter508671689.java (42:2371) : **PropertiesCache cannot be resolved**


2016-04-06 09:11:09,601 WARN : org.graylog2.rules.DroolsEngine - Unable to add rules due to compilation errors.
org.graylog2.rules.RulesCompilationException: Message [id=1, level=ERROR, path=r1.drl, line=30, column=0
   text=Rule Compilation error PropertiesCache cannot be resolved]

Note: PropertiesCache java class and my drl file exist in the same directory. Pretty much its not able to resolve the import and fails with compilation error
As its a corporate code i am not posting the code intentionally.Please let me know if somehow my ask is nt clear.

Any insights would be valuable , 

`

**Comment by joschi** [comment]
@codeitdandy Please use the community support channels (see https://www.graylog.org/community-support) for this discussion and make sure to include your actual rules file in your mailing list post.

**Comment by codeitdandy** [comment]
thans @joschi  for your prompt reply. i have attached my drl in the community support mailing list(google groups)post. Please advice or let me know for any insights it will help us a lot or let us know some community guidelines/best practices to achieve our objective.

Below is the link https://groups.google.com/forum/#!topic/graylog2/mKdGtKUHxtE
