### ISSUE TITLE
Slack notification test is green even if wrong URL is provided

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#12315]
Slack notification test is green even if wrong URL is provided.

## Expected Behavior
Slack notification test fails and informs that URL is wrong.

## Current Behavior
Slack notification test is green even if wrong URL is provided. One can put everything there, as long as it starts with "https://hooks.slack.com/services", test won't fail.

## Steps to Reproduce (for bugs)
1. Go to Alerts -> Notifications.
2. Press "Create Notification" button.
3. Fill required fields, put something random in "Webhook URL", starting with "https://hooks.slack.com/services".
4. Press "Execute Test Notification"

![Screenshot 2022-03-18 at 12-46-35 Graylog - New Event Definition Extremely long login time ](https://user-images.githubusercontent.com/100699120/158998614-9c65abee-0f6e-429a-8f49-0231cd59f12f.png)

## Your Environment

* Graylog Version: Graylog 4.3.0-beta.2+a61a34c on server (Oracle Corporation 1.8.0_322 on Linux 5.13.0-1017-aws)
(test-day)

**Comment by thll** [comment]
In the example above, when clicking the `Execute Test Notification` button, the notification backend will issue a `POST` request to https://hooks.slack.com/services/lalala/completelywronglink.

The problem here is, that the slack API will respond to this with a `302` redirect to https://api.slack.com/. The backend's HTTP client will follow the redirect by issuing a `GET` request to https://api.slack.com/ where it will receive a `200 OK`.

From the client's perspective, this is therefore a successful request.

Ideally, the slack API would return a response in the `400`'s for a POST request to non-existing resources. In that case, the failure would be visible in our UI as well.

We could start interpreting redirect responses for `POST` requests to webhook resources as failures. But I can't rule out that there are legitimate use cases for this. Therefore I don't think we should simply change that.

Btw, I think we have the same issue with "HTTP Notifications" because they use the same HTTP client underneath.

@luk-kaminski, @boosty Unless you have a different take on this, I think we can close this issue.

**Comment by luk-kaminski** [comment]
@thll -> Thank you for your detailed response! I'm not the one that should decide about the priority of this issue. For me it is a bug, but I understand it may be not very important and it may be difficult/complex to solve. I'm not sure if we should close it, or maybe give it some kind of "do it later" label...

**Comment by boosty** [comment]
@thll Thanks for the investigation.

> We could start interpreting redirect responses for `POST` requests to webhook resources as failures. But I can't rule out that there are legitimate use cases for this. Therefore I don't think we should simply change that.

I think we should not following the redirect here, and treat any non-200 response as a failure. Slack says that they will return 200 on success: https://api.slack.com/messaging/webhooks#handling_errors

Could there be a legitimate case where Slack would send a `302` response to let the `POST` hit a different URL? This is very unlikely, as it would not really be supported by the HTTP spec: 

> If the 302 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

Source: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by thll** [comment]
Right, for slack we could indeed change this.

I was thinking of our HTTP notifications in general (HTTP & Slack), which are using the same HTTP client underneath.

The RFC also states:

```
      Note: RFC 1945 and RFC 2068 specify that the client is not allowed
      to change the method on the redirected request.  However, most
      existing user agent implementations treat 302 as if it were a 303
      response, performing a GET on the Location field-value regardless
      of the original request method. The status codes 303 and 307 have
      been added for servers that wish to make unambiguously clear which
      kind of reaction is expected of the client.
```

@boosty Having that in mind: do you think we are safe changing HTTP notifications as well or should we implement this change for Slack only?
