### ISSUE TITLE
Field content value condition broken

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1245]
The field content value condition for alarm callbacks is somewhat broken.

![wgkvrced1ssaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/461/8131097/530c1936-1118-11e5-9fea-77e236b1bac8.png)

It does not let the user specify a time range for the condition, but hardcodes it to `alert_check_interval * 60`.

With a field content value condition configured like the following and an `alert_check_interval` of 60 (the default), the user gets an alert email every minute for one hour if only one message with that field arrived in the time range.

![k9t9ssppbsqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/461/8131174/c4c47e9c-1118-11e5-9e32-488e1eb7e2d9.png)

~~So the time range needs to be configurable like with the other alert conditions.~~ *see comments below*

**Comment by dennisoelkers** [comment]
I think it makes sense that you are not specifying a time range for this condition, as it is different from the other conditions as in that it's not working on an aggregation of the messages in a time range (count  for MessageCoundCondition and min/max/avg/stddev for FieldValueAlertCondition) but responding to single messages. This means, that we should make a search going back to the last time we have checked and search all messages in between for the occurence of a message with field with this content. Therefore, the idea was to just do a relative time range search for the configured alert checking interval.

The '* 60' is the issue here, which probably resulted from a misconception about the dimension of either the configuration variable or the parameter passed to the RelativeRange constructor.

**Comment by bernd** [comment]
Good point!

**Comment by kroepke** [comment]
I would like to keep the change for 1.1 as simple as possible, though.

Thus, I think the most logical change is what commit https://github.com/Graylog2/graylog2-server/commit/8eebc14a58bfcd6a04a97baf5ea30da9b92816c0 is doing.

Let's maybe consider saving the last-run-time for each alert for 1.2 or beyond?
