### ISSUE TITLE
(HS 8267556) Content Pack creation page fails to load entities if any fail to deserialize 

### ISSUE THREAD

**Issue by kingzacko1** [Graylog2/graylog2-server#12684]
If any content pack exportable entity in the DB fails to deserialize when populating the content pack creation page then the entire page will just be empty and have no entities available to export.

## Expected Behavior

The entities that are correctly deserialized should be listed for export and any failing entities should have a descriptive log message as to why they are not included on the page. 

## Current Behavior

If any one entity fails to deserialize when populating the content pack creation list of entities then no entities are displayed for exporting

## Possible Solution

Catch the exception for that failed deserialization, log it, and then continue gathering entities to display on the content pack creation page

## Steps to Reproduce (for bugs)

Not easily reproducible from the Graylog UI itself. Seems to occur after GL upgrades most often.

1.  Modify an entity in your MongoDB so that it no longer can be deserialized correctly (I renamed the `title` field in a stream from `title` to `not_title`: `db.streams.updateOne({"_id": ObjectId("000000000000000000000001")}, {$rename:{"title":"not_title"}})`
2. Go to System > Content Packs > Create a Content Pack. Should have no options for exporting
![image](https://user-images.githubusercontent.com/91903901/168862293-896d3f6d-3e75-446a-aceb-74513cb5e181.png)

(yes this breaks other stuff and likely wouldn't ever happen, but it's just a quick way to recreate the issue) 

## Context

Seen in at least two cases by customers and on multiple occasions by Graylog contributors. It seems like it is typically the result of an upgrade where an entity may not have been migrated 100% correctly. 

## Your Environment

My test env where I reproduced the issue: 
* Graylog Version: 4.3
* Java Version: 8
* Elasticsearch Version: OpenSearch1.3
* MongoDB Version: 4.4
* Operating System: Ubuntu
* Browser version: latest Chrome and Firefox

but note this has happened across multiple customer and contributor environments

**Comment by patrickmann** [comment]
@kingzacko1 We discussed at length and decided not to add error handling code to the content pack creation:
- this should not happen in the first place. The cited example was due to a schema change during RC, that broke prior RC installs. That was an unusual exception - we generally avoid schema changes during RC.
- if a bug like this does escape, it will usually cause a lot of other problems besides blocking content pack creation. By making content pack creation more robust, we may hide the error instead of finding and fixing it quickly.
- deserialization exceptions are already visible in the log. Catching these exceptions and writing a prettier log message doesn't make a huge difference in pinpointing the problem.
The PR can be resurrected in future, if we come across a compelling scenario.
