### ISSUE TITLE
Invalid collector_id on Sidecar Collector configuration content Pack creation

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#12778]
Hi, 
i'm using Graylog 4.1.6 and I found something strange when I generate a contentPack where I select my Sidercar Collector Confoguration.
In the json file, I found a tag where is present the collector_id: 
> "collector_id": {
>           "@type": "string",
>           "@value": "1a2fdb07-9065-4f0a-8c21-46b4be064170"
>         },

whell the id value does not match with no collector that I can see using API Rest.
![image](https://user-images.githubusercontent.com/3224592/171331223-fe712be7-23d4-4db7-987e-f84a8c3f4827.png)

The correct collector id has a different value. 
This bug means that If I cut&past the same collector configuration, changing the name and other attribute values, I cannot use it as a valid contentPack to import in the same enviroment.

The imported object as not valid collector configuration match
![image](https://user-images.githubusercontent.com/3224592/171331444-d23b04f5-ecd7-44ff-b23e-67bcc62511fd.png)

Probablly it is a bug. Is there something that I can do as workaround to fix this problem?

**Comment by bernd** [comment]
@gianluca-valentini The ID values in content packs are "logical" IDs and not the actual database IDs. When the content pack is installed, the content pack system resolves those IDs to real database IDs.

Unfortunately, I don't understand what you are trying to do yet. Can you please elaborate on your use case and what exactly you are trying to do that doesn't work? Thank you!

**Comment by gianluca-valentini** [comment]
Hi @bernd let me try to explain better my situation.

I need to import some sidecar collector configuration starting from one that I already create manually.
So the only step that I can use is the configuration import using content pack but the collector_id found on export operation is not valid.
So I cannot complete the import because a user action is required to fix it using the graylog gui


![image](https://user-images.githubusercontent.com/3224592/171408594-7b8a19b0-3a5d-419d-a367-7ac919f64cf6.png)

**Comment by bernd** [comment]
@gianluca-valentini Thanks for the update. I was able to reproduce the issue with the following steps:

1. Create a custom "Log Collector"
2. Create a custom "Configuration" and use the newly created custom log collector for the configuration
3. Create a new content pack, selecting the created configuration and log collector
4. Delete the collector configuration and the log collector
5. Install the newly created content pack
6. Observe the installed Sidecar configuration showing "Unknown collector"

The problem is that the code is using the logical ID of the log collector instead of looking up the database ID of the created log collector during the content pack installation here:

https://github.com/Graylog2/graylog2-server/blob/36d3a2dad84d65b15405a4412195cce1031076d2/graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java#L95

The code needs to get the actual database ID from the `nativeEntities` parameter in `SidecarCollectorConfigurationFacade#createNativeEntity()`.

**Comment by gianluca-valentini** [comment]
@bernd 
is there any news?
