### ISSUE TITLE
An option in the geo-resolver to use legacy non-Graylog Information Model (GIM) schema values

### ISSUE THREAD

**Issue by jjkoster** [Graylog2/graylog2-server#12909]
Before GL 4.3.1, the geoip resolver in Graylog created fieldnames like below:

For an IP address in field clientIP:
clientIP_country_code
clientIP_geolocation

These fields are used extensively across dashboards, alerts and reporting. After upgrading to 4.3.2, there is significant work to migrate to the new GIM aligned fieldnames:

For an IP address in field clientIP:
clientIP_geo_country_iso
clientIP_geo_coordinates

It would be good to have a feature that turns on or off GIM aligned geo fieldnames so that organisation that make heavy use of geo fields can plan the update of dashboards, alerts and reports, rather than having to clean up after an upgrade.

Thanks,

**Comment by H2Cyber** [comment]
Unless the change in field names is documented in the release notes, I think this issue is more of a `bug` in 4.3. 

Indeed, the impact of the change is cumbersome for those of us who use geo information across many saved searches, event definitions and dashboards. The impact is not always "apparent" especially for event definitions.

**Comment by bernd** [comment]
This looks like a breaking change indeed. Thanks for the report.

@Graylog2/secdev Please investigate. Thank you!
