### ISSUE TITLE
Custom default Reader role

### ISSUE THREAD

**Issue by malinkinsa** [Graylog2/graylog2-server#13383]
At this moment, user with default _Reader_ role can watch input info and other information about clusters. 

On input page, for example in kafka custom config, they can found sensitive data

It would be nice to be able to remove the ability to access a number of pages for a role Reader.

Reader permissions scope:
```
"clusterconfigentry:read",
"indexercluster:read",
"messagecount:read",
"journal:read",
"messages:analyze",
"inputs:read",
"metrics:read",
"fieldnames:read",
"buffers:read",
"system:read",
"jvmstats:read",
"decorators:read",
"throughput:read",
"messages:read"
```

## Your Environment

* Graylog Version: 4.3.5
* Elasticsearch Version: 7.10
* MongoDB Version: 4

**Comment by malinkinsa** [comment]
Reader permissions scope:
```
"clusterconfigentry:read",
"indexercluster:read",
"messagecount:read",
"journal:read",
"messages:analyze",
"inputs:read",
"metrics:read",
"fieldnames:read",
"buffers:read",
"system:read",
"jvmstats:read",
"decorators:read",
"throughput:read",
"messages:read"
```

**Comment by thll** [comment]
@malinkinsa thanks for the report!
 
Just to clarify the issue you are reporting: on the inputs page, the configuration for the Kafka input will show sensitive information for the `custom_properties` field like so:

![image](https://user-images.githubusercontent.com/886541/199530175-e5d3bbf3-f7d6-4ab3-8062-102c67f04a10.png)

@malinkinsa, did you see any other places where sensitive information could be revealed to a `Reader`?

Usually, sensitive information on the inputs page is replaced with asterisks (`********`). For the `custom_properties`, this has not been implemented. Rather than providing means to customize the `Reader` role, I think we should change how the `custom_properties` for the Kafka input are displayed and/or stored.

**Comment by malinkinsa** [comment]
@thll , 

> Rather than providing means to customize the Reader role, I think we should change how the custom_properties for the Kafka input are displayed and/or stored.

Yep, this a great solution.

> did you see any other places where sensitive information could be revealed to a Reader

Once again checked my setup through the user with `Reader` role and only in kafka config is it possible.
