### ISSUE TITLE
Update PaloAlto input fields

### ISSUE THREAD

**Issue by giveen** [Graylog2/graylog2-server#13582]
Currently Palo Alto has updated its fields to reflect its new version 10.x operating system.
I am getting errors like this:

`ERROR [PaloAltoTypeParser] Error parsing field application_response_time, auto is not a valid numeric value`

https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields

```
1,2022/09/30 16:25:33,019901000640,THREAT,url,2561,2022/09/30 16:25:33,1XX.1XX.133.65,198.8.71.128,0.0.0.0,0.0.0.0,allow-campus-to-any-outbound,ML@contoso.edu,,ssl,vsys1,inside,outside,ae1.501,ae1.500,default,2022/09/30 16:25:33,578116178,1,56508,443,0,0,0xf400,tcp,block-url,"a.rfihub.com/",(9999),grayware,informational,client-to-server,7147335354514856469,0x8000000000000000,United States,United States,,,0,,,0,,,,,,,,0,17,18,24,2643,,fw-5450,,,,,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,,"grayware",416c1c84-c561-4826-81d1-00b1c124a826,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2022-09-30T16:25:33.790-06:00,,,,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no
```

**Comment by Srinidhi-Saravanan** [comment]
Hi, I have tried to parse the above given log and it is parsing without any errors, also tried to parse another sample log of the same 10.x version.

- can you share the log for which you get the mentioned error, so that I could check for the exact field which is giving error. Other sample log also would help to check for parsing errors.
- I have also checked for the newly added fields in the 10.x schema 
- These newly fields are added at the end of the schema which doesn't change the existing format.
-  I would work on adding the new fields to Graylog templates to support the  10.x version.

**Comment by giveen** [comment]
This issue can be closed. It wasnt an issue with the Parser but merely I was shoving my globalprotect logs into that input parser and it wasnt handling it very well.
