### ISSUE TITLE
Different API error formats returned by the same EP

### ISSUE THREAD

**Issue by zeeklop** [Graylog2/graylog2-server#13623]
I've observed that the EP used to validate Lookup Tables, Caches and Data Adapters returns a different error format depending on the field that has the error. This makes it really difficult for the UI to handle those errors and show the user a useful notification of what went wrong.

## Expected Behavior

Ideally, all errors returned from the API should follow the same format. At this point at least, this EP should pick a format and return the same payload without depending on which field is the one that has the problem.
The values the UI would need would be the field name with its hierarchy and a short message describing the problem.

## Current Behavior

Data adapter validation `url: /api/system/lookup/adapters/validate`

payload with null title:
```
{
    "id":null,
    "title":"",   
    "name":"a-title",
    "description":"",
    "config": {
        "type":"dnslookup",
        "lookup_type":"A",
        "server_ips":"",
        "request_timeout":0,
        "cache_ttl_override_enabled":true,
        "cache_ttl_override":1,
        "cache_ttl_override_unit":"MINUTES"
    }
}
```
return
```
[
  {
    "message": "must not be empty",
    "message_template": "{javax.validation.constraints.NotEmpty.message}",
    "path": "LookupTableResource.validateAdapter.arg0.title",
    "invalid_value": ""
  }
]
```
same request with a title but a bad config value:
```
{
    "id":null,
    "title":"A title",   
    "name":"a-title",
    "description":"",
    "config": {
        "type":"dnslookup",
        "lookup_type":"A",
        "server_ips":"",
        "request_timeout":0,
        "cache_ttl_override_enabled":true,
        "cache_ttl_override":1,
        "cache_ttl_override_unit":"MINUTES"
    }
}
```
return
```
{
  "errors": {
    "request_timeout": [
      "Value cannot be smaller than 1"
    ]
  },
  "error_context": {},
  "failed": true
}
```

## Possible Solution

We should probably follow the same format for all errors returned from the API. Google has a good standard that can be applied
[JSON error format](https://developers.google.com/webmaster-tools/v1/errors)

## Steps to Reproduce (for bugs)

1. Create a new data adapter without a title
2. You'll get the first error type
3. Add a title but modify a config value to be invalid
4. You'll get the second error type

## Context

I'm trying to use this EP to show meaningful error messages to the user when creating / updating Lookup Tables, Caches or Data Adapters.

## Your Environment

* Graylog Version: 5.0
* Java Version: 17
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by danotorrey** [comment]
Thanks for taking the initial look @ryan-carroll-graylog. I agree, it looks like the difference in response is due to hibernate validation being done on the resource method/aspect level with the `@Valid` annotation (which in-turn checks the `@Valid` annotations in `DataAdapterApi`) versus the inline validation being done within the method and returning a `ValidationResult` .

https://github.com/Graylog2/graylog2-server/blob/ab28169163c3f5739239818af7e550622eb67e3b/graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java#L596

https://github.com/Graylog2/graylog2-server/blob/ab28169163c3f5739239818af7e550622eb67e3b/graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java#L597

I agree that the validation results should always be consistent. I think the best course of action is to remove use of the method-level annotation validation and exclusively use the inline `ValidationResult` checks. That probably just means performing a few not empty/not null checks manually or calling the hibernate [validator manually](https://stackoverflow.com/a/19191064/1624052) and returning those errors in the `ValidationResult` object.

**Comment by ryan-carroll-graylog** [comment]
Ah that makes sense, thanks for the detailed explanation! 

Definitely agree, and seems pretty straightforward. It would probably be easiest to use the manual hibernate validator results, unless the formatting is off from the other errors, in which case we can always perform the empty/not null checks manually.
