### ISSUE TITLE
Remove default values for path configurations

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#13673]
## What?

Remove the default values for the `bin_dir`, `data_dir`, and `plugin_dir` configuration options.

- Remove the default values for the options in the `PathConfiguration` class
- Keep the option uncommented in the default `misc/graylog.conf` file, but remove their values
- Document the changes in `UPGRADING.md`
- Update manual setup documentation: https://docs.graylog.org/docs/manual-setup

## Why?

We had a customer that created a custom `graylog.conf` and forgot to include the `*_dir` settings. The Graylog server used the default values instead and created the journal directory in an unexpected directory.

Removing the default values avoids misconfiguration because the server complains on startup when required settings are missing.

Our operating system packages and the container images set these values to working defaults, so removing the default values from the code doesn't affect these common installation methods.
Only users that run Graylog using the tarballs (not recommended anymore) and developers have to adjust their configuration files.

**Comment by DevPJ9** [comment]
Hello, @bernd I would like to contribute.

**Comment by AntonEbel** [comment]
After looking into the codebase, it seems that removing the default value for the `data_dir` property is not so easy, since we use the [DEFAULT_DATA_DIR](https://github.com/Graylog2/graylog2-server/blob/62e21d76d3ca3aad6bbfcef41cd824ec8a4f123c/graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java#L32) location in these classes as well: [KafkaJournalConfiguration]( https://github.com/Graylog2/graylog2-server/blob/b7ac3ca7fb23a66752d2022676602822c56bde87/graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java#L31), [GeoIpProcessorConfig](https://github.com/Graylog2/graylog2-server/blob/b7ac3ca7fb23a66752d2022676602822c56bde87/graylog2-server/src/main/java/org/graylog/plugins/map/config/GeoIpProcessorConfig.java#L32), [Configuration](https://github.com/Graylog2/graylog2-server/blob/b7ac3ca7fb23a66752d2022676602822c56bde87/graylog2-server/src/main/java/org/graylog2/Configuration.java#L171). Removing this default value means that the user must also specify the following properties: `content_packs_dir`, `geo_ip_processor_s3_download_location` `message_journal_dir`. A better solution from a usability perspective would be for the user to specify the required property `data_dir` and for us to use that as the parent directory for the `/journal` directory, for example. Unfortunately, this is currently not possible with the [JadConfig lib](https://github.com/Graylog2/JadConfig) we are using. So we have to decide if we want to extend the JadConfig lib with such a feature or let the user specify the six properties. @boosty, what do you think about this?

**Comment by boosty** [comment]
> or let the user specify the six properties

That does not sound great. I agree with your usability argument, so we should only require `data_dir` to be set.

But if that is too much work, we should talk about postponing this issue to 5.1.

cc @bernd
