### ISSUE TITLE
Reload plugins with out graylog server restart

### ISSUE THREAD

**Issue by g4graylog** [Graylog2/graylog2-server#1395]
Hi Team,

   Not sure if we have this feature in graylog.

   I don't think the changes in plugin folder are dynamically picked up. It would be a good feature if we have this.

Thanks
-Gangadhar

**Comment by kroepke** [comment]
Graylog cannot reload plugins due to the way our dependency injection works.
I'm not aware of anything except OSGi that supports hot reloading in any kind of semi-sane way, but at the same time that flexibility comes at a very high cost. The complexity involved in allowing arbitrary code to change at runtime is immense, error prone and very hard to test.

Why do you need reloading plugins, and specifically which plugins do you need to be reloadable?
If we had specific requirements we could see if it makes sense to support this for a subset of the plugins.

**Comment by g4graylog** [comment]
I completely understand you, and the difficulties/limitations around
implementing this feature.

Usually when you have your application in production you would like to have
zero downtime. I have used Graylog Plugin API to extend/add features
specific to my business needs.


Thanks
-Gangadhar

**Comment by dennisoelkers** [comment]
I think this is not the correct way to achieve zero downtime. Instead you should set up identical nodes which can be used for load balancing and/or failover. This way you are also able to do rolling upgrades of Graylog without downtimes.

**Comment by razvanphp** [comment]
Still, what about an API to change the retention period and type on-the-fly? This was the reason for most of the restarts lately in our case.
