### ISSUE TITLE
[Graylog 4.3.9] Search button does not work when pressed Apply button on Search Time Range

### ISSUE THREAD

**Issue by hohuyphuong** [Graylog2/graylog2-server#13978]
## Expected Behavior

Search button will execute and show results when pressed Apply button on Search Time Range

## Current Behavior
On Search Time Range, choose value and press Apply button, I saw the Search button Disable and Enable, but it does not work, I must press Search Button to get the results

## Steps to Reproduce (for bugs)
1. Step 1: Choose value and apply
<img width="801" alt="Screen Shot 2022-11-16 at 15 05 24" src="https://user-images.githubusercontent.com/26562329/202129747-f6e451a4-b2b5-4b98-8457-f17447bbfab4.png">

2. Step 2: I saw Search Button Disable and Enable but does not work.
<img width="607" alt="Screen Shot 2022-11-16 at 15 10 27" src="https://user-images.githubusercontent.com/26562329/202129878-5af70acb-52a2-478d-a51a-d1bb09f5ee07.png">

3. Step 3: I click Search button to get the results
<img width="1159" alt="Screen Shot 2022-11-16 at 15 37 31" src="https://user-images.githubusercontent.com/26562329/202130186-a596d57f-2724-4636-ad86-a4a30d77372b.png">

* Graylog Version: Graylog 4.3.9
* Java Version: Oracle Corporation 1.8.0_261
* Operating System: Linux 3.10.0-1160.71.1.el7.x86_64
* Browser version: Firefox 106.0.5 (64-bit)

**Comment by dennisoelkers** [comment]
Hey @hohuyphuong,

this is working as expected. We do not execute the search when changing the time range, streams or the query string until you click the green submit button (or press enter in the query input). The only difference is for the time range presets (which are shown when you press the arrow next to the time range button). The reason for this is that most users want to change multiple parts of the search before executing it and intermediate search executions are wasteful.

I am closing this issue because it does not describe a bug. If you feel this is not capturing your original intent and/or you have additional information, please reopen it.

**Comment by hohuyphuong** [comment]
clearly, thank you so much
