### ISSUE TITLE
CORS setup

### ISSUE THREAD

**Issue by mulyoved** [Graylog2/graylog2-server#1404]
On client browser I get 
```
XMLHttpRequest cannot load http://misc-services.cloudapp.net:12900/streams. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:10000' is therefore not allowed access.
```

Did enabled rest_enable_cors in server.conf
Image is based on https://github.com/Graylog2/graylog2-images/tree/master/docker

With added server.conf
```COPY ./images/graylog/graylog2.conf /etc/graylog/server/server.conf```
 
Check rest_enable_cors is true
```
root@f58aac5c60e3:/# cat /etc/graylog/server/server.conf | grep cors
rest_enable_cors = true
root@f58aac5c60e3:/#
```

Not sure how to check that server is indeed use the right server.conf or why it does not enabled CORS

Any hint?

**Comment by joschi** [comment]
Please post the actual HTTP headers of the response you get from http://misc-services.cloudapp.net:12900/streams.
```
curl -u $GRAYLOG_USER:$GRAYLOG_PASSWORD -i -H 'Content-Type: application/json' http://misc-services.cloudapp.net:12900/streams
```

**Comment by mulyoved** [comment]
Trying to connect from this project https://github.com/Graylog2/graylog2-stream-dashboard

Headers

```
Remote Address:127.0.0.1:10000
Request URL:http://127.0.0.1:10000/views/streams.html
Request Method:GET
Status Code:304 Not Modified
Response Headers
view source
Accept-Ranges:bytes
Cache-Control:public, max-age=0
Connection:keep-alive
Date:Tue, 08 Sep 2015 12:45:04 GMT
ETag:"0-1441710270091"
Last-Modified:Tue, 08 Sep 2015 11:04:30 GMT
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,he;q=0.6
Authorization:Basic bXVseTpDYXRjaDIy
Cache-Control:max-age=0
Connection:keep-alive
Host:127.0.0.1:10000
If-Modified-Since:Tue, 08 Sep 2015 11:04:30 GMT
If-None-Match:"0-1441710270091"
Referer:http://127.0.0.1:10000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
```

**Comment by joschi** [comment]
@mulyoved The Graylog omnibus package (which is being used in the Docker image) isn't using the configuration file at `/etc/graylog/server/server.conf` at all.

In order to enable CORS headers on the Graylog REST API, I'd recommend setting the environment variable `GRAYLOG2_REST_ENABLE_CORS=true` and pass that into the Docker container (either via the [`ENV` directive in your `Dockerfile`](https://docs.docker.com/reference/builder/#env) or by overriding it in your [`docker run`](https://docs.docker.com/reference/run/#env-environment-variables) call).

**Comment by mulyoved** [comment]
GRAYLOG2_REST_ENABLE_CORS=true done the trick, thanks
