### ISSUE TITLE
Unable to create endpoint for notifications via API

### ISSUE THREAD

**Issue by edward-marrufo-graylog** [Graylog2/graylog2-server#14257]
## Expected Behavior

As a Graylog user I expect that anytime I create a notification via the API browser/API it should be created without any errors.
## Current Behavior

Currently when creating a notification via the front end there are no issues. If there is a notification already created we can grab the code via the "get: events/notifications/{notificationid}" end point. Delete the notification just to ensure everything is in a default state. Under Events/Notifications : Manage event notifications > Post Events notifications once we paste in the previous code provided to us by Graylog we get the following error:

`{
  "type": "ApiError",
  "message": "Couldn't deserialize value: {\"is_set\":false} (set_value must be a string and cannot be empty or missing)\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 9, column: 5] (through reference chain: org.graylog.events.notifications.AutoValue_NotificationDto$Builder[\"config\"]->org.graylog.events.notifications.types.AutoValue_HTTPEventNotificationConfig$Builder[\"basic_auth\"])"
}`
## Possible Solution

Even when creating the notification with the default model schema we get other errors so I'm unclear what is causing this.
## Steps to Reproduce (for bugs)

Check the steps above for recreating this error.

## Context

Currently this customer is unable to create notifications via API so this is hindering their workflow.
Please check HS-1327718548 for further details.
## Your Environment

* Graylog Version:5.0.1

**Comment by danotorrey** [comment]
Thanks for the issue @edward-marrufo-graylog. As noted on the ticket, I think this is working as designed:

The request to update an HTTP notification is slightly different than the response value that they are trying to use. This is because the Basic Authentication an API Secret are stored on create, but they are not returned in the response in the first API request to retrieve the notification (for security reasons). To set those, a slightly different request payload is needed.

To update an HTTP notification without changing the Basic Authentication or API Secret, the following API request payload can be used.

```
PUT /api/events/notifications/<notification-id>
{  "id": "<id>",
  "title": "title",
  "description": "description",
  "config": {
    "type": "http-notification-v1",
    "basic_auth": {
      "keep_value": true
    },
    "api_key": "key",
    "api_secret": {
      "keep_value": true
    },
    "url": "http://my-url/"
  }
}
```

To update either of those values, the basic_auth and/or api_secret values can be changed to: "set_value": "the-new-value". For example:

```
PUT /api/events/notifications/<notification-id>
{
  "id": "<id>",
  "title": "title",
  "description": "description",
  "config": {
    "type": "http-notification-v1",
    "basic_auth": {
      "set_value": "the-new-auth-value"
    },
    "api_key": "key",
    "api_secret": {
      "set_value": "the-new-secret-value"
    },
    "url": "http://my-url/"
  }
}
```
The request should be successful with either of these payloads.
