### ISSUE TITLE
Create a warning when a linked event definition is deleted which is referenced in a correlation

### ISSUE THREAD

**Issue by edward-marrufo-graylog** [Graylog2/graylog2-server#14302]
## What?

As a Graylog user I should expect a warning telling me when I go to delete an already existing correlation which contains a linked event definition.

## Why?

This is important because I could inadvertently delete an existing/useful event definition which would break my correlation.  Currently when deleting the event definition, there is no warning and Graylog just lets you delete it similar to doing rm -fr / in Linux.

See HS-1294294640 for more details.

**Comment by danotorrey** [comment]
I tested and confirmed: When an event definition that is added to another correlation is deleted, there is no warning, and the event definition page then only displays the other event definition id. 

I also confirmed by looking at the code, the Correlation Processor will ignore that deleted event definition when executing the correlation, since it will not be found in the `EventDefinitionService` any longer.

![image](https://user-images.githubusercontent.com/3423655/211086930-0e61c44a-675d-438f-afef-479ffadcd5cc.png)
