### ISSUE TITLE
Send E-Mail to an recipient gathered from field

### ISSUE THREAD

**Issue by r4msd** [Graylog2/graylog2-server#14927]
A feature where an E-Mail can get send to an recipient who's e-mail address is in a field from the event.

## What?
A feature where an E-Mail can get send to an recipient who's e-mail address is in a field from the event.

## Why?
Use Case:

User locks itself in the ldap system, ldap system logs this to logfile (with users-email)->logs get indexed in graylog: Send this user an email why they got locked out from systems (reason of lockout is part of the logline)

## Your Environment
* Graylog Version: 5.0.4
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: n/a

**Comment by r4msd** [comment]
HS-1485552145

**Comment by drewmiranda-gl** [comment]
Implemented in Graylog 6.0.0 via https://github.com/Graylog2/graylog2-server/pull/17588

**Comment by kingzacko1** [comment]
With the PR mentioned in the previous comment, a new feature was released to allow for population of the email recipient, sender, and reply to fields of an email notification by looking up email addresses in a lookup table using the value of a field in the event as the lookup key. It doesn't allow to directly populate those fields with values from arbitrary message fields due to security concerns, but by creating a simple MongoDB lookup table and populating it with the necessary key-value pairs in a pipeline rule, it can be accomplished.
