### ISSUE TITLE
Elasticsearch 2.0.0 is released

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-server#1518]
https://www.elastic.co/blog/elasticsearch-2-0-0-released

**Comment by joschi** [comment]
Elasticsearch will probably be supported by Graylog 2.x, but not by Graylog 1.x due to incompatibilities in the TCP transport and the internal protocol.

This being said, there's an *experimental* branch for Elasticsearch 2.0.x support already: https://github.com/Graylog2/graylog2-server/tree/elasticsearch-2.0
