### ISSUE TITLE
Cannot assign, remove, or edit notification in Illuminate created event in 5.1.x

### ISSUE THREAD

**Issue by thejoeschmosho** [Graylog2/graylog2-server#15916]
When trying to add a notification to an Illuminate Event in 5.1.x, you are met with a message that says "This particular Event Definition has been marked as immutable when it was created, therefore it cannot be edited," which prevents you from editing anything about the event in question.  That includes adding, removing, or modifying a notification in that event, making it so that illuminate events cannot have notifications attached to them after install of 5.1.x.  This was tested on 5.1.0, 5.1.1, 5.1.2, and 5.1.3

## Expected Behavior
There is an ability to add, remove, and/or modify a notification in an Illuminate event

## Current Behavior
The UI does not allow you to touch notification settings on an Illuminate event

## Steps to Reproduce (for bugs)
https://graylog.zoom.us/rec/share/SlEUOmRHhnUOY7wmzoi7CxX-6CB8iNh-VYNvUXNkcahc_nl_-zImH1bqV_qJFOrC.UslD2MlK_vRNbWWg?startTime=1688758535000
Passcode: uppk8&hL

**Comment by rich-graylog** [comment]
This has to do with the event definitions from Illuminate being scoped entries in newer versions - if a user was allowed to add a notification to an Illuminate event, it would be removed when Illuminate is upgraded to a newer version.

As a temporary solution, we can remove the edit funcationality and direct the users to duplicate the event so that edits can be made.

For 6.0, as we look to revamp the Event Definitions, we should look to decouple notifications from events in a way that they can be added to scoped entities without causing issues on Illuminate content updates.
