### ISSUE TITLE
i18n support program(only frontend)

### ISSUE THREAD

**Issue by oluul** [Graylog2/graylog2-server#1648]
hi,all
graylog2-web-interface doesn't support i18n;

# Gettext?
Gettext is an old translation standard. It solves a unique set of problems when dealing with things like pluralization and positional interpolation. There are implementations of gettext in nearly every language (including javascript). I wasn't happy with the quality, safety, or speed of other javascript implementations and thus Jed was born. You can read more about Gettext here: [gnu.org/software/gettext](http://gnu.org/software/gettext/)

## Optional technology selection: 
- [i18next](https://github.com/i18next/i18next) (recommend)
- [jed](https://github.com/SlexAxton/Jed)
- [sprintf javascript implementation](https://github.com/alexei/sprintf.js)
- [po2json](https://github.com/mikeedwards/po2json)

## Implement:
- Extract translatable strings from given input files.
  - [xgettext of GNU gettext](https://www.gnu.org/software/gettext/)
  - [xgettext node.js implementation](https://github.com/gmarty/xgettext)
- translate source file:

    jed , i18next

Recently I'll submit code

**Comment by kroepke** [comment]
Hi!

We have no plans to support i18n at this point, due to the immense amount of work involved. Each UI component will have to be touched and subsequently be translated for this effort to make sense.

Furthermore, it is not enough to simply translate text content, all the dates and numbers should be localized, too, which is even more tricky work.

Given that we neither have plans nor have the cycles to review such a huge PR right now, I would discourage you from investing lots of time in this right now. Of course Graylog is free software and you can still work on this if it is important to you, but please don't expect us to be able to review/merge this any time soon.

Best regards,
Kay
