### ISSUE TITLE
Elasticsearch nodes freezes due to sudden memory contention / GC

### ISSUE THREAD

**Issue by Ikke** [Graylog2/graylog2-server#1680]
Regularly, once a day (except for weekends, might be user related), we have to restart our ES cluster because each node freezes, either due to GC:
> [2016-01-08 13:21:36,355][WARN ][monitor.jvm              ] [nllog002] [gc][old][59372][138] duration [19.2s], collections [1]/[19.3s], total [19.2s]/[17.3m], memory [29.8gb]->[27.3gb]/[29.8gb], all_pools {[young] [1.1gb]->[62.9mb]/[1.1gb]}{[survivor] [149.7mb]->[0b]/[149.7mb]}{[old] [28.5gb]->[27.2gb]/[28.5gb]}

Or due to shard failures:

> [2016-01-08 13:19:39,646][WARN ][indices.cluster] [nllog003] [[graylog2_62][4]] marking and sending shard failed due to [failed to create shard]
...
Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [graylog2_62][4], timed out after 5000ms

Restarting each node fixes the problems again.

Our ES nodes have 76, 86 and 96G of memory, the jvm heap size is 31G.

Normally, the heap usage is around ~40% average, but during the freezes, it suddenly increases to >80%

Any idea what causes this, and how to fix / limit these issues?

**Comment by onyxmaster** [comment]
Same problem here. When running some queries (even for small ranges like last 5 minutes, covering ~1M of messages) the ES occasionally goes into the GC coma (~10s head-to-tail collects). ES disks are idle, CPU is not overoaded, graylog server buffers messages, because ES does not accept writes. Currently we have 16G heap sizes and 128G. We have 3 ES shards (separate physical machines) and only 1 or 2 shards usually exhibit this problem. Restart fixes the problem, until the queries are run again.
We upped heap size to 26G, but I really doubt this will help.

I wonder if there is some kind of timeout and auto-retry mechanism built into graylog that flood ES with queries, or if it's an ES bug.

graylog-server v1.3.2
ES v1.7.4
Oracle Java 1.8.0_66-b17

**Comment by AndyWTBlueHair** [comment]
So i'm having almost identical issues to onyxmaster, excluding the requirement for a query, this will handle randomly throughout the days and cause the UI to through 500s. Same configuration.

**Comment by joschi** [comment]
Did you try to solve your problem with the help of the nice people in the Elastic discussion forums at https://discuss.elastic.co/c/elasticsearch?
Since this is a problem with Elasticsearch, this seems to be the place to ask those questions.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
