### ISSUE TITLE
No Backlog even with RFC5424 rsyslog

### ISSUE THREAD

**Issue by navidf10** [Graylog2/graylog2-server#1704]
Hi,

I'm new to graylog-server. I installed it on an ubuntu server and everything works fine except that when a message is routed to my test stream, the alert via email doesn't display any message (no backlog). The server sending the rsyslog messages is set to format its messages with RFC5424 format. the strange thing is that Graylog receives the messages correctly (with all the right fields and all) but still when routed loses data (??). 

I would appreciate a little help on this matter. 

Thank you in advance guys.
Great work. 

Regards,
N.

**Comment by bernd** [comment]
I believe that this is related to https://github.com/Graylog2/graylog2-server/issues/2382 which will be fixed in the upcoming Graylog 2.1 via https://github.com/Graylog2/graylog2-server/pull/2546

I am closing this now, please re-open if you still have this issue with Graylog 2.1. Thank you for the report!
