### ISSUE TITLE
Graylog2 can't accept 'create_at' as additional field

### ISSUE THREAD

**Issue by GEverding** [Graylog2/graylog2-server#1730]
I've been using graylog2 version 1.3.0 and there seems to be some issue with including a ```created_at``` additional field. Looking at the server logs if ```created_at``` is not a integer it fails to parse the value of the key. Is there a reason this behaviour is not documented or is this a bug?

Example Logs
```
[7]: index [graylog2_20], type [message], id [24fc9b80-c548-11e5-98ee-02420a000303], message [MapperParsingException[failed to parse [created_at]]; nested: NumberFormatException[For input string: "bar"]; ]
```
```
2016-01-27T22:49:05.276Z ERROR [GelfCodec] Could not parse JSON, first 400 characters: {"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_created_at":2016-01-27T21:04:57.195Z}
 at [Source: {"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_created_at":2016-01-27T21:04:57.195Z}
 at [Source: {"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_created_at":2016-01-27T21:04:57.195Z}

```

```

**Comment by joschi** [comment]
@GEverding The character sequence `2016-01-27T21:04:57.195Z` is not a valid string. JSON only supports a few datatypes (https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example), so you'll need to provide this timestamp in a different format, e. g. as a number (milliseconds since UNIX epoch) or as a string (`"2016-01-27T21:04:57.195Z"`).

Additionally, Elasticsearch seems to have figured out that the `created_at` field contains only numbers via its dynamic mapping. If you want to ensure a certain type for this field and not rely on Elasticsearch's automatic detection, you'll have to create a custom index mapping (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping.html) and use that in an index template (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-templates.html).
