### ISSUE TITLE
Pipeline rule simulator: JSON inside message fields do not parse properly unless double quotes escaped

### ISSUE THREAD

**Issue by Joel-Duffield-Graylog** [Graylog2/graylog2-server#17464]
## Expected Behavior

If you have some JSON that you want to test parsing, flattening, etc in the rule simulator you should be able to paste that into the rule simulator box and test your rule against it.

## Current Behavior

When you place standard JSON into the rule simulator field, it appears to work, you get fields showing in the simulator etc however some functions do not work on them. specifically, flatten_json does not work. You can make it work, but you need to escape all the double quotes in the JSON.

## Possible Solution

Ideally let the JSON be pasted in this way, or at least produce a warning so you can manually change your example

## Steps to Reproduce (for bugs)

1.Place this into the rule tester
`message: 2023-11-20 17:13:56.664 INFO 1 --- [ spring] infoLogger : {"user": "NA", "machineName": "customers-xyz-check-initiator-xxxx-abc", "machineIP": "1.2.3.4","loggerLibName": "java.logging", "loggerLibVersion": "1.10", "level": "info", "timestamp": "1700500436664"}`
2. use this rule code
`rule "parse JSON"
when
  true
then
 let clean_json = split(":\\{", to_string($message.message));
 let valid_json = "{" + to_string(clean_json[1]);
 //check that cleaning went properly
 set_field("valid_json", valid_json);
 set_field("is_json_valid", is_json(parse_json(valid_json)));
//flatten json into fields
 let flattened_json = flatten_json(to_string(valid_json), "flatten");
 set_fields(to_map(flattened_json));
end`
3. run the rule simulator, the is_json will return true, but flatten_json will not work.

## Context

There are no warnings etc that tell you this isn't a valid value to test etc, so you just think something is wrong in your rule code. This used to work in the previous version of the rule tester that only allowed the message field.

## Your Environment

* Graylog Version: Graylog 5.2.0+8a9ccef

**Comment by LouisAtGH** [comment]
There are two simulators for pipelines:
- the overall pipeline simulator. I did not notice problems with that one
- the simulator as related to the Managed rules. Which does not behave correct in certain situations

The problems I met are all related to "spaces"  disappearing / missing during parsing. 
(just an) example:

an input string like
myfield: arp: 192.168.100.5 moved from 00:a0:98:70:ce:7c to 58:9c:fc:10:ff:ab on lagg1.100
is parsed like
arp:192.168.100.5 moved from 00:a0:98:70:ce:7c to 58:9c:fc:10:ff:ab on lagg1.100
which is NOT working of course :(


After discovering that the problem was there (in first instance, I lost a lot of time, not understanding why it was not working), I used the overall pipeline simulator as work around

I had the problem when defining and testing grok patterns. Also using 5.2.0+

**Comment by LouisAtGH** [comment]
I discovered more issues related to simulators or perhaps grok in general (I do not know). There seems to be a link between the faulty simulator behavoir and the character ":' 

I also noticed problems when parsing stings containing "=" . I do not manage to parse stings containing "=" correctly.  But that could be grok issue and not especially simulator related.
