### ISSUE TITLE
Graylog 2.0.0 alpha sessionid encryption scheme

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#1794]
In 1.x the sessionid in the session cookie is encrypted using AES-128 ECB, and the 16 first characters of application.secret as the key. What has changed to 2.x?

I assumed the key is 16 first characters of password_secret from graylog.conf, because it seems to be the only one left. However decrypting the sessionid fails suggesting that either the key is wrong, or the used algorithm has been changed.

**Comment by bernd** [comment]
The session cookie handling has changed in Graylog 2.0. The session ID is now stored in the browser's local storage.

What are you trying to achieve?

**Comment by mikkolehtisalo** [comment]
Decrypting the cookie in web server in order to augment access logs with information mandatory for audit logs (e.g. authenticated user name), something that Graylog does not offer out of the box:

https://github.com/mikkolehtisalo/mod_gllog

It seems Play 2.4 has moved to AES-128 CTR based on their documentation, but I am unsure about the effect of that change. Mainly that is because the javadoc there makes very little sense.

**Comment by dennisoelkers** [comment]
This is not possible with 2.0 anymore, because the web interface of 2.0 is js-only and therefore the web interface endpoint is returning only static assets and does not do any kind of authentication anymore. For 2.0 you would need to take a look at the [RestAccessLogFilter](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/rest/RestAccessLogFilter.java) which you can utilize to have log stream of all REST API accesses including the usernames.
