### ISSUE TITLE
Using "Add to query" on Search/Dashboard pages can sometimes cause the time range and search box to disappear

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#18053]
Using "Add to query" on Search/Dashboard pages can sometimes cause the time range and search box to disappear

See https://videos.graylog.com/watch/GcBCFksCBq8MnWBtXFzbJK

Tested with preview.graylog.cloud

Please let me know if there are any questions.

## Expected Behavior

time range and search box do not disappear.

## Current Behavior

Using the "Add to query" function(see video) can sometimes cause time range and search box to disappear.

## Steps to Reproduce (for bugs)

See video. I'm not sure what variables affect this but the behavior is not consistent. Sometimes this bug occurs after only 2 or 3 uses of "add to query" other times it takes more.

how i reproduced it in the video was:
1. open a dashboard
1. find a value to click on that you can do “add to query”
1. add the value to query
1. use the search text box to remove the text and execute search again (same state as loading the dashboard page initially)
1. repeat steps 3 and 4 until the bug occurs

## Context

When this occurs the only way i have found to work around this is to refresh the entire page which can cause you to lose your query.

## Your Environment

* Graylog Version: 5.2.2 Cloud

**Comment by drewmiranda-gl** [comment]
not sure if this is helpful, it appears manually adding z-index: 1 appears to make the hidden elements reappear…
![image](https://github.com/Graylog2/graylog2-server/assets/107503402/b0b76c6a-fe99-4627-b02e-ea87842794cd)

**Comment by linuspahl** [comment]
Interesting. I had a quick look and it seems to be related to the query input. One of its elements has `position: absolute` and a full width and height, because its parent no longer has `position: relative`.

For some reason the container component looses the `ace_editor` class (which has the styling `position: relative`) .

Default:
<img width="718" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/46300478/3172ecba-7c5c-417a-925f-41f7c680fe18">

When the error occurs:
![image](https://github.com/Graylog2/graylog2-server/assets/46300478/a421eb20-5ce6-4927-9034-b8c88545bb6a)

**Comment by BBruce-Graylog** [comment]
Adding the Zendesk ticket we have for the issue: [(https://graylog7416.zendesk.com/agent/tickets/124)]
