### ISSUE TITLE
Clarify extractor compatibility

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1831]
From the mailing list, there is a report of a change in the extractors structure. Extractors exported from versions pre 2.0, had an `extractor_type` field, whereas in 2.0 that field is called `type`.

We should verify that we support old extractors or clarify that in the documentation, probably even notify plugin creators.

**Comment by joschi** [comment]
FWIW, graylog-server is still using `extractor_type`: https://github.com/Graylog2/graylog2-server/blob/2.0.0-alpha.2/graylog2-server/src/main/java/org/graylog2/rest/models/system/inputs/extractors/requests/CreateExtractorRequest.java#L65

**Comment by the-Pretender** [comment]
Well, maybe it should, but it doesn't. Exporting a newly created split and index extractor on graylog 2.0.0 alpha 2 yields the following:
<code>{
  "extractors": [
    {
      "id": "019c12f0-d633-11e5-b850-005056b58d98",
      "title": "cef_version",
      **"type": "split_and_index",**
      "converters": [],
      "order": 0,
      "exceptions": 0,
      "metrics": {
        "total": {
          "time": {
            "min": 90,
            "max": 330,
            "mean": 189,
            "std_dev": 76,
            "95th_percentile": 330,
            "98th_percentile": 330,
            "99th_percentile": 330
          },
          "rate": {
            "total": 6,
            "mean": 1.1225790991670823,
            "one_minute": 1.2,
            "five_minute": 1.2,
            "fifteen_minute": 1.2
          },
          "duration_unit": "microseconds",
          "rate_unit": "events/second"
        },
        "converters": {
          "time": {
            "min": 1,
            "max": 2,
            "mean": 2,
            "std_dev": 0,
            "95th_percentile": 2,
            "98th_percentile": 2,
            "99th_percentile": 2
          },
          "rate": {
            "total": 6,
            "mean": 1.1225890412654602,
            "one_minute": 1.2,
            "five_minute": 1.2,
            "fifteen_minute": 1.2
          },
          "duration_unit": "microseconds",
          "rate_unit": "events/second"
        }
      },
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "cef_version",
      "extractor_config": {
        "index": 1,
        "split_by": "|"
      },
      "creator_user_id": "admin",
      "condition_type": "none",
      "condition_value": "",
      "converter_exceptions": 0
    }
  ],
  "version": "2.0.0-SNAPSHOT"
}</code>
The same extractor in 1.3.2:
<code>{
  "extractors": [
    {
      "condition_type": "none",
      "condition_value": "",
      "converters": [],
      "cursor_strategy": "copy",
      "extractor_config": {
        "index": 1,
        "split_by": "|"
      },
     ** "extractor_type": "split_and_index",**
      "order": 0,
      "source_field": "message",
      "target_field": "cef_version",
      "title": "cef_version"
    }
  ],
   "version": "1.3.2 (e7c49b6)"
}</code>

In order to be able to import the latter to graylog 2.0.0 alpha 2, <code> extractor_type </code> has to  be changed to <code>type</code>, or the following error is thrown in console: 
<code>Instantiation of [simple type, class org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest] value failed: Null extractorType</code>
