### ISSUE TITLE
Default message sorting in search results is not transparent in 5.1 and beyond

### ISSUE THREAD

**Issue by Joel-Duffield-Graylog** [Graylog2/graylog2-server#18348]
As of Graylog 5.1 when you perform a search the default sort order shown is timestamp, however in actuality it is timestamp and then gl2_message_id. This can cause problems is data types are incorrect on the gl2_message_id field, because you will get an error about being unable to run aggregations on the gl2_message_id field, however to the user that field does not appear to be used in any aggregations.

## Current Behavior

The two major issues are that nothing in the product tells you this is happening, the sort order just says timestamp, and there is absolutely no way to override this behaviour if you wanted to.
You can change the sort to another timestamp field, a beats timestamp field for example, but you need to do that every time. 
## Possible Solution

- An option to disable this function in server.conf etc, with some sort of appropriate warning message that points you towards this.
- Using a special brand new sort field as the default called timestamp+message_id, and you could still choose the regular timestamp field as the sort and it would behave like it did pre 5.1.

 

## Steps to Reproduce (for bugs)

1. change the gl2_message_is field to any data type other than keyword
2. load the search page

## Your Environment

* Graylog Version: 5.1+

**Comment by mpfz0r** [comment]
Some more context:

The sorting comes from this feature
https://github.com/Graylog2/graylog2-server/pull/6711
specifically
https://github.com/Graylog2/graylog2-server/blob/master/graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSMessageList.java#L107

The change was done with the mindset that we are in control of all`gl2_*` mappings and it is safe to assume it is of type `keyword`.

However, due to an Illuminate bug the type got changed from `keyword` to `text`:
https://github.com/Graylog2/graylog-project-illuminate/issues/739
This has been fixed and customers should update their illuminate package.

I'm not aware of any other problems with this sorting default.

I propose we write a migration that tries to fix the mapping type on all managed graylog indices.
We could do this together with:
https://github.com/Graylog2/graylog2-server/issues/18387
