### ISSUE TITLE
Problem with the search function

### ISSUE THREAD

**Issue by j-n-s-k-n-r** [Graylog2/graylog2-server#1853]
### Problem description

Hey Guys,

i have a short question about searching with graylog.

I have to highmark all session who started as a root. 
For this, i use a SuseLinux Enterprise Server (SLES) 12.1.

But when i type in the search windows, this works great. I can see when a session for root started, when it ends and when someone has type a false passwort.
But in the message field also are messages  from ngix or graylog-web or mongodb (see picture below)

![searchquestpng](https://cloud.githubusercontent.com/assets/17450611/13287431/5721eee2-db07-11e5-9791-0401e5b7c5d5.PNG)

Is the any question or inaccuracy, feel free to ask me.
Thank you for helping

Sincerely yours
Jonas

### Environment

* Graylog Version:  v.1.3.3
* Elasticsearch Version: i dont know 
* MongoDB Version: i dont know
* Operating System: Ubuntu 14.04 (i downloaded the .ova file from www.graylog.com)

**Comment by joschi** [comment]
The virtual appliances record some of their own logs (e. g. nginx access logs) in order to give new users an idea how a populated system looks like.

If you don't require or don't want to record those log messages, simply delete the pre-created inputs in the virtual appliance (see System &rarr; Inputs in the Graylog web interface).

**Comment by j-n-s-k-n-r** [comment]
Great thanks for the fast answer :)
