### ISSUE TITLE
Blocking Filters

### ISSUE THREAD

**Issue by kablz** [Graylog2/graylog2-server#1866]
### Problem description
On a filter plugin we enrich some messages based on a defined field. This enrichment may use a long time (1...30sec). HTTP/API call to an other service.

During this time new arrived messages are not processed anymore (until max number of threads). 
For example if we have eight messages which has to be enriched, no other messages pass into Graylog. Which may not need to be enriched. 
 
### Steps to reproduce the problem
Create a Filter Plugin. 
if(message.getField(fieldX) != null){
sleep(20000) //simulate the enrichment
}else{
 //just go on 
}

Send some logs which match the if. And after some other messages. Other messages could pass fast. But they're blocked... Because the thread is blocked of the matching messages. 

### Environment

* Graylog Version: v1.3.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System: RHEL 6

**Comment by kroepke** [comment]
I'm afraid this isn't possible, because of math. Eventually you will exhaust any number of threads if you have more messages of this type than you have free threads.

The only option I can see is to aggressively cache enrichment results in your plugin, if that's possible.

Since this is a general problem of queuing theory, I'll close this issue, because there's simply nothing we can do to make it go away.

Thanks!
