### ISSUE TITLE
Compound types may break table sorting 

### ISSUE THREAD

**Issue by AntonEbel** [Graylog2/graylog2-server#18696]
(Original title `Field type mapping breaks table sorting`, changed to better describe what is the real source of the problem.)

Adding a field to the message table on the search page and sorting by this field leads to different error messages:

![image](https://github.com/Graylog2/graylog2-server/assets/25727579/12fc7bdd-5521-45d6-9e9a-7068bbee0bc4)

Field with no mapping:
```
While retrieving data for this widget, the following error(s) occurred:
Unable to perform search query: OpenSearch exception [type=query_shard_exception, reason=No mapping found for [custom_port] in order to sort on].
```
Field with mapping:
```
OpenSearch exception [type=class_cast_exception, reason=class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.Number (org.apache.lucene.util.BytesRef is in unnamed module of loader 'app'; java.lang.Number is in module java.base of loader 'bootstrap')].
```

* Graylog Version: Graylog 6.0.0-beta.2+8b77fdb

**Comment by luk-kaminski** [comment]
I was able to reproduce the problem.

A general comment:
It is not a bug introduced by the new Field Type Mapping functionality.
One can change types in a more difficult manner, using direct calls on OS/ES, and will see **exactly** the same bug.

Field Type Mapping functionality makes it easier to change field types, so it also makes it easier to create compound fields, where in different indices they have different types, that do not work well together when it comes to sorting.

**Comment by luk-kaminski** [comment]
We have a similar problems with compound fields:
https://github.com/Graylog2/graylog2-server/issues/16165
https://github.com/Graylog2/graylog2-server/issues/10559

They have not been addressed properly yet.

If we believe this bug is a high-priority bug, I suggest considering one of the potentially quick FE solutions:
1. Blocking sorting on compound fields completely.
2. Re-trying a query, but without a sort, if query with sorting fails.
