### ISSUE TITLE
Data Node client certificates generated are not formatted properly

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#18781]
Data Node now allows generating client certificates to use for 3rd party systems. The generates certs, however, are not properly formatted and cannot but copy/pasted as is without fixing the formatting. For example, grafana will reject the certs.

The cert generated has all contents on a single line without any line endings (`\n`)

## Expected Behavior

Certs are generated as

```
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
```

## Current Behavior

Certs are generated as

```
-----BEGIN CERTIFICATE-----[...]-----END CERTIFICATE-----
```

## Possible Solution

Format cert on output

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This is very minor but some users won't have an understanding of certs and won't understand they may need to fix the formatting.

## Your Environment

* Graylog Version: 6.0 beta1,2,3
* Java Version: Bundled
* OpenSearch Version: Data Node (OpenSearch 2.12)
* MongoDB Version: 6.0.14
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 123.0.6312.59 (Official Build) (arm64)

**Comment by janheise** [comment]
I'll see if I find a better solution for it. We transport the certificates from the BE to the FE via json. If I include linebreaks, they either show up as `\n` in the text and break the certificate by doing so or they break the json format. That's why I started with removing them - but that creates the manual step you talk about.
