### ISSUE TITLE
V6.0 RC1 - Ctrl+Shift+S Keyboard shortcut to save as dashboard conflics with Windows 11 Screen Snapshot capture

### ISSUE THREAD

**Issue by jivepig** [Graylog2/graylog2-server#18897]
Defaults for ctrl+shift+s in Graylog keyboard shortcuts conflicts with windows keyboard defaults.
When this is done in a browser with any other window it brings up the windows screen capture options.
When it is done via the active window with Graylog it launches Graylog Save as dashboard.

## Expected Behavior
A different Keymap should be used by default.

## Possible Solution
Different map by default?

## Steps to Reproduce (for bugs)
perform steps as noted

## Your Environment

* Graylog Version: V6.0RC1
* Java Version: n/a
* OpenSearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: n/a

**Comment by jivepig** [comment]
Actually you are correct. Ctrl+shift+S is the default screen capture commands within the browsers: Firefox and Microsoft Edge not windows. So if you are using those two browsers the issue would conflict.

**Comment by linuspahl** [comment]
Alright. I am not really sure what the best solution here is. It looks like other web applications overwrite this keyboard shortcut as well. For example it triggers the voice typing feature in Google Drive when you edit a document.

We can either
- find a new keyboard shortcut, which has no conflict with all keyboard shortcuts in all browsers on all operating systems and potentially make the user experience worse for all users who do not use the screen capture feature in Firefox and Microsoft Edge on Windows 11.
- keep the current keyboard shortcut with the downside that you have to use the Windows screen capture tool instead of the browser screen capture tool Firefox and Microsoft Edge on Windows 11.

cc @Emy-01

**Comment by jivepig** [comment]
Looking at it, realistically if you needed to capture screenshots of your Graylog web browser, it's really only the problem.  So switching to a different tool to capture those is the solution.  It is really only a problem when the browser is active with Graylog.  So perhaps it's not something worth worrying about at this time.

**Comment by linuspahl** [comment]
Sounds good, let's close this issue for now. If there are more concerns in the future, we can still reopen it and find a different solution.
