### ISSUE TITLE
Export CSV on Safari asks for API authentication

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1898]
### Problem description
When exporting search results as CSV from the web interface, Safari asks for a username and password to authenticate against Graylog server. It should use the current session to get it instead.

### Steps to reproduce the problem
1. Open Graylog in Safari
2. Do a search, and click on the "Export as CSV" button
3. Authentication dialogue appears, instead of initiating the CSV export with the current credentials

### Environment

* Graylog Version: 2.0.0-alpha.5

**Comment by jhaar** [comment]
FYI, I see this too, but with different symptoms

Under Firefox I get a warning

You are about to log in to the site "graylog2.trimble.com" with the username "e482ce63-0f1b-4d62-add3-c9acba4472ae", but the website does not require authentication. This may be an attempt to trick you.


Under Chrome I get no warning, but in both cases it returns a 404 and fails. I noticed the query begins with "//search", which I assume should have been "/search" - so maybe that's related

Jason

**Comment by edmundoa** [comment]
@jhaar: That seems to be another issue to me, specially since the request fails. Please use #2111 to track it and add some extra information (I assume you are using Graylog 2.0.0-beta.3 from other issues, but still to be sure).

**Comment by dennisoelkers** [comment]
@jhaar: could you please add to #2111 what you get when you execute `window.appConfig.gl2ServerUrl` in your browser's javascript console when you are logged in to the Graylog web interface?

**Comment by jhaar** [comment]
I think the problem is related to the "//" issue I mention above. We're running graylog behind haproxy  and are doing rewrite tricks to make both port 9000 and 12900 appear to be the same server (I really think that was a bad idea to separate them apart you guys!). ie we remap "waf:443/api(.*)" to "backendserver:12900/$1"

What I'm seeing in the haproxy logs is calls to things like "GET /api/search/universal/relative" work fine, but when I do an CSV export, I see "GET /api//search/universal/relative/export" and that fails

Notice the double slash? If I then call them by hand directly to 12900, "/api//search" and "/api/search" return entirely different pages. It looks to me like your HTTP API is not normalizing the URI? I'll see if I can clean that up in haproxy - but that's looking like the problem

**Comment by edmundoa** [comment]
I have quickly checked this in 2.1.0-beta.2 and the issue is not longer present. Safari now also warns about a possible phishing attempt, but the download works fine when clicking on the "ignore warning" button. I am therefore closing this issue.
