### ISSUE TITLE
After enabling "Force rDNS" to existing input graylog stops working

### ISSUE THREAD

**Issue by piesu** [Graylog2/graylog2-server#2010]
### Problem description
After enabling "Force rDNS" to existing syslog udp input whole webui/graylog-server stops working. Can't list inputs, after restarting I even can't get login page

### Steps to reproduce the problem

1. Create Syslog UDP input with "Force rDNS" set off
2. Collect few msg's. source is incorrect as in https://github.com/Graylog2/graylog2-server/issues/125
3. Edit input, set "Force rDNS" on, save

Now you lost control over whole graylog server, can't even login. Moving elasticsearch files didn't help, I couldn't find anything in logs regrding issue. Manually deleting input in mongo helped.

### Environment

* Graylog Version: 2.0.0-beta.1
* Elasticsearch Version: 2.2.1
* MongoDB Version: 2.4.10
* Operating System: Debian Jessie
* Browser version: Iceweasel 44.0.2

**Comment by kroepke** [comment]
@piesu Can you please check the metrics for that input?
This sounds like your resolver is taking too much time, thereby blocking too many threads in the server.
Can you please paste the timing information for `resolveTime` on that input?

**Comment by piesu** [comment]
@kroepke Sure, but where I can check this timing? Although when I removed input in mongodb, and created new one with Force rDNS on, everything works fine for me. I get ip as source, but this is exactly what I wanted.

**Comment by joschi** [comment]
@piesu See System &rarr; Nodes &rarr; Metrics in the Graylog web interface.

**Comment by kroepke** [comment]
FWIW this code hasn't changed in ages, so at least it's not a new problem.
However, as rDNS is costly, we usually discourage using it and it sounds like you actually want the IP address anyway (and not the hostname of that address).

**Comment by piesu** [comment]
Yeah, I want ip address. Without it I was getting like in #125 - month as a source.

**Comment by kroepke** [comment]
Ok, that sounds like you really need to extract the message correctly.

Looking at the JVM code that gets called it looks like if an IP does not have a name associated with it, the fallback will be the IP in its textual form. Since you do have a remote IP already this will practically waste the DNS traffic, introducing a potentially long delay (which greatly depends on how robust your resolver setup is).
That delay can easily kill everything, as it blocks so many threads that the JVM can't make any more progress.

As such I don't think it's a bug but more of a confusing interface.
What you most likely want is to use the `gl2_remote_ip` field and copy it into the `source` field with an extractor (Copy input extractor).

I'll close this for now, as there should be a workaround.

Thank you,
Kay

**Comment by piesu** [comment]
@kroepke How I can copy this `gl2_remote_ip` field? It isn't visible in fields list on extractor configuration page?

**Comment by kroepke** [comment]
It could be that it is masked on that page, in 2.0 it should be available.

For now navigate to a suitable message that was received over the network and expand it from a search. It should list the gl2_remote_ip field. From the dropdown on the right hand side you can directly get to the extractor page.

**Comment by piesu** [comment]
When in search I click on "all fields" in field list, I can get gl2_remote_ip field visible. Anyway when I click on selected message, on list of fields I don't get gl2_* fields to create extractor from there. I get same list like on extractor creation page.
