### ISSUE TITLE
Multiple same Groke Pattern in same extractor

### ISSUE THREAD

**Issue by matthgyver** [Graylog2/graylog2-server#2029]
### Problem description

Hi,
Actually, it is not possible to use more than one same grok pattern in one same extractor.
### Steps to reproduce the problem

Example with this DHCP logs

> Apr 5 11:57:53 srv-dhcp dhcpd: DHCPDISCOVER from xx:xx:xx:xx:xx:xx (android-foobar) via 10.21.XXX.XXX
> Apr 5 11:57:29 dj-dhcp01 dhcpd: DHCPDISCOVER from xx:xx:xx:xx:xx:xx via eth0: network name: no free leases
> Apr 5 11:57:49 srv-dhcp dhcpd: DHCPINFORM from 10.21.XXX.XXX via eth0
> Apr 5 11:57:49 srv-dhcp dhcpd: DHCPACK to 10.21.XXX.XXX (xx:xx:xx:xx:xx:xx) via eth0
> Apr 5 11:57:18 dj-dhcp01 dhcpd: DHCPREQUEST for 10.21.XXX.XXX from xx:xx:xx:xx:xx:xx via eth0
> Apr 5 11:57:25 srv-dhcp dhcpd: DHCPOFFER on 10.21.XXX.XXX to xx:xx:xx:xx:xx:xx (android-foobar) via 10.21.XXX.XXX

This is my extractor :
`%{DHCPD_MSG:Action}\s(to|from|on|for)\s(%{IPV4}|%{COMMONMAC:MAC_Address1})\s(to|from)?\s?(%{COMMONMAC:MAC_Address2}\s\(%{HOSTNAME:Hostname1}\)|\(?%{COMMONMAC:MAC_Address3}\)?|\(%{HOSTNAME:Hostname2}\))?\s?%{GREEDYDATA:Data}?`

I'm using lot of "or" condition for treat all cases.
With hostname or MAC address, I should add number in field name.
Without this, I do not have all the fields based cases but with this I do not have harmony in the field names.

Thank you
### Environment

```
Graylog Version: 1.3.4
Operating System: CentOS 6
```

**Comment by incubusbatanga** [comment]
It gets worse with existing pattern libraries, as one would have to edit tons of patterns to change field names to be unique. For example, Nagios patterns (https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/nagios). Once you import the file, the idea is to use single %{NAGIOSLOGLINE} as an aggregate pattern that covers all Nagios log line formats and have a single extractor for all Nagios logs. That currently doesn't work in Graylog because NAGIOSLOGLINE pattern consists of different Nagios log line patterns ORed together. Many of those patterns extract data into fields with the same name. For example, NAGIOS_HOST_FLAPPING_ALERT pattern shares fields 'nagios_type' , 'nagios_state', 'nagios_hostname', 'nagios_message' with NAGIOS_HOST_ALERT and many others. Natural thing to expect here would be to get fields from the first matching pattern, but instead, when a field name occurs more than once in a pattern, it doesn't get extracted anyhow. So, in order to use this ready-made pattern library (and, surely, many others), one would have to create a Grok extractor for each log line format, which can be tremendously tedious job.

**Comment by bernd** [comment]
You can solve this by using the pipelines and pipeline rules. They allow you to use several grok patterns.
