### ISSUE TITLE
I Think Graylog Support ES-SQL Is a way to make the analyze much easy

### ISSUE THREAD

**Issue by kira8565** [Graylog2/graylog2-server#2041]
### Problem description

some times es search is not easy to analyze data,i think ,if we can support sql to search and  analyze data,it can be much easy to complete the analyze work,how about this idea ヾ(o◕∀◕)ﾉ 
### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@kira8565 Thanks for your input!

[SQL](https://es.wikipedia.org/wiki/SQL) is usually used in the context of [relational databases](https://en.wikipedia.org/wiki/Relational_database). Even if we did support some dialect of SQL in Graylog, it wouldn't be possible for example to do JOINs or most aggregations that relational database systems support because the underlying storage simply doesn't support those.

**Comment by kira8565** [comment]
I found a plug-in called ElasticSearch-SQL,https://github.com/NLPchina/elasticsearch-sql     it supports some SQL syntax, it can also support join operations and  some aggregate functions, but its join operation only supports two table, I'm trying to reform it (•̀ᴗ•́)و ̑̑

**Comment by w3h** [comment]
Can SPL be supported, such as Splunk.
