### ISSUE TITLE
Timezone setting in MS Teams Notification V2 seems to be ignored

### ISSUE THREAD

**Issue by zippi-ifn** [Graylog2/graylog2-server#20541]
## Steps To Reproduce

1. Use new `MS Teams Notification V2`

## Environment

- Graylog Version: Graylog 6.0.6+4aa664f
- OpenSearch Version: opensearch/stable,now 2.17.0 amd64
- MongoDB Version: mongodb-org-server/jammy,now 6.0.17 amd64
- Browser Version: --

_Seems like this was fixed for the old plugin: https://github.com/Graylog2/graylog-plugin-integrations/issues/1318_
(and I accidentally opened the issue [there](https://github.com/Graylog2/graylog-plugin-integrations/issues/1355))

When notifications are sent to MS Teams with the V2 plugin, the timestamp is always UTC, regardless of which timezone was selected in the drop-down list.

![image](https://github.com/user-attachments/assets/d04c1d2f-b30d-4d7c-b78f-15f12cbcb7fa)

_ATM Berlin is at GMT+2_
![image](https://github.com/user-attachments/assets/9f179e1e-7787-4346-b64b-4b5be413286a)

**Comment by kingzacko1** [comment]
@zippi-ifn I'm able to reproduce the bug, but I think it may be on the Teams side of things... When I send a test notification with my UTC-5 timezone set on the notification I can see all the way in Teams Workflows that my UTC-5 was formatted properly. Here is an example from the Workflow Run History of my most recent test. 
![image](https://github.com/user-attachments/assets/3af7eb78-dbb5-4e72-ad2b-a082ca0c68ad)
However, the card that was posted in my channel has been reformatted:
![image](https://github.com/user-attachments/assets/fbf58b24-8014-43e2-aa85-3b278cc11d85)
Check your Workflow history to find the raw message that was received by Teams and see if it is sent with the proper UTC+2 formatting. I think you will, meaning this is indeed a Teams issue.

And it seems to be a known issue, or rather something Microsoft says happens 'by design'. See [this question](https://learn.microsoft.com/en-us/answers/questions/1185730/why-does-ms-teams-date-and-time-functions-on-adapt) on Microsoft's Q&A website. The one answer has two comments, the second one by Sandor Zeestraten seems to describe this exact scenario with no response as to why.
