### ISSUE TITLE
Extract UNIX/epoch time as timestamp field

### ISSUE THREAD

**Issue by twgraham** [Graylog2/graylog2-server#2077]
### Problem description

Currently my logging schema uses a UNIX/epoch format for the timestamp field. When I pull my logs into graylog from kafka, I use a JSON extractor, however when it tries to extract the timestamp field, the system logs fill up with errors saying it's a bad format. Presumably this is because graylog only takes SimpleDateFormat for timestamps?

e.g.

```
[117]: index [graylog_0], type [message], id [85f998a2-0208-11e6-9660-0242ac110004], message [MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "1460614630000" is malformed at "0000"];]
```

Is it possible to make graylog accept this format of time please? (It's important that I can store it in epoch i.e. I don't want to have to convert it to another format).
### Environment
- Graylog Version: 2.0.0-beta.2
- Elasticsearch Version: 2.3.0
- MongoDB Version: 3.0.7
- Operating System: Ubuntu 14.04
- Browser version: Chrome 48.0.2564.116

**Comment by twgraham** [comment]
From my limited understanding, maybe the date format graylog 1 used was necessary due to the constraint elasticsearch 1.x had for mapping date fields:
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-date-format.html

However now that graylog 2 uses elasticsearch 2.x, maybe this could change since it now maps many more kinds of date formats (including UNIX):
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

**Comment by joschi** [comment]
@twgraham The format of the `timestamp` field is fixed in Graylog (see https://github.com/Graylog2/graylog2-server/blob/2.0.0-beta.3/graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java#L82 and https://github.com/Graylog2/graylog2-server/blob/2.0.0-beta.3/graylog2-server/src/main/java/org/graylog2/plugin/Tools.java#L60) for various reasons. It's currently not possible to override that format or use multiple (possibly conflicting) date formats. Anything you want to write into the `timestamp` field would have to be converted before indexing the log message, e. g. by using extractors and converters (http://docs.graylog.org/en/2.0/pages/extractors.html#normalization).

**Comment by eli-jordan** [comment]
What format would this field need to be, so that it is successfully processed and indexed?

**Comment by eli-jordan** [comment]
I tried yyyy-MM-dd HH:mm:ss.SSS with no success

**Comment by Diffusive** [comment]
eli-jordan not sure if you ever figured this out but that is the format that is required but you have to match that _exactly_ otherwise it appears not to work. I was wrongly assuming that [the code here](https://github.com/Graylog2/graylog2-server/blob/1.3.3/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/Tools.java#L65) allowed for timestamps without ms but that isn't the case.

I tried a few options without any success, mostly because my source did not have ms accuracy:
Unix epoch
yyyy-MM-dd HH:mm:ss (no ms)
yyyy-MM-ddTHH:mm:ssZ (as it appears in the UI)
and finally just wound up appending a .000 to the end of yyyy-MM-dd HH:mm:ss and that worked!

Hope this saves someone else from a couple hours down the rabbit hole.

**Comment by eli-jordan** [comment]
Yeah I figured it out., we weren't actually using the format I mentioned above.. Once  we did it worked.

**Comment by vsegdacocacola** [comment]
@eli-jordan, what you actually did to make unix timestamp parsed correctly by graylog?

**Comment by bernd** [comment]
@vsegdacocacola Checkout the date converters to parse a unix epoch. See http://docs.graylog.org/en/2.2/pages/extractors.html#normalization
