### ISSUE TITLE
Failure on JSON reading

### ISSUE THREAD

**Issue by theonlydoo** [Graylog2/graylog2-server#2080]
### Environment
```
Debian:Jessie
```
```
dpkg -l|egrep -i 'elas|mongo|gray'
ii  elasticsearch                        2.3.1                        all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  graylog-2.0-repository               1-1                          all          Package to install Graylog 2.0 GPG key and repository
ii  graylog-server                       2.0.0-4.beta.3               all          Graylog server
ii  mongodb-clients                      1:2.4.10-5                   amd64        object/document-oriented database (client apps)
ii  mongodb-server                       1:2.4.10-5                   amd64        object/document-oriented database (server package)
```
```
Firefox Latest
```

### Steps to reproduce the problem
Input message:
```
{"@timestamp":"2016-04-14T13:53:48.608+00:00","@version":1,"message":"Execution time 75th : 4.0","logger_name":"com.foo.bar.core.Throttler","thread_name":"thread-0","level":"TRACE","level_value":5000,"HOSTNAME":"ac254ee227e9"}
```
Extractor : `JSON`, Key,Value separator `":"` and `tail -fn0 /var/log/graylog-server/server.log` returns :

```
[456]: index [graylog_33], type [message], id [ae5f2d04-0249-11e6-a176-0242ca38929c], message [MapperParsingException[failed to parse [level]]; nested: NumberFormatException[For input string: "DEBUG"];]
```
JSON is linted, but parsing raises an exception.

**Comment by joschi** [comment]
@theonlydoo That's a problem with Elasticsearch's dynamic index mapping. It looks like the `level` field has contained only numbers until now, which is why Elasticsearch assumed it should be a number in the future.

If you want to use other data types for the `level` field (e. g. strings), you'll have to create a custom index mapping (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping.html) and put that into an index template (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-templates.html) so that it will be applied to newly created indices.

If you have questions about that, please post to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
