### ISSUE TITLE
Drools and pipelines works unexpectedly together

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2118]
### Problem description

I need to make some pre=processing of raw log messages.with Drools (attached throught rules_file option in server.conf).
Also I want to make some field extractions using pipelines.
But pipline rules do not see changes, made by Drools rules.
Furthermore, changes made with pipeline rules even did not saved to message, processed with Drools.
### Environment
- Graylog Version:2.0 beta3
- Elasticsearch Version:2.3.1

**Comment by kroepke** [comment]
This might be because of the order they run in.

You can see and change the order of the message processors on the System/Configuration page, by default the Message filter chain runs before the Pipeline processors.

I tried to recreate this and it works with current master (no relevant changes since beta3).

My setup is:
Message Filter chain runs before Pipeline Processors

`graylog.drl`:
```
rule "drools"
   when 
      m : Message()
   then 
      m.addField("from_drools", "drools");
end
```

Pipeline "something" contains a single stage 0, which uses the rule `add_field`:
```
rule "add field"
   when has_field("from_drools")
then
   set_field("from_pipeline", $message.from_drools);
end
```

The pipeline is connected to the "Incoming messages stream" because I'm not using any specific streams in this case.

There are three processors (threads) running, and every message contains both `from_drools` and `from_pipeline`.

Could you share the rule sources, pipeline and pipeline connections as well as the rule code, please?

Thanks!

**Comment by hc4** [comment]
Didn't know about Configuration page.

Checked and found, that I hade non default order
```
 #	Processor	Status
 1	GeoIP Resolver	active
 2	Pipeline Processor	active
 3	Message Filter Chain	active
```

Changed order to this:
```
#	Processor	Status
1	Message Filter Chain	active
2	Pipeline Processor	active
3	GeoIP Resolver	active
```

But still not works.
I've updated from 1.3.4 to 2.0 beta1 and then beta2 and beta3. Maybe there is some migration issues?

Drools file.[drools.txt](https://github.com/Graylog2/graylog2-server/files/229721/drools.txt)

Pipeline connected to Beats Input and consist of single rule with priority 0.
```
rule "Surfer Request Start Parsing"
when
    has_field("text")
then
    set_field("processed", 0);
end``

**Comment by kroepke** [comment]
Is that drools file complete? Line 11 looks truncated when downloaded.

I was wrong about the default order, yes, the pipeline processors runs first due to a different package name, but it should not influence the drools evaluation at all.

What do you mean by "Pipeline connected to Beats Input"?

**Comment by hc4** [comment]
just mistaken on copy from MC.
Correct fil:[drools.txt](https://github.com/Graylog2/graylog2-server/files/229793/drools.txt)

**Comment by kroepke** [comment]
Ok, I see.

Where did you connect the pipeline to? A stream? All incoming messages? Are the messages being routed in a stream at all?

**Comment by hc4** [comment]
Hm.. I've connected it to Input Stream.
After connecting to normal Stream everything works fine!

**Comment by hc4** [comment]
Also if I set Message Filter Chain after Pipeline Processor it won't work anymore

**Comment by kroepke** [comment]
I'm confused and feel I'm missing information.

What exactly happens to the messages?
The come in via a BeatsInput.
Then there's a drools rule manipulating them.
I am missing: Is there a stream rule involved? Which stream are the messages in?
Then the pipeline is running, to which stream is it connected?

"All incoming messages" match messages that _do not yet_ are on a stream.

**Comment by hc4** [comment]
Firstly I've attached pipeline to Incoming messages stream and it won't work.
Then I've attached same pipeline to Stream, that catches all messages and it started to work.

But only if Pipeline Processor stays after Message Filter Chain

**Comment by kroepke** [comment]
Ok, then I guess this is basically a documentation issue.

Processing works like this:

There are two different types of code that process messages. The older `MessageFilter` implementations, which are static fields, extractors, stream rules, and Drools.
Then starting with 2.0 there are the `MessageProcessor` implementations which are more powerful than the filters. The old filters run in the `MessageFilterChainProcessor`, the pipeline plugin runs in the `PipelineProcessor`.

The ordering in "System/Configurations" determines which of the processors(!) run first. The order of the filter is fixed and cannot be changed, except by changing the code.

Pipeline processing works as follows:
Messages which are not in any stream when the pipeline processing starts are considered to be on the "default" stream, which is labeled "Incoming messages stream" in the UI, because this stream is a logical construct, it does not explicitly exist in Graylog.
It does *not* contain messages which are already on one or more streams (and this is probably the point of confusion), instead those messages are only in the relevant streams, and will only be processed by pipelines which are attached to that stream.

If the filter chain does stream routing, the pipeline processing is essentially per-stream processing.
If the filter chain doesn't do stream routing (or doesn't route all the messages), the "Incoming messages stream" can be used to do stream routing in pipeline rules, which is much more flexible, but not as fast yet, as the stream router engine: the stream router is heavily optimized already, the processing pipeline is very new.

So in your use case you most likely either want to move your Drools logic into Graylog's rule system, or make sure the Drools messages are routed into a stream, attach a pipeline to that stream and do further processing on that.

Does that make sense? If so, I'll add it to the documentation.

**Comment by hc4** [comment]
Yep. Attaching pipeline to strem works fine.
Actualy I will prefer using of pipelines instead of Drools, but pipeline rules can't do some types of processing.
For example
1. I can't concatenate strings (i need it to construct timestamp from file date and time from message)
2. I can't do math on numbers (i need to calculate total CPU usage)
3. I can't filter out all fields except ones, which I need

**Comment by kroepke** [comment]
@hc4 I'll make feature requests for those, as we are looking for exactly this kind of feedback to improve that feature.

Thanks!

**Comment by hc4** [comment]
While writing rules I've found, that there is no **if**, **else** and **return** operators;
But I'm not sure if it's correct to use such operations in rule action.

Or it will be even better to be able to access matching result from **when** clause in **then** clause.
Something like this:
```
rule "Regex Rule"
when
    let m = regex(".*([0-9]+).*", to_String($message.text)) && m.matches
then    
    set_field("some_number", to_long(m["0"]));
end
```

**Comment by kroepke** [comment]
That was an early design decision, yes.

We found that adding **if** would make automatic optimizing and reusing rules very difficult and the `when` section basically is an **if**.
This is why stages allow `AND` and `OR` matching to gate further execution.

Later versions of the rule interpreter will memoize calculated values, making re-evaluation of regexes etc basically free, that's why we didn't allow **let** statements in **when** clauses. Although the syntax you describe has a certain elegance to it, as well. `let` would then need to be enclosed in `(` and `)`, though, because **when** clauses need to evaluate to a boolean.

Specifically we wanted to avoid a scenario where users would simply stuff all logic inside a single big rule, as one can sometimes find in load balancer configurations for example. Those are getting out of hand very easily.

I greatly appreciate the feedback!

**Comment by hc4** [comment]
Yep. Actual i need **if** only beause I'm aware of reevaluations.
Maybe it will be good to create dedicated evaluators which could be reused in rules (like it done for GROK patterns)

**Comment by kroepke** [comment]
Could you give an example for when you need an `if` function?

I'm trying to see if (haha) we can come up with a way that avoids putting it into the language itself.

**Comment by lennartkoopmann** [comment]
[pun police checking in]

**Comment by hc4** [comment]
As I said, i've realized theat I need IF only for optimization purposes (to not reevaluate regex twice).
If I'll find some other scenarios - I will create issue :)

**Comment by kroepke** [comment]
Ah! Misread that 😄

**Comment by dennisoelkers** [comment]
Closing this issue, as Drools was removed a while ago.
