### ISSUE TITLE
Live Tail feature is not new index aware for same session

### ISSUE THREAD

**Issue by luckyb56** [Graylog2/graylog2-server#2220]
### Problem description

The live update won't consider new index created for the same login session. 

### Steps to reproduce the problem
Create hourly/day indices, when data is indexed to new index, live update will continue to tail the index it was already querying. By logging out and logging in back, the search UI updates the new index.

### Environment

* Graylog Version: 2.0 GA
* Elasticsearch Version: 2.3
* MongoDB Version:
* Operating System: Ubuntu
* Browser version: Chrome 49.0.2623

**Comment by kroepke** [comment]
The live tail feature simply runs the same search repeatedly, so it is extremely unlikely that this should break when the index rolls over (since the normal search does nothing different).

We've been unable to reproduce this, please reopen the issue if you have additional information as to what might cause this.

Thanks!
