### ISSUE TITLE
Buffer size warning for Netty inputs

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2272]
### Problem description
Got this line in logs for all my Netty TCP inputs (Syslog and Beats)
`[NettyTransport] receiveBufferSize (SO_RCVBUF) for input ... should be 1048576 but is 212992.`

What does it mean? Should I set buffer size in input settings to 212992 (default is 1048576)?

### Environment
* Graylog Version: 2.0.1

**Comment by joschi** [comment]
@hc4 That's because your operating system doesn't allow the Java process to increase the socket receive buffer to be increased to 1 MB (1048576 bytes).

You can either reduce the receive buffer size in your input configuration or increase the limit on the operating system level.

See Graylog2/documentation#26 for an explanation.

**Comment by hc4** [comment]
Maybe there is should be better message?
For example:
`requested receiveBufferSize is 1048576, but system allowed only 212992.`

Or maybe even better - make this check in UI, when applying Input configuration.
