### ISSUE TITLE
Flaky test: KafkaJournalTest.serverStatusThrottledIfJournalUtilizationIsHigherThanThreshold

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#2364]
```
Results :

Failed tests: 
  KafkaJournalTest.serverStatusThrottledIfJournalUtilizationIsHigherThanThreshold:395 expected:<[Throttled?[LB:THROTTLED]]> but was:<[Running?[LB:ALIVE]]>
```
https://jenkins.torch.sh/job/graylog2-server/765/console

**Comment by kroepke** [comment]
The test relies on the server's event bus (implicitly because the server status is being published).
Looks like a simple race condition, we'll need to figure out how to synchronize it better.

**Comment by kroepke** [comment]
Ah no, actually the result should also be available without async processing.
Nevertheless it looks like a timing problem, because the `KafkaJournal` retention threads will run in parallel to the test.
The test itself has a very short retention period (1 second) which might elapsed in case the CI box is slow, verified this by adding a second of sleep to the test.
