### ISSUE TITLE
Graylog 2.0.3 adds additional information to Collector-Sidecar nxlog.conf

### ISSUE THREAD

**Issue by roxer2725** [Graylog2/graylog2-server#2410]
### Problem description
Graylog 2.0.3-1 (graylog-server-2.0.3-1.noarch.rpm) adds additional information to Collector-Sidecar nxlog.conf file above what the nxlog snippet provides when creating the nxlog.conf file

### Steps to reproduce the problem

1. Create collector for Windows OR Linux and enter snippet for nxlog. Start collector-sidecar service: Graylog adds additional lines at the top of the nxlog.conf file.

For Windows:

define ROOT C:\Program Files (x86)\nxlog

<Extension gelf> 
	Module	xm_gelf 
</Extension> 

For Linux:

define ROOT /usr/bin

<Extension gelf>
  Module xm_gelf
</Extension>

### Environment
Three Centos 7 graylog hosts sitting behind HAProxy server.

* Graylog Version: Graylog 2.0.3 (f07c170)
* Elasticsearch Version: 2.3.3-1
* MongoDB Version: 3.2.7-1.el7
* Operating System: Centos 7.0 (3.10.0-327.18.2.el7.x86_6)
* Browser version: IE 11/Firefox

**Comment by mariussturm** [comment]
Hi,
this is intended. The Gelf module is needed in any case when you use NXlog in combination with Graylog. The ROOT path is just a definition and it's composed from your settings in `collector_sidecar.yml`.

Just make sure that you dont paste the same lines into your NXLog snippets, so that you don't end up with a duplicated configuration.
