### ISSUE TITLE
Search reloads whole interface

### ISSUE THREAD

**Issue by sandrinr** [Graylog2/graylog2-server#2424]
### Problem description

Every time I do a search the whole interface is reloaded, i.e. the browser navigates again to the search page.  This results in an unpleasant search behaviour because you need to wait for the page being loaded before the search even begins. I did a quick check in the front end code and it seems this is "intentional behaviour" according to the code, i.e. there is a real form submit going on.

If you think this is working as designed then please close this ticket.

### Steps to reproduce the problem

1. Open a Graylog2 instance and navigate to the search functionality
2. Enter anything into the search field and press enter

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.3.8
* Operating System: Ubuntu 16.04
* Browser version: Chrome 51.0.2704.103 on OSX 10.11

**Comment by dennisoelkers** [comment]
Thanks for reporting this!

Yes, this is intended behavior, because during the transition from the old web interface to the single page app we have now, some logic relied on the full page reload. That should not be the case in `master` anymore, so we want to get rid of the full page reload. This won't happen for 2.0.x though, so it will probably end up in 2.1.

**Comment by sandrinr** [comment]
@dennisoelkers thank you very much for your prompt response and the provided information. Much appreciated.
