### ISSUE TITLE
Bad redirect if rest and web hosted on same addr

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2593]
### Problem description
I have `rest_listen_uri = http://0.0.0.0:80/` and `web_listen_uri = http://0.0.0.0:80/web`
If user opens http://graylog, he will be redirected to `http://0.0.0.0:80/web`

### Environment
* Graylog Version: 2.1.0-beta2

**Comment by shishkin** [comment]
`web_transport_uri` property seem gone and has no effect.

**Comment by joschi** [comment]
@shishkin There never was such a configuration setting.

**Comment by shishkin** [comment]
I see, there was no redirect from REST to UI as well. Now when REST redirects to UI it doesn't know what the external URI should be. Maybe it would be more straightforward to have a common setting for external host (`http_external_host`?) instead of `rest_transport_uri` that would influence both REST and UI.

**Comment by hc4** [comment]
@joschi @shishkin  there is web_endpoint_uri option.
And if I set it to empty string - everything works fine.

**Comment by shishkin** [comment]
@hc4 `web_endpoint_uri` (set as `GRAYLOG_WEB_ENDPOINT_URI` docker env var) doesn't make a difference, `curl -i -H'Accept: text/html' http://localhost:12900` still redirects to `http://0.0.0.0:12900/web`, which is the value of `GRAYLOG_WEB_LISTEN_URI`. Same happens if I set `GRAYLOG_WEB_ENDPOINT_URI` to http://127.0.0.1:12900/web

**Comment by shishkin** [comment]
Although the redirect is broken, the UI works fine with @hc4 's suggestion when opening http://localhost:12900/web/ (trailing `/` is important, without it will redirect to the listen IP).
