### ISSUE TITLE
Search Button on dashboard widgets

### ISSUE THREAD

**Issue by mholttech** [Graylog2/graylog2-server#2728]
## Expected Behavior

In widgets with Values having a search button take you to the search page with the query to look at all logs related to it would be very useful.
## Current Behavior

Have to click the "play" button at the bottom of the widget and then build the filter from there to see what I want.
## Possible Solution

Implement a filter/search button to the widgets identical to what you see when you view a widget from the search page.
- Graylog Version: 2.1.0-beta.2+ffa3355

**Comment by elisiariocouto** [comment]
+1
Also, I would LOVE to have the datepicker and templating in dashboards like Grafana does!

**Comment by dannyz29** [comment]
+1
Datepicker is a critical feature that exists in KIbana and missing in Graylog. This is the main feature that makes me no want to use Graylog dashboarding. Would be greatly appreciated!

**Comment by alias454** [comment]
+1
It would be nice if the values were hyptertext links that take you directly to the proper search results.

Regards,
Brandon

**Comment by dennisoelkers** [comment]
Fixed in e0617de08684e4a2fb2d71f8e752034b20d02262 - you can click on a value and trigger the "Show documents for value" action, which generates a list of messages that contributed to this value's bucket.

@elisiariocouto, @dannyz29: Dashboards do have a time range selector since `3.2.0`. Maybe you want to reevaluate Graylog again?
