### ISSUE TITLE
EC2 autodiscovery is not supported with graylog2-server

### ISSUE THREAD

**Issue by chad-upton** [Graylog2/graylog2-server#2789]
cloud-aws ec2 discovery plugin isn't supported or able to be installed.

## Expected Behavior

include the ec2 discovery plugin within the embedded version

## Current Behavior

Elasticsearch Configuration:
`        'cloud.aws'                     =>  {
          'region'                      =>  'us-east-1'
        },
        'discovery'                     =>  {
          'type'                        =>  'ec2',
          'ec2.tag.Cluster'             =>  $clustername
        },`

Error: 
`Error in custom provider, java.lang.IllegalArgumentException: Unknown Discovery type [ec2]`

## Steps to Reproduce (for bugs)

1. Add the above section to your elasticsearch.yml file and install the cloud-aws plugin
2. Point graylog config to use the elasticsearch.yml file
3. Get error.
4.

## Context

Can't use EC2 autoscaling with elasticsearch due to having to manually add the nodes to the configuration files.  

Cloud-aws plugin should be included in the embedded ES version or installable through some method.

## Your Environment

Amazon AWS EC2 - Amazon Linux

* Graylog Version: 2.3.1
* Elasticsearch Version: 2.4.0
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@chad-upton This is a known limitation and won't change in the short term: http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html

**Comment by ignitediris** [comment]
Just a quick comment for anyone else who stumbles upon this.

You can work around this problem by installing elasticsearch in client mode on the same server that hosts graylog. Then, configure graylog like so:
elasticsearch_discovery_zen_ping_unicast_hosts: 'localhost:9300'
elasticsearch_config_file: '/etc/graylog/server/elasticsearch.yml'

In that elasticsearch config file add the following:
discovery.zen.master_election.filter_client: false

It would also be wise to add a different node.name in that file too so that both elasticsearch clients on the graylog server are uniquely identifiable.

With this setup, the installed elasticsearch client dynamically discovers the AWS cluster via cloud-aws and graylog's built in elasticsearch client queries localhost. The only downside to this is the elasticsearch clients which are largely useless after cluster formation. I lock them to 256MB ram and let them be.

I am testing this in AWS as I type this so if anyone knows of any downsides to doing this, I would appreciate knowing about them. So far, everything seams to function as expected. A newly provisioned deployment self assembled without intervention as desired/expected.
