### ISSUE TITLE
Search result loading indicator hard to see

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2843]
First of all: I LOVE the new way of reloading the search result page elements instead of a full browser reload. <3

One problem I noticed: When the search is returning the same search result very fast, it looks like no search ever happened and the user can be confused. I personally thought something was wrong when the page (seemingly) did not update.

A loading indicator would probably not solve this because the search returns so fast. Maybe some other highlighting that indicates that something happened? Happy to brainstorm here.

**Comment by coffee-squirrel** [comment]
Maybe an extra line near the top of the "Search result" section.  `Retrieved 2016-09-19 14:51:12.345`

**Comment by jhaar** [comment]
I agree, a quick search now shows zero evidence of having worked. Similarly, I am now finding myself routinely confused with long searches. I'll do a search, then re-run it and sit there wondering if I failed to click the button, because there's no evidence at all that anything is happening. If I wait long enough suddenly the results are there - but there's simply not enough visual feedback that anything is happening. The little "popup" at the bottom right is useful, but something more fundamental like a line stating when the last search was run would be a good trick - it would always change each time it was run. Another idea: how about an "hourglass" on the mouse, or some kind of real-time timer showing how long the search has been running?

**Comment by lennartkoopmann** [comment]
@kroepke Can we prioritize this into the next patch release? It is clearly a very confusing bug. Thanks!

**Comment by kroepke** [comment]
Yep, I agree it's not visible enough now.

**Comment by lennartkoopmann** [comment]
Thank you!
