### ISSUE TITLE
Search redirect/link unavailable after assigning user to global search role

### ISSUE THREAD

**Issue by jamiebuxxx** [Graylog2/graylog2-server#2856]
After creating a user role to allow non-admins to search within Graylog, some users have reported an issue of being redirected to the Streams page after logging in. And from this user screenshot, there is not link to the Search page on the web UI. 

https://drive.google.com/open?id=0B_sSEdtI9750YUdNZVFuUkgzSkk

However, the users can access the Search page by entering the URL slug(graylog.host.com/search). Some users have expressed limited productive due to this issue. Here is a copy of the user role JSON string we are using:

```
{
  "name": "Standard",
  "description": "Standard permissions for every Graylog user",
  "permissions": [
    "searches:*",
    "streams:*",
    "dashboards:*",
    "messages:*"
  ],
  "read_only": false
}
```

Also, not sure if this is related, but all of these users are also inheriting the Reader role by default as well. 
- Graylog Version: 2.1.0+62db7e0
- Elasticsearch Version: 2.2.0
- MongoDB Version: 2.4.9
- Operating System: Ubuntu 14.04.4

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this issue!

Trying to use that role myself, I can confirm the search menu does not appear in the navigation bar. The problem seems to be in the way we verify wildcard permissions in the web interface, so as a workaround you can use the permissions as stated in [`RestPermissions.java`](https://github.com/Graylog2/graylog2-server/blob/2.1/graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java).

**Comment by jamiebuxxx** [comment]
Thanks for the work around @edmundoa. I modified our role json to include each permission and the WebUI is working properly and users are happy! 👍 Glad I was able to bring this to your attention. Keep up the awesome work!

**Comment by kroepke** [comment]
This will be solved as soon as we have an explicit default stream.

**Comment by joschi** [comment]
Verified.

This issue was solved by introducing the Default Stream which can be read by appropriate roles.
