### ISSUE TITLE
Parsing exception without extractors

### ISSUE THREAD

**Issue by keitarobr** [Graylog2/graylog2-server#3084]
## Expected Behavior
Message should be indexed accordingly.

## Current Behavior
Tons of these error messages are logged:
[373]: index [graylog_38], type [message], id [2efe52c0-a78f-11e6-bc97-ce1442b73e45], message [MapperParsingException[failed to parse [application_name]]; nested: IllegalArgumentException[Invalid format: "postfix/smtpd"];]

No extractors are configured on the source.

## Context
Receiving several syslog from various devices and systems

## Your Environment
* Graylog Version: 2.0
* Elasticsearch Version: 2.4.1
* MongoDB Version: 2.6
* Operating System: Ubuntu Xenial (16.04)
* Browser version: Chrome

**Comment by joschi** [comment]
@keitarobr The problem is that the `application_name` message field wasn't a string before (or at least Elasticsearch didn't think it was a string).

You can create a custom index mapping to prevent these issues in the future: http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html#custom-index-mappings
