### ISSUE TITLE
GUI: Sources tab switches to search tab

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#3100]
Sources tab switches to search tab, when I select a time range in the upper left corner and then click on the search button.

## Expected Behavior
Stay on sources tab.

## Current Behavior
Leaves the the sources tab.

## Possible Solution
fix bug.

## Steps to Reproduce (for bugs)
1. Logon in GUI
2. click on sources tab
3. select a time range on upper left box. e.g. 1 hour
4. click on search button
5. GUI switches to search tab.

## Context
View throughput per source over a certain time range.

## Your Environment
Versions:
- Graylog 2.1.2 
- elasticsearch 2.3.5
- mongoDB 3.2.1
- Linux SLES 11
- Browser Firefox ESR 45.2.0

**Comment by edmundoa** [comment]
Hi,

Thank you for your report, but what you described is not a bug, it's the expected behaviour.

The search bar is on that page to help you search for messages from one or many of the sources you see in there.

You can expand the time of displayed sources in the dropdown on your right, inside the "sources" section. You can also filter sources by interacting with the graphs in the page.
