### ISSUE TITLE
PostProcessing not included in decoding timer

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3148]
The current `DecodingProcessor` implementation does record timer metrics for the decoding part, but not for the code called in `processMessage()`.

The following line is called in that untimed block:

    message.addField("gl2_remote_hostname", remoteAddress.getHostName());

This means that, if a RDNS lookup is slow, we have no way to see this in the `DecodingProcessor` timers or even any other timings.

**Comment by kroepke** [comment]
I'm not sure if you have seen that there are two distinct timers:
* `ProcessBuffer#decodeTime`
* `ProcessBuffer#parseTime`

`decodeTime` includes `parseTime` and all other processing done, including `getHostName`.
I don't think we should add timers specific to the `getHostName` call, unless we generally time rDNS/DNS lookups somewhere generically (because otherwise we'll miss other places that might do the same call accidentally).

**Comment by lennartkoopmann** [comment]
Agreed! I thought it was not included and read the Timers wrong. Thanks!
