### ISSUE TITLE
search keyword problem

### ISSUE THREAD

**Issue by christianmos** [Graylog2/graylog2-server#3437]
search keyword problem

## Expected Behavior
I will search all messages from today (00:00 to now) and try to use the keyword today midnicht to now.
I expected a preview like 2017-01-27 01:00:00 to 2017-01-27 09:26:32

## Current Behavior
When I delete the "w" from now, than switch the preview to 2017-01-27 01:00:00 to 2017-01-27 09:26:32.

## Possible Solution
I let the search keyword to "no"

## Steps to Reproduce (for bugs)
1. type in time search as keyword "today midnight to no"
2.
3.
4.

## Context
The problem happen every time.

## Your Environment

* Graylog Version: 2.1.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System: CentOS 7
* Browser version: Chrome 55.02883.87 (Win 64bit)

**Comment by joschi** [comment]
@christianmos I'm unable to reproduce that. The phrase "midnight to now" (or simply "midnight") works as expected:
<img width="683" alt="midnight to now" src="https://cloud.githubusercontent.com/assets/43951/22365464/e7342f7a-e477-11e6-9363-5c544dd3f0bd.png">

Please elaborate on which keywords you've been using, what you expected as a time range, and which time range actually was being used.

**Comment by Comradin** [comment]
Hi @joschi,

I can reproduce the error. The terms "today midnight" or "midnight" work as expected. I guess its because you specify the start of a time range and graylog detects the missing end and uses time.now() for the end.

The time range is _correct_ as long as the graylog-server does not recognize a keyword:
today midnight <-- works from here
today midnight t
today midnight to
today midnight to n
today midnight to no
today midnight to now  <-- failes to parse correct date

![graylog_timeselector](https://cloud.githubusercontent.com/assets/4760546/22367181/83965656-e480-11e6-88c1-c98010e400e0.png)

This is a slightly older release I probably should update: Graylog 2.1.0+62db7e0

**Comment by joschi** [comment]
@christianmos Okay, thanks!

There's not much we can do about it. We're using [Natty](http://natty.joestelmach.com/) for natural language parsing in the "keyword time range", so we're bound to what it supports.

You can play around with your keywords at http://natty.joestelmach.com/try.jsp, but I'd recommend using the working keywords (simply "midnight") in your Graylog search queries.
