### ISSUE TITLE
Key Value converter when Value is empty

### ISSUE THREAD

**Issue by zorel** [Graylog2/graylog2-server#3469]
Hello.

I'm using graylog to process & display ssh logs. When using key value converter with copy extractor, some fields are not generated properly when a value is empty.

## Expected Behavior
logname= uid=0 euid=0 tty=ssh ruser= rhost=172.18.0.7  user=root
would generate field:

- logname with value "" (or no field generation)
- uid with value 0
- euid with value 0
- tty with value ssh
- ruser with value "" (or no field generation)
- rhost with value 172.18.0.7
- user with value root

## Current Behavior
logname= uid=0 euid=0 tty=ssh ruser= rhost=172.18.0.7  user=root
generates field:

- logname with value "uid=0"
- euid with value 0
- tty with value ssh
- ruser with value rhost=127.18.0.7
- user with value root

## Possible Solution
In https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/converters/TokenizerConverter.java#L31 regarding the regex the behaviour is by design. Should it even be corrected? 

I'm looking into the regex to see if a solution is possible and can be submitted.

## Your Environment
Graylog-server docker image

* Graylog Version: 2.1.1+01d50e5, codename Smuttynose

**Comment by joschi** [comment]
@zorel This is a trade-off between being useful in 80% of all cases and being flexible but too complex to use.

The Tokenizer converter expects that there is a value corresponding to every key and doesn't support "empty" values (such as the one for the key `logname` in your example), but on the other hand it supports whitespace characters between the delimiter (so that `euid = 0` would be correctly split) and quotes around the keys and values (so that `logname=""` would be correctly split).

Sometimes, the Tokenizer converter is not the best fit for a problem like the one you've mentioned.

In your case, it should be easy to replace the Tokenizer converter with a Grok extractor which pulls out the relevant values (see https://gist.github.com/juanje/3081998#gistcomment-920908 for an example).

**Comment by gabawilmaa** [comment]
Dear @joschi 

Thanks a lot for your explanation!

I would kindly ask you to reconsider your decision. Empty values seem very common in all kinds of logs. Be it because of a bug or by intention.

In my opinion, this converter has almost no application for anybody as long at it does not handle empty values.

To make things worse, if a value is empty, the current version takes the next key/value-pair as it's value. So I often end up with values like this:
key1="key2=value2" (assuming key1 has an empty value)

Thanks for your great work and I would be happy to hear from you.

**Comment by clinta** [comment]
@gabawilmaa just wanted to let you know my workaround for this issue. First I created an extractor to quote all the values in the k=v field. It's a regex replacement extractor which replaces all instances of `([^\s]*)=([^\s]*)` with `$1="$2"`. This turns the `key1= key2=value2` into `key1="" key2="value2"`. Then I can do the key=value extractor on the new quoted field and it works as expected.
