### ISSUE TITLE
Index set must not be null! 

### ISSUE THREAD

**Issue by kkuyumjyan** [Graylog2/graylog2-server#3506]
I've installed fresh server from scratch with Graylog-Server 2.2, and migrated Elasticsearch and Mongo database from old graylog server 2.0 to new one, now I got this error in web   

Loading streams failed with status: Error: cannot GET https://mygraylogserver/api/streams (500)

and in graylog server log this one

java.lang.IllegalStateException: index set must not be null! (stream id=57ac34feee1c353261002ab1 title="Errors").

* Graylog Version: 2.2
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.6.12
* Operating System: Ubuntu 16:04
* Browser version: Google Chrome 56.0.2924.87

**Comment by jalogisch** [comment]
hej @kkuyumjyan upgrading vom 2.0 straight to 2.2 is something not supported.

because of some internal settings had changed you need to upgrade first to 2.1 and after that to 2.2.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
