### ISSUE TITLE
Support log4j output to Graylog server

### ISSUE THREAD

**Issue by dploeger** [Graylog2/graylog2-server#3704]
## Expected Behavior

Graylog2 uses log4j2 as its server logging framework. It would be great, if Graylog2 includes or supports log4j2-plugins like https://github.com/mp911de/logstash-gelf or https://github.com/graylog-labs/log4j2-gelf, so that one could additionally send the Graylog2-server messages to the server itself using GELF.

It makes no sense, that Graylog2's logs itself aren't directly available in the UI. 😉 
Using Beats as an alternative results in handling stacktraces in the logfile.

## Current Behavior

Currently, using plugins isn't possible using the default startup way. One could rewrite the startup command and using a classpath and the main class, but that's tedious.

## Possible Solution

* Include one of the two log4j-plugins in the graylog.jar
* Rewrite the startup command, so that a classpath can be specified

## Context

We'd like to see *all* logs in graylog, even the graylog logs itself.

## Your Environment

* Graylog Version: 2.2.3+7adc951
* Elasticsearch Version: 2.3.5
* MongoDB Version: 3.4.3
* Operating System: Ubuntu 16.04
* Browser version: 57.0.2987.133 on macOS 10.12.4

**Comment by joschi** [comment]
@dploeger 
> It makes no sense, that Graylog2's logs itself aren't directly available in the UI. 😉

It makes total sense to *not* (exclusively) store Graylog's own logs in its own storage. Just think about what will happen if there are problems with ingesting messages, e. g. because Elasticsearch is down, or other failures leading to a spike in log messages from Graylog.

Correct, it would make things worse and potentially turn a recoverable failure into a catastrophic failure.

This being said, it's already possible to use other log4j 2 appenders by simply adding them to the JVM class path.

You can also keep your eye on https://github.com/graylog-labs/graylog-plugin-internal-logs, although that's an unsupported project and it doesn't have a release yet.

**Comment by dploeger** [comment]
Thanks for the clarification. We might be on different sides there, but I can see your point.

The current startup script (at least in my ubuntu-install) uses java -jar, which only uses the libraries provided by the graylog.jar. I don't want to change (much) in that installation, because we set this all up using Puppet and try to stay with the default installation.

Thanks for the hint about graylog-plugin-internal-logs.
