### ISSUE TITLE
index rotation by size, but indexes are allocated with varying sizes

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3850]
## Expected Behavior
Having specified index rotation by size (50 GB/ 200 indexes/ delete), we expect every index will be rotated after approx. 50 GB. 

## Current Behavior
But index sizes are approx. 35 GB or 50 GB. We don't see any pattern for the index sizes. Also there aren't any related messsages in the logs.

## Steps to Reproduce (for bugs)
1. Index 50 GB
2. check index sizes

----
Versions:
- Graylog 2.2.3 
- elasticsearch 2.4.4
- mongoDB 3.2.1
- Linux SLES 11

**Comment by joschi** [comment]
@jalogisch Unfortunately that's not possible to fix.

The size of indices is calculated using the information Elasticsearch returns while writing to that very index. When the configured size is reached, Graylog will close that index, which does effectively two things: block writes to the index and execute a [force merge](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/indices-forcemerge.html).

The latter merges the segments of each [index shard](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/_basic_concepts.html#getting-started-shards-and-replicas), so that the overhead on disk is reduced. Additionally, "deleted" documents in the index will only be physically removed in this step and the segments will be recompressed, possibly yielding a better compression rate when lots of similar messages exist in the index.

This process causes the indices to "shrink" after they've been closed and that's the reason why the configured size is only the *maximum* index size, not the exact or minimum index size on disk this rotation strategy will result in.

Also see the following references for further information:
* https://www.elastic.co/guide/en/elasticsearch/guide/2.x/merge-process.html
* https://www.elastic.co/blog/store-compression-in-lucene-and-elasticsearch
* https://www.elastic.co/guide/en/elasticsearch/guide/2.x/indexing-performance.html#segments-and-merging

**Comment by joschi** [comment]
I'll label this issue as **known issue** and we could probably improve the documentation on the size-based rotation policy to make the tradeoffs and design decisions clear.
