### ISSUE TITLE
Field Content Alert Condition not working

### ISSUE THREAD

**Issue by paulvoosten** [Graylog2/graylog2-server#3881]
## Expected Behavior

An alert should be triggered when a message with value "yes" for field "alert".
## Current Behavior

Alert doesn't get triggered.
## Steps to Reproduce (for bugs)

1. Create a new alert condition for stream _All messages_ with condition _Field Content Alert Condition_
2. Set field to _alert_
3. Set value to _yes_
4. Send in a message containing field _alert_ with value _yes_

## Context

I was trying to see if the Field Content Alert Condition worked, but it didn't. I tried the other two conditions as well (Field Aggregation Alert Condition & Message Count Alert Condition) and they seem to work fine. If you need any more information please let me know.

Alert condition:
![alert testing](https://cloud.githubusercontent.com/assets/10833733/26623321/a20f196e-45ed-11e7-9fb1-39fa522db640.png)

Input: GELF TCP
![gelf tcp input](https://cloud.githubusercontent.com/assets/10833733/26623294/8ec62208-45ed-11e7-8b12-f6c74c968317.png)

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.5
* MongoDB Version: 2.6.12
* Operating System: CentOS 7.3.1611 (64-bit)
* Browser version: Chromium 58.0.3029.110 (64-bit)

**Comment by YoichSec** [comment]
Hi. Piggybacking on this a bit because I'm also seeing problems with field content alerting. It does work the majority of the time when set up correctly. The field must be valid ('alert' is not a field unless you created it yourself - there's also no checking whether your input is a valid field) and the condition checks for an exact match (there's no way to specify a 'Contains' search). Those are probably your issues if you're not getting any alerts at all.

I do think there's an issue with content alerts firing consistently. I'm getting occasional missed alerts when sending a number of the exact same events to graylog. This apparently isn't due to the alerting window set or the grace period because some of the missed alerts were for new messages far outside of either timeframe. All of the events are parsed the same and show up in the stream correctly. The alert just fails to trigger for one occasionally where it absolutely should. Unfortunately this means we can't rely on this particular alert feature at the moment.

**Comment by paulvoosten** [comment]
Hey @YoichSec, what version of Graylog are you on? I seem to recall that in version 2.2.2 the alert condition worked fine, however ever since 2.2.3 I just can't seem to trigger it anymore.
Could you also maybe give an example of a field content alert condition you are using?

To clarify my situation a little:
* The _alert_ field is an additional field
* When searching for the condition _alert: "yes"_ several messages that I've sent show up (see image), making me think that the condition should've been triggered
![alert not getting triggered - search results](https://cloud.githubusercontent.com/assets/10833733/26718456/624e1e52-4781-11e7-8722-988dbbd6b4ad.png)
Is there anything I'm missing/doing wrong?

**Comment by YoichSec** [comment]
I've tried it on 2.2.1 and 2.2.3. They both work most of the time for me with occasional misses. Looking at your screenshot, it seems like those should trigger the alert conditions you've specified. I would check to see that you aren't parsing an extra space character or similar into the custom field, but otherwise it looks fine and is similar to what I've tested. I'm parsing through the code and there's some debug logging on alerts that might help you diagnose the problem. I'm going to try that myself.

**Comment by YoichSec** [comment]
FYI this is what the debug output will look like:
2017-06-02 11:06:55,233 DEBUG: org.graylog2.periodical.AlertScannerThread - Stream [000000000000000000000001: "All messages"] ha                 s [1] configured alert conditions.
2017-06-02 11:06:55,237 DEBUG: org.graylog2.alerts.types.FieldContentValueAlertCondition - Alert check <058a8f79-0288-4d8d-a197-                 5114deab2494> found [1] messages.
2017-06-02 11:06:55,237 DEBUG: org.graylog2.alerts.AlertScanner - Alert condition [058a8f79-0288-4d8d-a197-5114deab2494:field_co                 ntent_value={field: name, value: Alert Test}, stream:={000000000000000000000001: "All messages"}] is triggered. Sending alerts.

I've diagnosed my intermittent mis-triggers as a timing issue due to normalization. Since it's an overall issue with the alert scanner and most likely not limited to field content alerts, I'm going to open a separate issue.

**Comment by SonofLiberty90** [comment]
The way that current Alert engine works is that every minute it checks all the events that came within $Now - 1m range and evaluates them for every alert condition you have on Graylog.

Check that your events come with the right time.

As per topic's question - I tested Field Content alerts on 2.2.3 and they worked fine after I realized how they really work.

**Comment by paulvoosten** [comment]
@SonofLiberty90 I wasn't aware of the $Now - 1m range for the Field Content Alert Condition, thank you so much! :+1:
It turns out that my work PC wasn't NTP synced, and the test server with Graylog was. After I tried it again after syncing my work PC it now works as expected.

Closing this issue since.
