### ISSUE TITLE
Lookup Tables: Allow case-insensitive lookups

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3961]
In a lookup table lookup it would be great if one could specify if the key should be handled case-insensitive or not.

My specific use-case: MAC address lookups. Some systems will send them with lowercase characters and some will uppercase them. Right now I am uppercasing them in the CSV and then applying `uppercase()` in the pipeline lookup to work around this.

```
"mac","station"
"82:2A:A8:07:4C:8D", "Home Main"
"2C:30:33:A5:8D:94", "Home Extender"
```

**Comment by bernd** [comment]
@lennartkoopmann We talked about this and will implement it for each data adapter where it makes sense and not with a generic config option for all data adapters. There will be data adapters where it does not make sense or isn't possible because the backend does not support it. (e.g. maxmind)

For 2.3 we will implement it for the CSV data adapter.
