### ISSUE TITLE
Enhancement: open dashboard widget search request in a new tab

### ISSUE THREAD

**Issue by xmik** [Graylog2/graylog2-server#3975]
## Expected Behavior
Hi, I use Graylog dashboards a lot and would like to suggest an enhancement. Often I want to keep a dashboard open and replay search of a widget in a new tab, probably on right-click. If this was implemented, we could avoid opening the specified dashboard as many times as many widgets we want to replay search of.

## Current Behavior
Currently, on right-click on the play button of a widget:
![graylog-dashboard-widget-replay-tiny](https://user-images.githubusercontent.com/8240219/27828402-8a1673ec-60ab-11e7-845a-08feba5eed83.png)

## Your Environment
* Graylog Version: official docker image `graylog2/server:2.0.0-1`
* Elasticsearch Version: official docker image `elasticsearch:2.3.2`
* MongoDB Version: official docker image `mongo:3.2.5`
* Operating System: docker host is Ubuntu 14.04.2
* Browser version: Google Chrome 58.0.3029.110 (64-bit)

**Comment by DerPhlipsi** [comment]
Hey @xmik,

try Shift-Clicking on the Play-Button :)
Also, I think this is more of an issue with your browser settings instead of a Graylog issue, since I'm getting the option to open the link in a new tab in Waterfox(Firefox) as well as in Chrome (see Screenshots).
![chrome_2017-07-05_17-06-55](https://user-images.githubusercontent.com/15906070/27870897-67987898-61a4-11e7-811d-6a10a9e0ec31.png)
![waterfox_2017-07-05_17-06-10](https://user-images.githubusercontent.com/15906070/27870958-9161e416-61a4-11e7-8036-688f9c95a912.png)



Greetings - Phil

**Comment by edmundoa** [comment]
Hi @xmik,

I'm closing the issue since this duplicates #2725. The issue got fixed in 2.1, I guess this is why it works for @DerPhlipsi :-)

**Comment by xmik** [comment]
Thank you very much! :)
