### ISSUE TITLE
Search query fails with large number of indices

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4054]
Graylog (or rather Jest) is sending HTTP requests with a large initial line (URI path and query string) to the Elasticsearch HTTP API if a large number of indices is included in the search query (e. g. when searching in "All messages").

Related topic: https://community.graylog.org/t/unable-to-search-in-all-messages/1922

## Expected Behavior

Search queries covering a lot of indices should work.

## Current Behavior

Search queries covering a lot of indices fail with an internal server error (HTTP 500) and produce an error message in the Elasticsearch logs:

```
[WARN ][http.netty               ] [ElasticsearchNodeName] Caught exception while handling client http traffic, closing connection [id: 0xecc07e39, /10.1.2.3:54321 => /10.1.2.3:9200]
org.jboss.netty.handler.codec.frame.TooLongFrameException: An HTTP line is larger than 4096 bytes.
```

## Possible Solution

Patch Jest to send index names in the POST body.

## Steps to Reproduce (for bugs)

1. Create lots of indices (so that the list of index names is longer than 4 KB)
2. Run search query covering all indices
3. ???
4. Profit!

## Your Environment

* Graylog Version: 2.3.0
* Elasticsearch Version: 2.x, 5.x

**Comment by bernd** [comment]
I think we should check the length of the URL and use `_all` instead of the list of indices if it's too long.

The only drawback which comes to mind is that we might touch more indices than needed. This might be an issue with older Elasticsearch versions because of fielddata loading, but shouldn't be an issue with Elasticsearch 5. (AFAIK)

Increasing an Elasticsearch setting, which requires an Elasticsearch restart, as a workaround until we have a proper fix is okay, but this is not really a solution in my opinion. Since this is HTTP, there might be proxies in between Graylog and ES which might not support this limit. (mentioned by @kroepke)

**Comment by joschi** [comment]
Elasticsearch doesn't support providing index names in the HTTP request body when using HTTP POST requests via [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-body.html).

**Comment by hc4** [comment]
Actualy you could split such request in multiple requests with shorter indices list (internally elastic will do one request for each index anyway)

**Comment by joschi** [comment]
@hc4 True, but we'd like to avoid the overhead of multiple HTTP requests.

**Comment by hc4** [comment]
I have 2 more ideas, but the both hacky :)
1) Create temporary index alias and search against it
2) Compact index list using wildcards: Assume we want to search in indices from 19 to 31, then index list compacted to: `index_19,index_2*,index_30,index_31`
