### ISSUE TITLE
Double loading spinner when clicking on an index set.

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#4113]
When going to look at an index set, you get a double loading spinner.

<img width="423" alt="screen shot 2017-08-25 at 12 55 56 pm" src="https://user-images.githubusercontent.com/5646799/29726496-8a217540-8995-11e7-81de-495d24a18511.png">

## Expected Behavior

A single loading spinner

## Current Behavior

2 loading

## Steps to Reproduce (for bugs)

1. Go to System - Indeces
2. Click on the Default Index Set

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.5.2
* MongoDB Version: 3.2.16
* Operating System: Ubuntu 16.04.3 LTS
* Browser version: Safari 11.0 and Firefox 56.0b6

**Comment by joschi** [comment]
@kpointer I'm unable to reproduce that on Graylog 2.3.1.
<img width="1002" alt="System / Indices – Loading spinner" src="https://user-images.githubusercontent.com/43951/29740196-51f6daa4-8a51-11e7-84d9-458327d7c64d.png">

Please make sure to empty your browser cache and check that all plugins you're using are compatible with Graylog 2.3.1.

**Comment by joschi** [comment]
@kpointer There are 2 spinners because the page loads 2 components, the general information about Elasticsearch and the index-specific information. Each of them is being loaded individually (and async), so that 2 spinners make sense.

<img width="685" alt="Index Set page" src="https://user-images.githubusercontent.com/43951/29740219-dc1255f6-8a51-11e7-91cf-7d277d02d628.png">
