### ISSUE TITLE
Cache (lookup tables) settings can't be changed

### ISSUE THREAD

**Issue by dcharbonnier** [Graylog2/graylog2-server#4180]
Graylog v2.3.1+9f2c6ef

When I save the new cache settings in the lookup tables I expect :
- at least a message telling me that the change will be processed after a server restart
- an option to restart the cache with those parameters
- at best an immediate change without loosing the current cache

**Comment by kroepke** [comment]
Hi!

Caches are supposed to be restarted on the fly and the corresponding lookup tables are recreated and exchanged atomically in the system. No server restart is be necessary.

Currently it is not possible to retain the in-memory cache during restarts, mostly because the underlying implementation (Guava's) does not support retaining the create timestamps to make sure the time based eviction would work as expected.

What leads you to suspect the cache is not updated after saving its settings?

**Comment by dcharbonnier** [comment]
Because I was able to see my initial cache size limit on the cache page, so, at least the display was incorrect.

**Comment by jalogisch** [comment]
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!
