### ISSUE TITLE
Field Chart widget: "Customize" field and default value not working with non-numeric fields

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4218]
When generating a field chart on a *string* field, which only supports *total* and *cardinality* as value, the following issues occur:

* The default *value* is  *total* but should be *cardinality*
* The *customize* dropdown menu of the widget still allows to change the *value* to unsupported types like *mean*, *max* or *min*.

**Comment by kroepke** [comment]
Without having the field types in the UI this is not possible to do for only non-numeric fields.

Firstly we always request the total first since that is supported for all field types. Getting the cardinality is a special request and more expensive.
Secondly, disabling the options in the drop down is only possible if we know the types. The structure of the code is so convoluted that we cannot get to actual field values when creating the dropdown. Again it needs to know the field types.

I would like to postpone this to 3.0 or later to fix it properly.

**Comment by lennartkoopmann** [comment]
@kroepke makes sense. I’m looking into this to see if there is a way to make the UX a little better until a real fix in v3.0.

**Comment by kroepke** [comment]
Perfect thanks!

**Comment by dennisoelkers** [comment]
This has been fixed in the new search in `3.2.0`.
