### ISSUE TITLE
Groovy, Jython to replace Grok, processors, pipelines, etc.

### ISSUE THREAD

**Issue by okelet** [Graylog2/graylog2-server#4235]
Hi, just a crazy idea... Why would not replace all processing methods (grok, pipelines, extractors, etc.) with a simpler and cleaner solution, for example Groovy, Jython, etc.? Also you would have all the features and libraries of Java, with a more consistent and easy language.

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.6.2-1
* MongoDB Version: 3.4.9
* Operating System: RHEL 7.4

**Comment by joschi** [comment]
@okelet We thought about using an existing scripting language when drafting the processing pipelines feature but ultimately decided against using those due to security and performance considerations.

For reference, take a look at why Elastic replaced generic scripting support with only Painless scripting.
