### ISSUE TITLE
Enhancement - Add count to stream rules

### ISSUE THREAD

**Issue by kentonbmax** [Graylog2/graylog2-server#4301]
## Expected Behavior
user can create a rule and set a count criteria. This allows an alert to be sent only if a count of rule(s) (occurrence) match occurs. 
Ex. Sql retry, or retry connection may return an error in code but may succeed after more than 1 retry. 

## Current Behavior
No way to manage streams or alerts based on an occurrence > 1 and <= n.

**Comment by joschi** [comment]
@kentonbmax That's not possible in the stream rules because the message hasn't been indexed yet.
Additionally, issuing search queries from within a stream rule (or a pipeline rule) is not possible due to performance restrictions.

Maybe you could solve your requirements with using an appropriate alert condition.
http://docs.graylog.org/en/2.3/pages/streams/alerts.html#message-count-condition
