### ISSUE TITLE
UI pagination not working as expected with default search

### ISSUE THREAD

**Issue by shakalandy** [Graylog2/graylog2-server#4394]
## Expected Behavior
- make a search
- browse to page 2 of search result
- get page 2 of initial search result

## Current Behavior
- make a search
- browse to page 2 of initial search result
- get page -10 due to the default "realtive" search of "5 minutes". Clicking on "page 2" results on getting the page 2 of a later search

## Possible Solution
In most searches you expect to get the page 2 result of your initial search.
Maybe it would be possible to change to generate the links on the different pages with "absolute" time ranges instead of relative ones?

## Steps to Reproduce (for bugs)

1. Make a "search in the last 5 minutes"
2. Receive some new messages in the meantime
3. click to page 2 of the initial search
4. get another page 2, not the one from your initial search

## Context
Our developers expect that the graylog search works as other search mechanisms out there.
This would mean, that you really get page 2 of your initial search result.
In Graylog this is only possible if you search with an "absolute" interval before.
So i am not that sure if this is really considered as a bug in your point of view.

## Your Environment

* Graylog Version: graylog-server-2.3.2-1.noarch
* Elasticsearch Version: elasticsearch-5.6.3-1.noarch
* MongoDB Version: mongodb-server-2.6.12-3.el7.x86_64
* Operating System: RHEL 7
* Browser version: Chrome 62

**Comment by bernd** [comment]
@shakalandy This is not as easy to solve as it seems, unfortunately. Even when using absolute time ranges for the pagination, the data can change. For example, a log shipper was disconnected for some time and buffered the logs. If it re-connects and empties its buffer there will be new messages with an older timestamp. In that case the pagination would be wrong even with absolute time ranges.

If our backend storage would implement consistent views over search results, we could use this. But Elasticsearch cannot do this right now. (it's a pretty hard problem, especially in a distributed data store)

Another way to solve this would be to materialize every search into some storage (e.g. writing every message in the result to disk) and paginate over that. That wouldn't ensure that the user will see all data, but the view would be consistent.
This would be quite expensive in regard to resources and not that easy to implement, though.

I am afraid for now we cannot really do anything about it. Sorry.

**Comment by mdollinger** [comment]
Sorry, i do not understand the consideration about some "log shipper"-corner case.

To me the case ist very clear:
- To execute a search is one thing
- To navigate in the search results is another thing
And navigating between pages must not result in another search being executed.
So the way it is implemented now seems to me like a big conceptual insufficiency which should stepwise be refactured

**Comment by kroepke** [comment]
@mdollinger No one said we consider this a "missing minor feature".

I understand your reasoning very well but that neither means it is easy for us to build nor that we have no interest in supporting this use case.
Unfortunately, as @bernd tried to explain, there are certain scenarios where people expect other behavior (mostly because Graylog has always behaved like it does today) and that there are technical reasons that make it difficult to support with the current architecture.

The only middle ground I can see is to convert a search over a relative time range into its absolute equivalent (which happens internally for every search anyway) and then expose that to the user. Then, if the underlying data set is not changing, executing searches again will not be visible to the user.

If that sounds useful to you, I would like to ask you to open a feature request so we can discuss how a UI for this could work.

Thank you for your input!
