### ISSUE TITLE
Introduce permission which allows users to assign roles to other users

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#4443]
We can't give on role and permission only to a sub role
`roles:edit:59e5c6ba.......`
`users:rolesedit:59e5c6ba.......`

The problem is when roles:edit is set, user can give himself the role admin.

* Graylog Version: 2.4.0
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox 58

**Comment by joschi** [comment]
> The problem is when roles:edit is set, user can give himself the role admin.

What would you expect to happen? 🤔

**Comment by TenGbps** [comment]
Need to be able to define user role by another role and not all (admin), for exemple a sub admin group.

**Comment by joschi** [comment]
@TenGbps Please elaborate on your use case and provide some examples.

**Comment by TenGbps** [comment]
We have 3 roles, admin, manage & readonly.

```
{
    "_id" : ObjectId("f1c605875da734e49b9ced16"),
    "name" : "Admin",
    "permissions" : [ 
        "*"
    ],
    "description" : "Grants all permissions for Graylog administrators (built-in)",
    "read_only" : true,
    "name_lower" : "admin"
}
```

```
{
    "_id" : ObjectId("9ea2ad89528c9889590f01d9"),
    "name" : "Manager",
    "permissions" : [ 
        "*"
    ],
    "description" : "Manager role",
    "read_only" : false,
    "name_lower" : "manager"
}
```

```
{
    "_id" : ObjectId("a7213cb8cf91aac4d4b2758a"),
    "name" : "Readonly",
    "permissions" : [ 
        "*"
    ],
    "description" : "Readonly role",
    "read_only" : false,
    "name_lower" : "readonly"
}
```

**Comment by joschi** [comment]
> The user on manager role can only assign role Readonlyw with this permission
`"users:rolesedit:a7213cb8cf91aac4d4b2758a"`

Yes, because that's what the permission says. I'm still not sure what you want to achieve.

**Comment by TenGbps** [comment]
This is view like a want manager role user view :

![perm](https://user-images.githubusercontent.com/30792994/34519930-ce4a9c94-f086-11e7-9f55-1b36c779b379.jpg)

**Comment by dennisoelkers** [comment]
@TenGbps I think your problem is that you want to control which roles a user is able to assign to other users. Users belonging to the "Manager" role are supposed to be able to assign specific roles to other users, but not the "Admin" role. 

If I understood you correctly, then I see where you are struggling. The `users:rolesedit:<id>` permission allows a user to edit the roles of a user with the id `<id>`. What you would require is another permission (i.e. `roles:assign:<id>`) which would allow a user to assign role `<id>` and would be checked additionally to the `users:rolesedit:<id>` permission during a roles update.

This is currently not implemented. If this is what you want, then we could probably implement it for one of the next releases.

**Comment by joschi** [comment]
As a sidenote, permissions regarding roles are using the schema `roles:<action>:<name>`, e. g. `roles:read:manager`.

https://github.com/Graylog2/graylog2-server/blob/2115a42fd26da728d525652b6240ea30ab3b4179/graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java#L99

**Comment by TenGbps** [comment]
I have try to use "roles:read:manager" without success on 2.4.0 

```
{
  "type": "ApiError",
  "message": "User [testperm] not authorized. (GET api/roles)"
}
```

**Comment by bernd** [comment]
This will be possible with the new sharing system in the upcoming 4.0.0 release.
