### ISSUE TITLE
Proposal for a better display of "Quick values" chart

### ISSUE THREAD

**Issue by iredmail** [Graylog2/graylog2-server#4463]
The idea is displaying more information in a "Quick values" chart, also easier to read and understand.

Current chart (v2.4):

![](https://i.imgur.com/iTU0nOi.png)

Proposed display: it displays 2 more values, also easier to read and understand.

* Remove both rows: "Top 5 values" and "Others".
* Replace the colorful indicator icon by numbers like: 1, 2, 3, 4, 5 (sorted order). the icon is meaningless. It will be easier to understand with a number.

```
  Value                 %                   Count
1 <value-1>           X                   X
2 <value-2>           X                   X
3 <value-2>           X                   X
4 <value-2>           X                   X
5 <value-2>           X                   X
6 <value-2>           X                   X
7 <value-2>           X                   X
8 <value-2>           X                   X
```

![](https://i.imgur.com/zPcCHqP.png)

**Comment by iredmail** [comment]
No interest?

**Comment by edmundoa** [comment]
Thank you for your suggestions @iredmail!

Since Graylog 2.4, it is possible to configure the quick values visualisation to show more items in the table, and also configure how many "top values" should there be. As I understand, those are the main suggestions coming from the issue.

Additional comments to your suggestions:

>Remove both rows: "Top 5 values" and "Others".

We will not remove those two sections since in many use cases people only want to see a handful of values, and this separation is meaningful for them. The number of values on each section is already configurable, although currently it is not possible to set the number of "top values" to 0, which is what you would want to do.

>Replace the colorful indicator icon by numbers like: 1, 2, 3, 4, 5 (sorted order). the icon is meaningless. It will be easier to understand with a number.

The coloured legend indicator is used to display a visual hint of which slices of the accompanying pie chart represent each value. However, they are also displayed when the pie chart is not there, which shouldn't be the case because, as you mentioned, they don't add any value.

So as a summary, these are the things I would consider changing from your feedback:

- Allow setting "top values" to 0, to remove that section altogether
- Remove coloured legend from table when the pie chart is not displayed
- Add row number next to the value

**Comment by bernd** [comment]
The "Quick Values" widget doesn't exist anymore in the current versions of Graylog. Closing this issue.
