### ISSUE TITLE
Remove old content pack (configuration bundle) functionality

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4783]
Remove the old content pack (configuration bundle) functionality from the web interface and the Graylog server, so that only the new content packs functionality remains.

**Comment by kmerz** [comment]
[Remove Frontend](https://github.com/Graylog2/graylog2-server/commit/fa8e9aff83f34dffde97dab9d3ccdbb93e75b2eb) removes the first part of the content pack (configuration bundles). The backend is still missing (except for the Rest resource) since it is still needed for the migration. When content packs are ready for that, we can replace the use in the migrations.

**Comment by bernd** [comment]
Replaced by https://github.com/Graylog2/graylog2-server/issues/4944
