### ISSUE TITLE
Pipeline processing will not stop for dropped messages

### ISSUE THREAD

**Issue by jtkkex** [Graylog2/graylog2-server#4855]
When trying to filter out noise from event logs, the pipeline rules seem as excellent option, as complex conditions are available. 

## Expected Behavior

When setting up noise reduction pipeline, it would seem logical to make the most voluminous drops at stage 0, and then have less messages to process in later stages.

## Current Behavior

At the moment, there are two things that happen

1. If there is no "empty rule": 
```
rule "empty"
when 
  (1 == 1)
then
end
```
processing does not continue to the next stages for the messages that are **not** dropped.

2. After adding the empty rule to the first stage, all messages are processed on the second stage, even the dropped ones.

## Possible Solution

Two suggestions:

1. Add a new condition to pipeline stage processing: "continue processing on the next step if none of the rules match condition"
2. When message is dropped, stop evaluating other rules for that message

## Steps to Reproduce (for bugs)

1. Make a stream Windows Events and route a Windows Event log entry there
2. Make a pipeline "Filter unnecessary Windows Events".  Connect it to the Windows Events stream
3. Stage 0, create a rule that drops messages with condition EventID == 4662 (for example - if your test setup creates these events)
4. Stage 1, create a rule that forwards the messages to a specific new stream "TestStream"

## Your Environment

* Graylog Version: 2.4.5
* Elasticsearch Version: 5.6.9
* MongoDB Version: 3.4
* Operating System: CentOs7
* Browser version: any

**Comment by jalogisch** [comment]
@jtkkex depending on your conditions the fastest possible solution would be to have multiple conditions:

```
alert "multi con"
when
  has_field("EventID") AND
  to_string($message.eventid) == 4662 OR
  to_string($message.eventid) == 4672 OR
  to_string($message.eventid) == 4662
then
  drop_message();
end
```

Currently your suggestion would be against the design principles of the processing pipelines that you need to select on purpose what is processed and what not.

**Comment by jtkkex** [comment]
Actually, I do use multiple conditions.  The "problem" is that after drop_message(), the processing of the message does not stop.  So having stage 0 drop messages that are not wanted and then stage 1 processing fields of (also) the dropped messages is so unnecessary. If for example 2000 msgs/s are processed at stage 0.  90% of them are dropped.  Then at stage 1, again 2000 msgs/s are processed, in stead of the 200msg/s that would seem logical to me.

**Comment by florianvolle** [comment]
This looks more like a bug and we will take a look at it.

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @jalogisch @florianvolle 

I am facing the similar issue in my env where graylog is running 3.1.1 version. Let us know if there is any update on this request.

https://community.graylog.org/t/pipeline-processing-continues-after-messages-getting-dropped-in-previous-stage-of-pipeline/13023

Thanks,
Ganeshbabu R

**Comment by tmacgbay** [comment]
Beyond drop_message(),  It would be helpful to have a separate exit_pipeline() function to reduce unnecessary processing and/or pipeline stages.  Being able to set rule execution sequence within a stage would help too... but is slightly off topic.

**Comment by jalogisch** [comment]
@tmacgbay you might want to open a feature request for that function.

**Comment by thll** [comment]
+1 for getting this fixed as the current behaviour is confusing and the issue is popping up again and again

[HS #604670126]

**Comment by patrickmann** [comment]
HS #604670126 has a good analysis of the problem. We cannot immediately abort processing of a message when `drop_message` is called, since we may still be processing the message in a different pipeline. However, the desired behavior may be achieved by having an initial rule move only the filtered messages to a different stream; a separate pipeline then processes that filtered set of messages. Using that paradigm, we do not need to call `drop_message` at all.

Or we can try and more closely match the user's intuitive expectations by evaluating drop_message per pipeline:
- stop processing the current rule and any further rules in the current stage
- do not process the message in any further stages in the current pipeline
- but allow message to continue to be processed in all other pipelines

I vote we get rid of drop_message, since we can achieve the desired noise reduction / performance optimization without it; and evaluating it per pipeline will complicate the already very complex pipeline interpreter and its associated metrics.
@boosty @thll what's your take?

**Comment by tmacgbay** [comment]
My understanding of `drop_message()` is that it stops the message from being stored in Elasticsearch. I believe it's the only function that allows you to do that so it wouldn't make sense to get rid of it - in the docs it shows a rule dropping a message because it is oversized....  I would still want that capability.  I can't think of a reason I would ever want to process a message through more stages or even another pipeline that it would currently be in or slated to go to.  It's not going to be stored.... why waste further processing anywhere?

Whil

**Comment by jtkkex** [comment]
I also use drop_message() to avoid storing messages to ES.  So if it is removed, some other mechanism to drop messages using a specific (possibly complicated) condition should be added.

**Comment by patrickmann** [comment]
@tmacgbay @jtkkex Thanks for the input - we definitely need to have the ability to exclude messages from ES. I was focused on the performance optimization aspect; and the confusing throughput metrics associated with `drop_message`. So I think we still have these options:
1. keep everything as is; improve documentation to clarify what `drop_message` actually does, so it can be used appropriately and resulting metrics are not as confusing.
2. redesign `drop_message` processing to work on a per-pipeline basis, to improve performance gains and bring it more into line with user expectation

Does anybody feel strongly about (2)?

**Comment by tmacgbay** [comment]
As strongly as a non-developer can feel...

**Comment by jtkkex** [comment]
I would also prefer 2.

**Comment by thll** [comment]
I also vote for 2.

To get a clear picture of the suggested redesign, what exactly does "per-pipeline basis" mean?

Couldn't we just stop processing the message at all, once `drop_message` has been called? We could collect potential problems with a change like this and then decide.

If I understand pipeline processing correctly, there might be pipeline configurations that would lead to non-deterministic behaviour because pipeline execution order is not fix. 

For example considering the following scenario when `drop_message` discards the message immediately:
I have two pipelines and on stage 1 of the pipelines, pipeline A does a `create_message` or a `clone_message` based on the same rule condition that pipeline B is doing a `drop_message` for. Depending on execution order of the pipelines I might or might not end up with the additional message in ES but in both cases the original message was dropped.

@patrickmann: Do you know of any other scenarios, where things can go wrong?

If it's just the scenario above, I think it's OK. We could document that `drop_message` is ideally placed on a dedicated stage to avoid issues like this.

**Comment by patrickmann** [comment]
@thll Thanks for the assessment. That was also the result of a discussion with @bernd and what is implemented in the linked PR.

I think it strikes a good balance: 
- It's easy to understand what `drop_message` does
- unexpected results are likely to be rare in the real world
- improves performance, in line with user expectations
- throughput metrics are in line with user expectations

**Comment by boosty** [comment]
@dulanism Looks like this should get an update on https://docs.graylog.org/docs/functions.
