### ISSUE TITLE
Username param isn't needed, because it isn't checked

### ISSUE THREAD

**Issue by 1Jesper1** [Graylog2/graylog2-server#4860]
https://github.com/Graylog2/graylog2-server/blob/365d26fff714cf37b360d09a337b3138437f663a/graylog2-server/src/main/java/org/graylog2/rest/resources/system/PermissionsResource.java#L67

**Comment by dennisoelkers** [comment]
From a quick check, this looks like the resource is not used anymore anyway, and can be removed.

**Comment by bernd** [comment]
While the resource isn't used by any of our backend or frontend code, it is quite useful for admins who need to create custom roles or fine tune user permissions. The endpoint provides an overview of all existing permissions (including those from plugins).

That's why we should keep it for now.

@1Jesper1 The username parameter is actually needed in the `/system/permissions/reader/{username}` endpoint because the "user self edit" permissions are computed based on the username.

**Comment by 1Jesper1** [comment]
@bernd Thanks for the explanation.
