### ISSUE TITLE
Cannot access Graylog interface outside the host machine

### ISSUE THREAD

**Issue by arsaboo** [Graylog2/graylog2-server#4890]
## Expected Behavior

Graylog web interface should be accessible from all machines on the network. 
## Current Behavior

I installed Graylog on my Ubuntu machine using the following commands:
```
$ sudo sysctl -w vm.max_map_count=262144
$ sudo docker run --name mongo -d mongo:4
$ sudo docker run --name elasticsearch -e "http.host=0.0.0.0" -e "xpack.security.enabled=false" -d docker.elastic.co/elasticsearch/elasticsearch:5.6.2
$ sudo docker run --name graylog --link mongo --link elasticsearch -e TZ="America/New York" -p 9000:9000 -p 12201:12201 -p 1514:1514/udp -v /docker/containers/graylog:/etc/graylog/server/ -v /docker/containers/graylog/plugin:/opt/graylog/plugin/ -e GRAYLOG_WEB_ENDPOINT_URI="http://127.0.0.1:9000/api" -d graylog/graylog:3.0
```
I can access the webinterface (http://192.168.2.212:9000/) from the machine where I installed Graylog. However, the Graylog web interface is not accessible from any other machine on the same network. http://192.168.2.212:9000/ gives me a blank screen (no error) from other machines.

## Your Environment

* Graylog Version: 3.0
* Elasticsearch Version: 5.6.2
* MongoDB Version: 4
* Operating System: Ubuntu
* Browser version: Firefox/Chrome

**Comment by joschi** [comment]
> I can access the webinterface (http://192.168.2.212:9000/) from the machine where I installed Graylog. 

@arsaboo That's because you've configure the URI of the Graylog REST API to be `http://127.0.0.1:9000/api`. See https://en.wikipedia.org/wiki/Loopback#Virtual_loopback_interface for details.

Additionally, Graylog 3.0.0 is currently in alpha state and you shouldn't use it if you don't want to contribute bug reports.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by arsaboo** [comment]
@joschi Should I not specify any URI in that case? I took the example from the official docs.

**Comment by joschi** [comment]
@arsaboo There are breaking changes in Graylog 3.0.0, make sure to read https://github.com/Graylog2/graylog2-server/blob/3.0.0-alpha.1/UPGRADING.rst#simplified-http-interface-configuration or use the latest stable release, which is Graylog 2.4.5 at the time of writing.

Also kindly move the discussion to one of the aforementioned channels.
