### ISSUE TITLE
When deleting a GELF Output graylog doesnt process message

### ISSUE THREAD

**Issue by henri9813** [Graylog2/graylog2-server#4960]
## Expected Behavior
When i delete a output, graylog must just stop to use this output and continue to process messages.

## Current Behavior
When i delete a output ( in my example, a gelf tcp output ), graylog stop proces message. I must restart the graylog's server.

## Possible Solution
Force the "reloading" of graylog outputs ? 

## Steps to Reproduce (for bugs)
Create a gelf output ( with real destination ).
Remove the gelf output

That's all, graylog will not process messages anymore... unless i restart it
![](https://i.gyazo.com/d83c8264007ee23727acdf61ed0f7ac0.png)

## Context
To analyse logs, i create a python tcp listener to recieve graylog logs. But when i stopped my app, graylog doesn't process messages anymore, even if a delete the output for all stream.

## Your Environment

* Graylog Version: 2.4.6-1
* Elasticsearch Version: 5.6.10 
* MongoDB Version: 3.6.6
* Operating System: Debian
* Browser version: Chrome

**Comment by henri9813** [comment]
Hello,
This happen on every stream.

**Comment by bernd** [comment]
I am unable to reproduce this, unfortunately. :confused: 

I tested the following with 2.5.0-alpha.1. (but it should be the same with 2.4.6 because there haven't been any changes to the outputs system)

- Create new output for a stream
- Update output settings
- Delete output from a stream
- Delete output globally

I did both with the included STDOUT logger and GELF outputs on the default stream and a custom stream. Everything works for me.

Do you have any other information for us on how to reproduce this? Like log messages.
