### ISSUE TITLE
Changes to stream output settings require a restart of the server to take effect

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5010]
I have noticed several times that the following actions do not take effect until you restart the `graylog-server` process:

* Creating a new output and assigning it to a stream
* Changing settings of an output that is assigned to a stream
* Unassigning an output from a stream

I believe that #4960 is related to this.

## Your Environment

* Graylog Version: 2.4.6

**Comment by bernd** [comment]
I am unable to reproduce this, unfortunately. :confused: 

I tested the following with 2.5.0-alpha.1. (but it should be the same with 2.4.6 because there haven't been any changes to the outputs system)

- Create new output for a stream
- Update output settings
- Delete output from a stream
- Delete output globally

I did both with the included STDOUT logger and GELF outputs on the default stream and a custom stream. Everything works for me.

Do you have any other information for us? Like log messages.

**Comment by lennartkoopmann** [comment]
I've also not encountered this again. Thank you!
