### ISSUE TITLE
AMQP dead letter queue

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#512]
Currently we are acking messages that could not be parsed or failed for some reason and just throw them away because they would get re-delivered forever.

Implement a dead letter queue here.

**Comment by bernd** [comment]
I am closing this because the recent architecture changes make this really hard. The message parsing is not done in the input path anymore but only after the message has been read from the journal. This would require some channel from the codecs to the input or a separate AMQP connection from the codec.

Please re-open if this is still relevant. Thank you!
