### ISSUE TITLE
Support alternative, FOSS Configuration Database Backend(s)

### ISSUE THREAD

**Issue by NotAFile** [Graylog2/graylog2-server#5257]
Mongodb pulled a switcheroo on their contributors and is no longer Free or Open Source Software. This means that it is or will be impossible to run a graylog server using a FOSS setup.

Aside from being an ideological problem, this also means that some companies might hesitant to consider graylog.

## Possible Solution
Afaict, supporting multiple configuration database backends has been considered before (#3866 etc.). 

If enough momentum builds around a community mongodb fork for continued support, this problem would solve itself, although this seems unlikely to me at the moment.

## Context
 - I am running a personal instance, where I would prefer to run FOSS only for ideological and practical reasons.
 - I am recommending using graylog as solution at work, but have faced resistance due to mongo's licensing.

**Comment by lennartkoopmann** [comment]
Hi,

implementing multiple configuration databases is still an item we are considering, but we will not re-prioritize this because of the recent MongoDB license change.

The comment about hesitation because of uncertainty around the license is very valid and that's why we are getting a legal memorandum ready.

Thank you very much!

**Comment by NotAFile** [comment]
@lennartkoopmann is there any tracking issue I can subscribe to for this? I could not find one, which is why I opened this issue.

**Comment by lennartkoopmann** [comment]
@NotAFile Tracking issue for the legal memo or the database backends?

**Comment by NotAFile** [comment]
@lennartkoopmann I meant the backends tracking issue, I'd assume that a legal memo tracking issue would go into the documentation repo instead.

**Comment by lennartkoopmann** [comment]
referring to @kroepke for that question :)

**Comment by kroepke** [comment]
At this time we don't have a specific issue about allowing other external databases.
Given the amount of complexity even supporting a single other type of database adds I don't think it is likely that we will ever go that route.
Instead I could imagine that we might instead not have an external database at all and keep the application state and configuration in some kind of embedded database.

But currently we don't have any plans addressing this, since it hardly ever comes up anymore and the required work (implementation, documentation, support, testing) greatly exceeds the benefits we would get from supporting completely different databases.

**Comment by NotAFile** [comment]
okay, thanks for your reply!
