### ISSUE TITLE
LDAP Group Mapping

### ISSUE THREAD

**Issue by lschroth** [Graylog2/graylog2-server#5261]
## Expected Behavior
when assigning security roles via ldap mapping, I would have expected that all roles for a match group would have been assigned to a graylog user.  example, if I had four groups in my ldap mapping, one with reader, one with administrator, one with custom role and one with no role, I would have expected my new user who was assigned in ldap to each of the groups, would be assigned the reader, administrator & custom in my graylog implementation.

## Current Behavior
Currently if a role has none assigned, it removes all other roles for the user, leaving on the "default" role

## Possible Solution
In this case, the security should be a combination of all ldap mappings with an assigned graylog role.  It seems that a mapping without a role is causing all roles to be removed.

## Steps to Reproduce (for bugs)

1. setup ldap pulling all ldap groups over and assign one a role of administrator
2. setup user in ldap to have the group with administrator and one without administrator
3. login to as the user and see what role is assign

## Context
Currently cannot use roles which do not have an assigned group.  I have to setup LDAP mapping and specific roles for graylog in my ldap

## Your Environment
Active Directory ldap setup

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.x
* MongoDB Version:
* Operating System: Ubuntu 18.4
* Browser version: edge / chrome

**Comment by jalogisch** [comment]
He @lschroth would you please share with us the anonymized group definitions and the assignment to the user. 

Currently, we are not able to re-create the issue with the given information. This would help us to verify the issue and make the search for a potential bug easier

**Comment by lschroth** [comment]
Sure, Here is the setup

DSigns - assigned to Digital_Signs and Digital_Test AD Groups

Graylog - assign Digital_Signs as Digital_Signs Role.  Leave Digital_Test as no rights and assign default as reader

When logging in as DSigns, they get "reader" instead of "Digital_Signs" role.  I would have expected them to have at least Digital_Signs
LDAP Settings
![ldap setting](https://user-images.githubusercontent.com/17602189/48806623-7edc5b00-ece0-11e8-8a16-6b7e7705b52a.PNG)
LDAP Mapping
![group mapping](https://user-images.githubusercontent.com/17602189/48806632-8b60b380-ece0-11e8-8996-489b46cf6802.PNG)
Roles Assigned after login of user
![after signin](https://user-images.githubusercontent.com/17602189/48806653-9fa4b080-ece0-11e8-87ab-ca78c957312d.PNG)

**Comment by edmundoa** [comment]
Hi,

I was trying to reproduce this in 2.5.0 but I can't:

<img width="847" alt="screenshot 2018-12-11 at 11 36 29" src="https://user-images.githubusercontent.com/716185/49794946-11e53f80-fd39-11e8-9342-19b5575cd812.png">

<img width="1076" alt="screenshot 2018-12-11 at 11 36 20" src="https://user-images.githubusercontent.com/716185/49794937-0db92200-fd39-11e8-83aa-9a81cc1c1ec8.png">

I don't think we changed anything in authentication since 2.4.6, so I would start double-checking that the user is in all groups by doing a test login in Graylog's LDAP configuration page. If your setup uses more than one AD server to authenticate, please also ensure the data in all servers is consistent.

Another thing you should check is if you see any errors in your Graylog server logs during authentication from those users.
