### ISSUE TITLE
Not able to extract values as numeric fields using grok extractors

### ISSUE THREAD

**Issue by emanzaman** [Graylog2/graylog2-server#5285]
I have used the following grok patterns:
![image](https://user-images.githubusercontent.com/38486100/48554575-cdff4600-e904-11e8-8ce9-315ebb46dee6.png)
But still the response time is treated as string as shown below:
![image](https://user-images.githubusercontent.com/38486100/48554661-ff781180-e904-11e8-80f9-8cadb565bce3.png)

 site = %{DATA:site} \| version = %{NUMBER:version} \| responseTime=%{NUMBER:responseTime}

My test input is:
site = LDN | version = 10 | responseTime=3232 ms

## Current Behavior
Not able to view extracted NUMBERS as numeric values in graylog using grok extractors. 

Please let me know what is missing. 
Thanks.

## Your Environment

* Graylog Version: 2.4.3
* Elasticsearch Version: 5.6.8
* MongoDB Version: 3.6.2
* Operating System: RHEL7

**Comment by jalogisch** [comment]
He @emanzaman 

the ability to show advanced stats on one field limited how the value is saved in elasticsearch. From what you have described I guess the value is saved as a string and not a number. 

To fix this you can use prefix the field to ensure that only values as numbers are saved in the field. The other option is to use a custom mapping that allows only numbers as field values ( http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#custom-index-mappings ).

The source of this is not because of a bug in Graylog or elasticsearch, more because it is not clear communicated how messages are saved and what is possible. The upcoming versions of Graylog will be more clear on this. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
