### ISSUE TITLE
Entity Validation on REST API does not validate objects in request body

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#5402]
## Expected Behavior

Objects passed in the request body of a REST request should be properly validated when the parameter is annotated with `@Valid`.

## Current Behavior

Objects in the request body are not validated, invalid values are accepted.

## Steps to Reproduce (for bugs)

1. `curl -XPOST -u admin:foobar -H 'X-Requested-By:curl' -H 'Content-Type:application/json' -d '{"flatten": true,"list_separator": ",","key_separator": "","kv_separator": "","key_whitespace_replacement": "_","key_prefix": "","string": ""}' http://localhost:9000/api/tools/json_tester`
2. (Above request should fail due to several empty properties which are annotated with `@NotEmpty`, but it succeeds)

## Your Environment

* Graylog Version: 3.0.0-alpha.5
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by thll** [comment]
It works when the corresponding hibernate annotation `org.hibernate.validator.constraints.NotEmpty` is used but it doesn't work with the generic `javax.validation.constraints.NotEmpty` annotation.

There seems to be some kind of configuration issue with the validator configured for jersey.

**Comment by bernd** [comment]
@dennisoelkers @thll I think I figured it out.

The problem seems to be that the `jersey-bean-validation` dependency is pulling in an older `hibernate-validator` dependency.

- We use:
  `org.hibernate.validator:hibernate-validator:6.0.13.Final`
- Jersey is pulling in:
  `org.hibernate:hibernate-validator:5.1.3.Final` (see the different `groupId`)

Since both use a different `groupId`, both dependencies are in use. I guess jersey trips on that for some reason. Excluding the `org.hibernate:hibernate-validator` dependency from the `jersey-bean-validation` dependency declaration fixes the issue for me.

I also noticed that the server doesn't log the latest `hibernate-validator` version on startup:
```
INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
```

With the exclusion the correct version is logged:

```
INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.13.Final
```

Using the `curl` command from the issue text I am getting the following wrong response without the exclusion:

```
$ curl -ni -XPOST -H 'X-Requested-By:curl' -H 'Content-Type:application/json' -d '{"flatten": true,"list_separator": ",","key_separator": "","kv_separator": "","key_whitespace_replacement": "_","key_prefix": "","string": ""}' http://localhost:9000/api/tools/json_tester
HTTP/1.1 200 OK
X-Graylog-Node-ID: 28164cbe-4ad9-4c9c-a76e-088655aa7889
X-Runtime-Microseconds: 98353
Content-Type: application/json
Date: Thu, 28 Nov 2019 17:36:42 GMT
Content-Length: 99

{"matches":{},"flatten":true,"line_separator":",","key_separator":"","kv_separator":"","string":""}
```

With the exclusion I am getting:

```
$ curl -ni -XPOST -H 'X-Requested-By:curl' -H 'Content-Type:application/json' -d '{"flatten": true,"list_separator": ",","key_separator": "","kv_separator": "","key_whitespace_replacement": "_","key_prefix": "","string": ""}' http://localhost:9000/api/tools/json_tester
HTTP/1.1 400 Bad Request
Vary: Accept
X-Graylog-Node-ID: 28164cbe-4ad9-4c9c-a76e-088655aa7889
X-Runtime-Microseconds: 102069
Content-Type: text/plain
Date: Thu, 28 Nov 2019 17:41:57 GMT
Connection: close
Content-Length: 502

must not be empty (path = JsonTesterResource.post.arg0.kvSeparator, invalidValue = )
must not be empty (path = JsonTesterResource.post.arg0.string, invalidValue = )
must not be empty (path = JsonTesterResource.post.arg0.string, invalidValue = )
must not be empty (path = JsonTesterResource.post.arg0.kvSeparator, invalidValue = )
must not be empty (path = JsonTesterResource.post.arg0.keySeparator, invalidValue = )
must not be empty (path = JsonTesterResource.post.arg0.keySeparator, invalidValue = )
```

I created a pull request for this: https://github.com/Graylog2/graylog2-server/pull/6898
It would be awesome if you could check if this fixes the problem for you.
Thank you! :smiley:

**Comment by thll** [comment]
Perfect, that fixed it. Thank you!
