### ISSUE TITLE
Equals (=) character cannot be used in a regular expression

### ISSUE THREAD

**Issue by schultzjms** [Graylog2/graylog2-server#5648]
## Expected Behavior

When a regular expression containing an `=` character is included in a regular expression, the regular expression should match log entries containing `=`.

## Current Behavior

A regular expression containing an `=` will return no results.

## Possible Solution

`=` is used for some numerical searches, but does not seem to be able to be escaped to be used as a literal character. Perhaps it ought to be added to the list of characters than can be escaped.

## Steps to Reproduce (for bugs)

1. Search for a regular expression that contains a regular expression that matches a string preceding an `=` (e.g. `message:/uid/` will match with log entries containing `uid=`)
2. Within the regular expression delimiters, add an `=` at the end of the pattern, such that the a string found in step should be found (e.g. `message:/uid=/`).
3. This expression will now not match any logs.

## Your Environment

* Graylog Version: Graylog 2.5.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kroepke** [comment]
The issue here is that the field `message` is analyzed and Elasticsearch runs the regex query against the terms of the field, not the original field content.
Please see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html for details.

In any case, Lucene/Elasticsearch requires the regex to match the entire field/term, which is often not what users mean when they use regexes this way.

As it stands, Graylog cannot easily support this capability with an Elasticsearch backend, so I'm afraid I'll have to close this issue.
