### ISSUE TITLE
How to omit passwords from logs?

### ISSUE THREAD

**Issue by matemikulic** [Graylog2/graylog2-server#5784]
## Expected Behavior
Previously we used logstash in front of graylog, which would parse logs and GELF output them to graylog. On logstash we achived this with mutate.

`mutate {
    	gsub => ["message",  "(?<=password=)[^&]+", "****"] 
    	gsub => ["http_request",  "(?<=password=)[^&]+", "****"] 
    }
`
But on Graylogs that will not have a lot of messages coming in, we are trying to simply setup by using Graylog extractors to parse messages. This works fine with addition of couple of grok patterns, but I'm not sure how to hide fields like passwords.

## Context
Original message looks something like this:
`Mar 19 12:28:36 localhost haproxy[56341]: 77.243.30.178:12273 [19/Mar/2019:12:28:36.317] api.example.com http-api/BACKEND-1 0/0/1/12/13 200 183 - - ---- 709/707/2/1/0 0/0 {||api.example.com} {189299} "GET /api/command?user=someUser&password=myPassWord&cmd=SOMETHING HTTP/1.1" - -`

I wish to omit password from log in order not to have password available to everyone accessing the logs. So the line should look like something like this:

`Mar 19 12:28:36 localhost haproxy[56341]: 77.243.30.178:12273 [19/Mar/2019:12:28:36.317] api.example.com http-api/BACKEND-1 0/0/1/12/13 200 183 - - ---- 709/707/2/1/0 0/0 {||api.example.com} {189299} "GET /api/command?user=someUser&password=*****&cmd=SOMETHING HTTP/1.1" - -`

## Your Environment
Dockerized using official docker images
* Graylog Version: 2.4.6-1 
* Elasticsearch Version: 5.6.13 
* MongoDB Version: 3.4
* Operating System: CentOS 7
* Browser version: Chrome 72.0.3626.121

**Comment by jalogisch** [comment]
He @matemikulic 

personally I would use the processing pipelines, because those allow to modify messages better than you could do with the extractors. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
