### ISSUE TITLE
Graylog 3.0 resource loaded with hostname not working for FQDN (http_publish_uri not working like rest_listen_uri)

### ISSUE THREAD

**Issue by matzegebbe** [Graylog2/graylog2-server#5785]
Hi Graylog Team!

OLD VERSION: Graylog 2.4.6+ceaa7e4 on deb832117bd7 (Oracle Corporation 1.8.0_72-internal on Linux 4.9.0-6-amd64)
NEW VERSION: Graylog 3.0.0+db6cf59 on 7b2115b6066e (Oracle Corporation 1.8.0_181 on Linux 4.3.0-0.bpo.1-amd64)

in the past we were able to set the resource uri with
_web_endpoint_uri = /sdi/admin/logs/api
rest_listen_uri = http://0.0.0.0:9000/sdi/admin/logs/api/_
resulting in reloading the resources from
```
<script src="/sdi/admin/logs/config.js"></script>
```
![image](https://user-images.githubusercontent.com/3482021/54607874-b91bf600-4a4f-11e9-8298-66521412ea7c.png)

In version 3.0.0-2 we are enforced to set a host in the settings (0.0.0.0 is not allowed) with
http_publish_uri = http://emea-jas-a11t:8080/
```
<script src="http://emea-jas-a11t:8080/config.js"></script>
```
If we call graylog behind a reverse proxy (https) or try the FQDN like emea-jas-a11t.company.net like before graylog is not working with the error message:
We are experiencing problems connecting to the Graylog server running on http://emea-jas-a11t:8080/api/. Please verify that the server is healthy and working correctly.

![image](https://user-images.githubusercontent.com/3482021/54608065-3b0c1f00-4a50-11e9-8efd-3018aa314810.png)

How can we map the old behavior with the new configuration?

**Comment by aft2d** [comment]
I had a similar issue and solved it with nginx rewrite rules, however in my opinion this is not the correct way to deal with that.

**Comment by jalogisch** [comment]
He @matzegebbe 

first you need to know that we had an issue when running Graylog in a "subdirectory" that will be fixed with the next release ( https://github.com/Graylog2/graylog2-server/pull/5765 ). 

Please read carefully the description of the new parameters that are available in Graylog: 

https://github.com/Graylog2/graylog2-server/blob/3.0/misc/graylog.conf#L93-L134

@aft2d I guess that you refer to [Proxy web interface and API traffic under a path prefix using HTTP](http://docs.graylog.org/en/3.0/pages/configuration/web_interface.html#nginx) that is done on purpose. 

However, we are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
