### ISSUE TITLE
Click header logo breaks back button

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#5975]
## Expected Behavior
Clicking logo should take you directly to the expected destination 

## Current Behavior
When you click the logo in the header, it navigates to `/` which redirects to `/search`.
This effectively breaks the `back` button on the browser as tries to go "back" to `/` which just redirects again.

## Possible Solution
- Either have the logo navigate directly to `/search`
OR
- Have `/` use ES6's history API `replaceState` to redirect the user 

## Steps to Reproduce (for bugs)

1. Navigate to any page other than `/search`
2. Click the Graylog logo in the header
3.
4.

## Your Environment

* Graylog Version: `master`
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
To add a bit of context: the reason why the logo does not redirect directly to `/search` is because a user can set up a custom start page to a stream or dashboard that will be displayed directly when logging into Graylog or going to `/`.
Anyway, I think the option of using `replaceState` to do the redirection should work and fix the issue with the back button.

**Comment by edmundoa** [comment]
Fixed in #6750
