### ISSUE TITLE
Restoring graylog after elastic run out of space.

### ISSUE THREAD

**Issue by vveliev-tc** [Graylog2/graylog2-server#5990]
## Expected Behavior

expecting for graylog to store logs in elastic as well as load index_set page

## Current Behavior

logs not going into the index(not stored)

## Steps to Reproduce (for bugs)

1. elastic runs out of space 
2. recovering elastic by deleting old indices 
3. restarting graylog 

## Context

2 elastic nodes run out of space, not able to recover graylog after.

## Your Environment

* Graylog Version: 3.0.2+1686930 on 2e1c382c4189
* Elasticsearch Version: 6.5.4
* MongoDB Version: mongo:3
* Operating System: Debian Stretch
* Browser version: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by gimmic** [comment]
You're probably going to have to provide some more context here. Unfortunately we routinely have ES nodes fill up, the cluster goes red and graylog stops indexing. The Journals continue to process and fill up. 
When you delete index sets, ES goes green again and graylog continues submitting the backlog to ES properly. You shouldn't need to restart graylog.

**Comment by vveliev-tc** [comment]
so I think I would some info why it's broken for me. But I'm not sure how to fix that, don't see any API that resolves the problem.

Currently, Default index returns: 
```
{
  "type": "DetailedError",
  "message": "More than one index in deflector alias: [graylog_49, graylog_53]",
  "details": []
}
```

`POST /system/indices/ranges/index_set/{indexSetId}/rebuild ` - does not seemed to fix the issue.

**Comment by gimmic** [comment]
Have you tried rotating your index?

**Comment by vveliev-tc** [comment]
so cycling does create a new index but graylog still throws the same error 

I have indexes : 
graylog_54
graylog_48
graylog_47
...

where 49-53 were manually deleted as they were empty.

**Comment by vveliev-tc** [comment]
looks like when elastic runs out of space it changes cluster settings. This is not confirmed, but it's the only command I have run since elastic went out of space.
but I think running this fixes the issue:

```
PUT /_cluster/settings
{
  "persistent" : {
    "cluster.blocks.read_only" : false
  }
}
```

**Comment by waynekearns** [comment]
@vveliev-tc This is a known and expected behavior for Elasticsearch when the high water mark is exceeded. The procedure for changing the high water mark (cluster.routing.allocation.disk.watermark.flood_stage) is included below. 


https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html

**Comment by zez3** [comment]
> 
> 
> @vveliev-tc This is a known and expected behavior for Elasticsearch when the high water mark is exceeded. The procedure for changing the high water mark (cluster.routing.allocation.disk.watermark.flood_stage) is included below.
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html

Yes but the Graylog behavior is not normal. In my case the Graylog 3.1.4 was still writing/output-ing  to ES even if the ES cluster was in read-only.
Graylog should detect & stop sending messages if the ES cluster is in read-only otherwise the messages go to nirvana.
I did had such errors in Indexer failures {"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}
