### ISSUE TITLE
Dashboard tooltips are detached from widgets

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6114]
## Expected Behavior
When hovering over a Widget the tooltip should be near/attached to the widget. 

## Current Behavior
![image](https://user-images.githubusercontent.com/404238/60962741-42ad4780-a30f-11e9-9681-a6222dabcb72.png)

### Your Environment

* Graylog Version: 3

**Comment by jrunu** [comment]
I kinda want to latch onto this issue, because it sounds like it has the same root cause. We particulary have this problem on dashboards when scrolling. It works fine until you scroll down. Then it looks like the distance scrolled is added between the chart you're hovering over and the tooltip. 

Browser tested are Firefox 70 and Edge 44

**Comment by lfshammu** [comment]
I can reproduce this bug exactly as described. Tested on Chrome 78 and Firefox developer 71
