### ISSUE TITLE
Expose search URL to event notifications

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6203]
## Description

The old alerting system exposed a search URL to alarm callbacks that could be used by notification receivers to find messages that triggered the notification. This is currently missing in the new event notification system.

Since the new alerting is not stream specific anymore, we have to create a link to the new search page to allow multi-stream searches. We might have to create a specific search endpoint for this to be able to create a simple link. (the new search is mainly using POST request for searches)

**Comment by karlisi** [comment]
Until you fix it, adjust the 3.1 documentation.
http://docs.graylog.org/en/3.1/pages/streams/alerts.html#email-alert-notification

**Comment by juris** [comment]
While we are waiting for 3.2.0, as a workaround, you can use `https://graylog_url/streams/${stream.id}/search` in templates.

**Comment by ahuxtable** [comment]
So instead of having a solution, you just keep pushing out the milestone??  Come on, this is poor form.  The 3.2 doco STILL has stream_url as a valid option in notifications and it STILL does not work.  I need an easy way for only semi-technical people to be linked to an event (or filtered list of events) that generated the alert so that the can determine if action needs to be taken.  To break such a useful and important feature is crazy.  Perhaps we can have a 'Simple' alert option that will fire off a single event?

**Comment by on3iropolos** [comment]
The best work around I've found for this, is when you're creating the alert, copy and paste the search URL into the Alert Description. It's a hack, but it solves my problem enough for now.

**Comment by coffee-squirrel** [comment]
This could probably be closed, given replay links exist now.  Doesn't look like they're covered in the Notifications documentation, though.
