### ISSUE TITLE
DNS lookup adapter fills cache with failed lookup results

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#6295]
If you misconfigure a dns lookup adapter (using a non-responding DNS server IP),
it seems to fill the cache with `null` results.

After fixing your error, the lookup will still return no results for a previously
queried and cached domain.
After purging the cache, everything is back to normal.

## Expected Behavior
Lookup failures should be treated differently than `NXDOMAIN` results.

## Current Behavior
I'm just guessing here, but it seems any error is treated as `NXDOMAIN`

## Possible Solution
Distinguish between those errors and don't insert lookup errors into the cache.

## Steps to Reproduce (for bugs)
1. Configure DNS data adapter to use a wrong DNS server (e.g. `1.2.3.4`)
2. Purge cache
3. Wait until input processing looked up some messages (with empty results)
4. Configure a valid DNS server
5. Messages for previously looked up domains are still created with empty results

* Graylog Version: 3.1-rc2

**Comment by chris-y** [comment]
I note that all the lookup caches appear to work this way.  If I do a HTTP JSON lookup which returns an error (or does not contain the single lookup value specified), a NULL or the default lookup value gets inserted into the cache.  When the service stops returning errors, the lookup still returns NULL/default because that was in the cache.
I'm not sure this is a bug necessarily because a query which fails probably does not want to be repeated quickly as it is likely to fail again.
