### ISSUE TITLE
Can't aggregate "source" field because it is compound(string,string)

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#6313]
I'm trying to aggregate on the `source` field but I can't because it's reported as `compound(string,string)`, which doesn't seem to make much sense.

![source](https://user-images.githubusercontent.com/35022/63218021-b0bb0a80-c116-11e9-8009-28c3cf0d2fdf.png)

What could be the reason for this? Can we avoid it?

Graylog v3.1.0

**Comment by kmerz** [comment]
Hmm works for me.. can you inspect what elasticsearch is saying about the type of `source`?

![Graylog (3)](https://user-images.githubusercontent.com/448763/63249494-db69a800-c269-11e9-9461-bc89389e51ad.png)

**Comment by huegelc** [comment]
Same happend to me. I changed the grok pattern of the extractor from long to int:

`%{BASE10NUM:proxy_reply_size_include_header;int} `

since then field shows compound (long,string)

<img width="407" alt="image" src="https://user-images.githubusercontent.com/6955465/64678788-973d8200-d47a-11e9-9927-863573fce309.png">

**Comment by jalogisch** [comment]
@huegelc this is known and expected behavior. After changing the data type of a field and you include data from indices with the old and the new data type the field will be a compound field. 
This will be changed when you only include data from the field with one data type.

@lennartkoopmann could you please give feedback.

**Comment by huegelc** [comment]
Thanks @jalogisch for the explanation. I did a manual index rotation but the field is still compound although the type is set to "long"

```
curl -X GET http://127.0.0.1:9200/graylog_328/_mapping?pretty
.
.
"proxy_reply_size_include_header" : {
            "type" : "long"
          },
```
How can I get rid of the compound filed and have only "long" so that I can create charts out of it.

Thanks

**Comment by dennisoelkers** [comment]
I was able to reproduce the initial issue of @lennartkoopmann and created a PR fixing it.
