### ISSUE TITLE
No conditions link

### ISSUE THREAD

**Issue by tott** [Graylog2/graylog2-server#6314]
I installed Graylog 3.1 from scratch following the instructions outlined at https://docs.graylog.org/en/3.1/pages/installation/os/debian.html but conditions do not appear.

## Expected Behavior
I should be able to create and edit conditions from the Alerts screen and have my conditions appear in the Condition type dropdown

## Current Behavior
Everything seems to be working fine and I see logs flowing in, can search and filter on them but when I try to create alerts I do neither see the Conditions link in Alters screen (see https://i.imgur.com/DES7L5W.png ) nor do all conditions appear in the even condition type dropdown (see https://i.imgur.com/Z1oDaWd.png )

## Your Environment
* Graylog Version: Graylog 3.1.0+aa5175e 
* Elasticsearch Version: 6.8.2
* MongoDB Version: v4.0.12
* Operating System: Debian 9.4.168 on Graylog server, Debian 10 on client where browser runs
* Browser version: Google Chrome

**Comment by kmerz** [comment]
With Graylog 3.1 we ship a new alert engine. Instead of `Condition` please take a look into `Event Definitions` to create a new Alert condition. The documentation is not yet updated but will be so soon.

If you have further questions on this subject please ask them on: https://community.graylog.org/
