### ISSUE TITLE
Lookup `http_proxy_uri` on usage with DNS - not once on startup

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6377]
## Expected Behavior
Changing the Hostname resolution in DNS should make Graylog use the new entry.

## Current Behavior
Graylog does a lookup for `http_proxy_uri` only once on startup. 

## Context
If you decide to use a hostname for `http_proxy_uri` you make this on purpose. Having in mind that you have the option to switch/change the proxy without the need to restart Graylog.

With the current implementation, on each DNS change Graylog needs a restart.

## Your Environment
* Graylog Version:3.1

[Z#842623]

**Comment by dennisoelkers** [comment]
The issue is that in the `OkHttpClientProvider` we are doing a name lookup (through the construction of an `InetSocketAddress`) [here](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java#L95), during the **construction** of the proxy selector class for this specific instance. Instead we should do it [during the selection of the proxy](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java#L115), which means it is performed everytime a request is executed.

The caveat of this is a potentially higher latency for requests as we now ask the local resolver everytime, but it is hopefully negligible due to caching.
