### ISSUE TITLE
Alerts with aggregation should scope backlog messages in notification

### ISSUE THREAD

**Issue by joshabts** [Graylog2/graylog2-server#6381]
When alerts are created using the new aggregation filter to limit triggering an event, the ensuing notification option for including backlogged messages, should be scoped at the key level from the aggregation.

## Expected Behavior
Create a new alert and apply an aggregation filter using a key of username and filtering to where count() > 50 (thus username must have been on more than 50 of the messages), and then create a notification specifying to include the last 50 messages.  Set the custom field as a key and then specify the value from username as the value.  When the notification is received via email for example, I would expect to see the 50 messages that a specific username had that triggered the alert.

## Current Behavior
The above steps are followed, however when the notification is received, it includes the last 50 messages from the search in its entirety (including non-aggregated usernames) rather than only the specific messages that met the aggregation criteria.

## Possible Solution
Have the backlog have a filter to be based on the key field optionally or to somehow scope only the messages that met the aggregation criteria be included as the backlog messages.

## Context
The addition of aggregation in the alerts and events handler is huge, but being able to scope it in the messages even further makes it practical to use.  As an example, if I am monitoring file changes in a directory using auditing, I want to see a user who deletes an excessive number of files in a time span.  So if I say alert me when user X deletes more than 10 files in 15 minutes, I want to see the files they recently deleted that caused the alert to trigger.  Currently I get a notification showing all of the recently deleted files which makes it hard to quickly pinpoint the exact cause.

* Graylog Version: 3.1.0

**Comment by jameskirsop** [comment]
@mpfz0r I'd almost consider this a bug report, not a feature request.

It makes little sense to not filter/scope the backlog of related events included in a notification for an event built on an aggregated query.

Currently the notifications I receive aren't very useful, because they contain backlog events that (often) have no relevancy to the event that triggered the notification. It seems that @joshabts is in a similar position based on the details in his `Context` section above.

It really makes the event notification feature useless in my situation.

Could you consider relabelling this issue??

**Comment by mpfz0r** [comment]
@jameskirsop let's meet in the middle then bug and feature ;-)
Not sure when we'll find the time to fix this though :-(

**Comment by svarcoe** [comment]
Checking in on this issue. Is there any known workaround besides turning off the message backlog in alerts?

**Comment by summbrooks** [comment]
I'm also in need of a resolution to this issue.

**Comment by milefork** [comment]
+1 on that.
The notifications sent were very misleading with a message backlog of messages not related to the event trigger.

In my case I've an aggregation with a group by field of the target user name. The query is for a specific event and I want to get an altert if someone tries to brute force an account. So I fitted it with a count condition >= 5. 
Now when the notification arrives it contains failed login messages in backlog for other accounts which had a failed login count like <=2.

In the Event section of the notification the message part seems to be right so far, there the account name like "EventNAME John - count()=22.0" will be shown.

**Comment by koalaeagle** [comment]
+1 for this issue.

Right now, I have to manually search data based on an alert since the alert does not provide correct context based on the backlog.
One of my group by fields is company, so my backlog may contain information from other companies. I can workaround this by creating an alert per company which takes my number of alerts from 30 to 300. However, this still doesn't get around issues with my second group by field (usually a source IP or username) and I still get irrelevant things in my backlog.

**Comment by koalaeagle** [comment]
Seems related: #8828
