### ISSUE TITLE
Remove Event indices from global search

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#6384]
We should not include the new alerting event indices in the default search.
First of all, events are special and are not really meant to be viewed with the search UI.
Second of all, they create unnecessary failures if users want to sort an fields that
are not present in the Event indices.

**Comment by bernd** [comment]
This is only a workaround for https://github.com/Graylog2/graylog2-server/issues/4367 and the proper fix would be to use the [unmapped_type](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#_ignoring_unmapped_fields) option. Since this can only be done after we switched to the new search in 3.2 (the old search doesn't know about types), we have to implement the work around.
