### ISSUE TITLE
3.1 Alert system uses message timestamp rather than receive time

### ISSUE THREAD

**Issue by tgarons** [Graylog2/graylog2-server#6456]
## Expected Behavior

The alert should use the  receive time of a message rather than the timestamp to decide what "within" means in the "Search within the last" dialogue in an event definition.
This was the behavior prior to 3.1.

## Current Behavior
Currently the timestamp is used.  If defining an event from a source with a long latency, such as the AWS plugin where there is up to a 20 minute difference between the timestamp in the message and when it is received by graylog you have threee choices: miss an event altogether if the search does not go back far enough,  creating multiple events while the timestamp remains within the search window, or doubling the latency by making the search interval as long as the latency. See https://community.graylog.org/t/duplicate-events-with-aws-plugin/11965/3 for more details on how exactly this plays out now.

## Possible Solution
Either provide a choice as to whether to use the receive time or the timestamp in event definitions or go back to semantics prior to 3.1

## Steps to Reproduce (for bugs)

1. Setup the AWS plugin
2. Set up an event for some AWS message with a 20 minute "Search within the last"  and a 1 minute "Execute search every"
3. Generate some filtered message from AWS
4. Wait up to 20 minutes and then watch up to 20 events to be generated.

## Context
Our current workaround is to set both the search window and the search execution to 20 minutes.  This results in an up to 40 minute delay between the occurrence and AWS and the event in graylog.  This is not ideal.  We use this for security events—any change in a security group, the run or termination of an instance, etc. (If we set the search window to anything less than 20 minutes we miss messages.) 

## Your Environment
* Graylog Version: Graylog v3.1.1+b39ee32
* Elasticsearch Version: 5.6.16 (Lucene 6.6.1)
* MongoDB Version: v3.6.14
* Operating System: Ubuntu 18.04
* Browser version: Any browser

**Comment by tgarons** [comment]
(Behavior is identical with the 3.1 server with either graylog-plugin-aws-3.1.1.jar or graylog-plugin-aws-3.0.2.jar)

**Comment by bernd** [comment]
@tgarons 

> The alert should use the receive time of a message rather than the timestamp to decide what "within" means in the "Search within the last" dialogue in an event definition.
> This was the behavior prior to 3.1.

Sorry, the alerting system before 3.1 was not using the receive time because we don't track the receive time. The old system was also executing regular searches by looking at the `timestamp` of the message. The new system is doing the same.

Could it be that something else in your system changed and the `timestamp` of your messages is now correctly set to the event time of the message?

When Graylog receives a message that doesn't provide a `timestamp` value, it will be set to "now". (the receive time) Something in your message parsing could have been changed so that the `timestamp` is now correctly set to the event time of the message.

Again, we cannot use the receive time of a message for alerting in 3.1 (and prior versions also couldn't use it) because we don't track it yet.

Can you check if something else changed in your system that sets the message timestamp?

Are you using the legacy AWS plugin or are you using the new wizard based AWS plugin?

**Comment by tgarons** [comment]
Thanks for the reply.  In looking at old logs and comparing them to AWS I do see that it was also using the timestamp, not the receive time.  The difference is that we were only getting one event and notification per message.  In thinking about it some more, even if the receive time is used with the new system we would still get multiple alerts with the settings at search back 20 minutes every one minute.  The difference seems to be that under the old system the message was somehow marked as being alerted and hence only one notification was sent.  

Nothing has changed in our set up from 3.0 to 3.1.  The existing alerts were automatically migrated and as soon as that happened we started getting one alert per minute for the up to 20 minutes that a message fell within that window.
We are using the graylog-plugin-aws-3.1.1.jar that came with the dpkg installation.  (We also get the same behavior if we use graylog-plugin-aws-3.0.2.jar)
Thanks,
Tom

**Comment by bernd** [comment]
@tgarons Thanks for the update!

Did your old alert condition had the "Repeat notifications" option disabled? Like this:

![image](https://user-images.githubusercontent.com/461/66061950-c064a600-e540-11e9-8b73-b6cf7fe1302d.png)

Because the new alerting/events system works a bit different now, we cannot offer that option anymore.

Can you please show us a screenshot of your current event definition?

Can you also please explain your use case? You want to get one notification when what happens?

Thank you!

**Comment by tgarons** [comment]
Not having “Repeat notifications” set must be the difference.  

Enclosed is a print of the current definition from the “Filter & Aggregation” tab.

The use case is we want to be notified as soon as possible of any security group change in AWS.  We have a stream set up to filter on any security group event in AWS.  Any time a message is routed to that stream we want to be notified.  Because of the way that AWS events make their way to graylog there is already an up to 20 minute delay between the occurrence of the event and its appearance in graylog.  Because repeat events are not filtered the only way to avoid multiple notifications of an event is to only check the stream every 20 minutes.  Previously we could check every minute looking back 20 minutes.  The net effect is that we have introduced an additional 20 minutes of latency.
Thanks,
Tom

**Comment by bernd** [comment]
@tgarons Thanks for the detailed use case information! :+1: 

Since we don't support event creation based on message receive time and no event de-duplication yet, I see the following workaround:

If the AWS security group events have some kind of unique ID, you can use that as a key for the event.

![image](https://user-images.githubusercontent.com/461/66479678-45017800-ea9d-11e9-92cc-e8e2050b8330.png)

To avoid duplicate notifications you can configure a grace period for the event notifications.

![image](https://user-images.githubusercontent.com/461/66479817-8eea5e00-ea9d-11e9-865b-3ddf69d3ecc9.png)

Since the events have the unique ID configured as a key, the grace period prevents new notifications for new events with the same key.

The system will still create new events for the same log message every time the event definition is executed, but you will at least not get notified every time.

One other option would be to reset the timestamp of the AWS security group event in a pipeline rule to `now()`, basically using the receive time instead of the message event time. (`set_field("original_timestamp", $message.timestamp); set_field("timestamp", now("UTC"));`) Using `now()` in the message pipeline is not really the receive time, though. (it'S rather the processing time) It depends on how many messages are buffered in the journal and when the pipeline rule actually runs. This might result in missed alerts so I would favor the first workaround.

We are still working on improvements for the alerting/events system so I hope we can support your use case in a better way in the future. I created a feature request to optionally allow event creation based on receive time in https://github.com/Graylog2/graylog2-server/issues/6557.

**Comment by bernd** [comment]
@tgarons We came up with another workaround:

You could also create a pipeline rule that matches the incoming AWS security group change and creates a new message in a separate stream. You can then point the event definition to that separate stream and alert on new messages in that stream.

```
rule "AWS security group change"
when has_field("some_field_to_match")
then
  let newMessage = create_message("AWS Security Group Event", to_string($message.source), now("UTC"));
  set_field(field: "custom_field", value: $message.some_field, message: newMessage);
  route_to_stream(id: "stream-id-of-separate stream", message: newMessage);
end
```

Hope that helps!

**Comment by tgarons** [comment]
Clever workaround. Thanks!

**Comment by bernd** [comment]
@tgarons Thanks for the feedback! :smiley: I am closing this issue now. Feel free to follow https://github.com/Graylog2/graylog2-server/issues/6557 for progress on the receive time feature.
