### ISSUE TITLE
Error when a password with spaces is used in elasticsearch_hosts

### ISSUE THREAD

**Issue by dhaynes331** [Graylog2/graylog2-server#6571]
In the graylog config file on the "elasticsearch_hosts" line, if a password that includes spaces is entered, Graylog errors on startup. This behavior happens whether the password is entered with spaces or with unicode that equals a space (\u0020). For instance,

`https://username:password with spaces@127.0.0.1:9200`
https://username:password\u0020with\u0020spaces@127.0.0.1:9200`

## Expected Behavior
Graylog should start up and log in to elasticsearch using the credentials provided.

## Current Behavior
Graylog exits and throws the following error: 

> Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://username:password with spaces@127.0.0.1:9200

## Steps to Reproduce (for bugs)
1. Stand up graylog
2. In the server.conf file, enter the following:
`elasticsearch_hosts = https://username:password with spaces@127.0.0.1:9200`
OR
`elasticsearch_hosts = https://username:password\u0020with\u0020spaces@127.0.0.1:9200`
3. run sudo systemctl start graylog-server

## Context
I am attempting to connect Graylog to the Elasticsearch instance using credentials. Due to this bug, I cannot use spaces in the password which, although only slightly, decreases security.

## Your Environment

* Graylog Version:
3.0
* Elasticsearch Version:
6.8
* MongoDB Version:
4.0.10
* Operating System:
Ubuntu 18.04
* Browser version:
N/A

**Comment by kroepke** [comment]
Hi!

This is a little non-obvious, but plain spaces are not allowed here, primarily because they aren't allowed in URIs either.
If you properly URL encode the space (with %20) it will parse correctly.

The issues is not that the config file parser doesn't accept the space with `\u0020`, but that the URI parser does not allow plain white space characters.

Even if we added quoting support, this would still break the URI parser.

cheers!
