### ISSUE TITLE
Web interface hard codes domain/ip breaking k8s port-forward

### ISSUE THREAD

**Issue by swdee** [Graylog2/graylog2-server#6758]
Using the Helm charts to install Graylog into a kubernetes cluster.
```
helm install --namespace logging --name graylog stable/graylog
```

After Helm has finished install the note is output stating
```
To connect to your Graylog server:

1. Get the application URL by running these commands:

  Graylog Web Interface uses JavaScript to get detail of each node. The client JavaScript cannot communicate to node when service type is `ClusterIP`. 
  If you want to access Graylog Web Interface, you need to enable Ingress.
    NOTE: Port Forward does not work with web interface.
```

Ignoring the strange `NOTE` we open up a port-forward to the web interface.
```
kubectl -n logging port-forward svc/graylog-web 9000:9000
```

In the browser open http://127.0.0.1:9000 and the web page gets stuck in a state of perpetual loading.  Viewing the HTML for the initial page load outputs;
```
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="http://10.244.2.108:9000/assets/favicon.png">
    
  </head>
  <body>
    <script src="http://10.244.2.108:9000/config.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/vendor.91c91d4a31d54d96392a.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/polyfill.24a1414e150e7e2e3ce2.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/builtins.24a1414e150e7e2e3ce2.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.0b8691f7db9d7a529f91.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.d8f49d015da6e4cac7ca.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.dc27a65059e0a01875da.js"></script>
    
    <script src="http://10.244.2.108:9000/assets/app.24a1414e150e7e2e3ce2.js"></script>
    
  </body>
</html>
```

Clearly the reason why the page does not load and the strange `NOTE` about port-forward not working is due to the hardcoded domain/ip which is picking up the internal IP from the kubernetes cluster.

Why does such a limitation exist, surely you can just output a relative URL like `assets/app.24a1414e150e7e2e3ce2.js` with no hardcoded domain/ip or even a root relative URL `/assets/app.24a1414e150e7e2e3ce2.js`  and avoid such a strange limitation?

**Comment by jalogisch** [comment]
Dear @swdee you should report errors and problems with the helm chart over in the helm repository. 

https://github.com/helm/charts/tree/master/stable/graylog

Graylog does not created or maintain this configuration, it is created by a 3rd party that does not belong to Graylog. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by pschichtel** [comment]
If you look at this like a configuration issue I would agree, that this is not a graylog issue. However I do wonder why Graylog generates complete absolute URLs to its assets where URLs relative to the host would work just as well.

So in short: Why generate `http://10.244.2.108:9000/config.js`, when `/config.js` would work just as well? I think that's what this issue is about.

When I set `http_external_uri` to = `/`, I get exactly what I expect: `/config.js`. I'm certain, that this will break other places that generate URLs, like for example emails which don't have the context of the current browser page.

I would suggest splitting `http_external_uri` into `http_external_uri_base` for the `http://10.244.2.108:9000` part required by non-browser contexts and `http_external_uri_path` for just the `/` part for internal path generation. I guess this could be done without breaking compatibility by only using the new options, if the old one is not being used.

What do you think?

**Comment by pschichtel** [comment]
And actually there is also the second issue of not handling the broken assets situation very well, I think there should be some kind of message on the page even if not javascript is working. Or alternatively a small script embedded into the HTML detecting the error situation.
