### ISSUE TITLE
Use  known "sessionid" login other User

### ISSUE THREAD

**Issue by nellychen** [Graylog2/graylog2-server#6825]
I have 3.0&2.4  
 if get my user sesssionid ,i will use other username to login his accont

* Graylog Version:3.0&2.4
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:firefox 70.0.1

**Comment by jalogisch** [comment]
dear @nellychen could you please be a little more verbose.

Did you mean, if you can guess a sessionid or manipulate your sessionid to be the same as another users sessionid you will hijack the users sessions?

**Comment by nellychen** [comment]
Dear Jan Doberstein
If you have  an account sessionid, you can use this ID to log in to the system administrator or any account.

Change red line username
[cid:image001.png@01D59FB5.82691780]


Thanks

**Comment by jalogisch** [comment]
@nellychen should you be able to steal a sessionid you can become that user - this is known.
That you are able to become ANY user as you described isn't possible - should you proof me wrong, please follow our written guide how to report a security problem you found in the product.

**Comment by nellychen** [comment]
Dear Jan Doberstein
Sorry, I didn’t make it clear.

step1.This’s our system user account
[cid:image002.jpg@01D59FBB.47CB1550]

step2.Login get my sessionid
[cid:image008.jpg@01D59FBB.47CB1550]

Step3.Change my username and re-load
[cid:image009.jpg@01D59FBB.47CB1550]

**Comment by dennisoelkers** [comment]
@nellychen: The images do not show up. Can you please upload them in this issue on github instead of replying via email?

**Comment by nellychen** [comment]
@dennisoelkers 
step1.This’s our system user account
![1](https://user-images.githubusercontent.com/57928816/69319387-0b19b900-0c7a-11ea-95cf-d1f4c4615e54.jpg)
step2.Login get my sessionid
![2](https://user-images.githubusercontent.com/57928816/69319395-10770380-0c7a-11ea-99d6-aa7d8b43037c.jpg)
Step3.Change my username and re-load
![3](https://user-images.githubusercontent.com/57928816/69319401-140a8a80-0c7a-11ea-9f41-9eeba83153d3.jpg)

**Comment by dennisoelkers** [comment]
@nellychen: What happens after you change the username in `localStorage`? from what i can see, i get immediately logged out. even if that would not be the case, the `username` string in your browser's local storage is just for caching and displaying purposes, it has no effect on your effective permissions or on the search results/streams/... you see or the actions you can perform. Those are always bound to the user who created the session id. 

Unless you can prove otherwise, there is no issue in this ticket and no required action and I would like to close it.
