### ISSUE TITLE
Text input fields on pages using wizard is delayed

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6881]
## Expected Behavior

Entering text into a text field inside a wizard component should be fast.

## Current Behavior

When editing text in wizard components (e.g. creating content pack, creating event definition) the text is added with a delay. This makes entering text feel very sluggish. If I hold a single key it takes some time until the characters appear.

The delay doesn't show up when creating an AWS input which is also using a wizard component.

This wasn't the case in 3.1.x.

## Steps to Reproduce (for bugs)

1. Open event definitions page
2. Create new event definition
3. Enter some text in the title input
4. Try to do it very fast
5. Hold one key

## Your Environment

* Graylog Version: 3.2.0-SNAPSHOT rev 3a10796

**Comment by edmundoa** [comment]
I was testing in the Create Event Definitions page and there are a couple things that caught my attention:
- Typing a letter in the `title` input rendered that input twice. This could probably be improved, but it's expected for the `title`, since components higher in the hierarchy use the `title` to update the page header with the current value.
- Buttons on the page are also rendered twice per update. This is more surprising and seems to be taking longer to re-render
  - Almost 3/4 of the render time for Buttons is taking by two calls to `forwardRef`
    <img width="1376" alt="Screenshot 2019-11-28 at 15 35 54" src="https://user-images.githubusercontent.com/716185/69814640-ef239380-11f4-11ea-9ada-d14d314eb2fe.png">
  - Looking at the `Button` code and playing with it a bit, it seems that generating the styled components is taking most of the time. We wrap that code in a `useCallback` hook which memoizes the function, but not its results, so that function is executed on each render
  - Exporting the original `react-bootstrap` `Button` component instead of the styled-component version of it had a big impact on the responsiveness of the page

To me the biggest-impact optimization we can make is to optimize when we call `styled` and avoid doing it when is not necessary. We can of course also avoid doing some re-renders when are not necessary, but that would need a more fine grained analysis and tuning.

**Comment by mpfz0r** [comment]
If you want to a more severe example, try and edit a GROK pattern.
Each keypress takes about 0.7 seconds

**Comment by edmundoa** [comment]
Fixed in https://github.com/Graylog2/graylog2-server/pull/6906
