### ISSUE TITLE
Navigation bar does not always reflect current page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7019]
## Expected Behavior
The navigation bar should reflect the page the user is currently on.

## Current Behavior
For stream search and dashboards, the navigation does not reflect which top-level page the user is currently on.

## Possible Solution
This seems to have something to do with page URLs and routing.

## Steps to Reproduce (for bugs)
![main-navigation-bug](https://user-images.githubusercontent.com/52014/71092376-67072d00-21a7-11ea-82dd-5d8700c16664.gif)

## Context
The current behavior is inconsistent and can be confusing.

## Your Environment

* Graylog Version: 3.2.0-SNAPSHOT+c9c2ee7

**Comment by linuspahl** [comment]
It looks like this behaviour did not changed since 3.1. We are currently using react-router / react-router-bootstrap like described in the docs. The current implementation should result in the required behaviour. I can only guess that updating the libraries will fix the issue.

We would like to fix this issue in 3.3, to implement a solution which works for all scenarios, e.g. as well for the enterprise and system sub pages.

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/13498
