### ISSUE TITLE
Message / data table action context menu is not fully visible when displayed at the edge of the browser window.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7132]
Like described in the title, the action context  menu of a message / data table is not fully visible when displayed at the corner of the browser window. This depends on the length of the field value. 

![image](https://user-images.githubusercontent.com/46300478/72082500-8a358000-3300-11ea-9760-560ba6ebcd28.png)

## Steps to Reproduce (for bugs)
1. Create a message table widget
2. Open a message
3. Adjust a message field value with the dev tools

## Your Environment
* Graylog Version: 3.2 beta2

**Comment by alex-konn** [comment]
Can confirm. Happens when the message value reaches the right edge of the browser. Maybe the context menu could open at the cursor position or on the left side of the clicked element instead.

![value-context-menu-far-right](https://user-images.githubusercontent.com/45592524/72088009-aa1d7180-3309-11ea-9d03-086c37e2298a.gif)

**Comment by linuspahl** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/7305
