### ISSUE TITLE
Font loading errors in browser console

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7263]
## Expected Behavior

There should be no errors in the browser console about font loading.

## Current Behavior

I see the following font loading errors in the console when running the production artifacts:

![image](https://user-images.githubusercontent.com/461/73011316-45d3d500-3e14-11ea-8122-faed03783abb.png)

The browser is trying to load `/af7ae505a9eed503f8b8e6982036873e.woff2` which returns the default HTML index page. Using `/assets/af7ae505a9eed503f8b8e6982036873e.woff2` works, so the font URL is missing the `/assets` prefix.

We use the [webpack-entry.js](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/webpack-entry.js) in the server and the plugins to switch between development (no `/assets` prefix) and production (with `/assets` prefix) mode.

**Update:**

This seems to be an issue with chrome based browsers. I don't see the issue using Firefox. I can reproduce it in Google Chrome and also Vivaldi 2.10.1745.27. No extensions installed.

## Steps to Reproduce (for bugs)

1. Open browser console
2. Open Graylog UI
3. Check browser console for font loading errors

## Your Environment

* Graylog Version: 3.2.0-beta.5-SNAPSHOT (rev 3e7cd98)
* Operating System: Ubuntu 16.04 LTS
* Browser version: Google Chrome 79.0.3945.130

**Comment by kyleknighted** [comment]
@bernd  okay, so it appears that the error isn’t really an error, even though it is an error.

The frontend build process is duplicating the code, possibly for every plugin. It seems like at least one of those times the font-family url does not get `/assets/` appended to it. 
There are a couple issues at play here: 
- The code should build with the proper paths, regardless of why it's duplicating
- The code shouldn't duplicate, or we should de-duplicate the output before shipping

I am still digging through this. I have a branch that brings all the fonts locally instead of from a 3rd party dependency, but I don't think that's the full solution.

**Comment by kyleknighted** [comment]
_Note the third time the fonts are imported it generated the incorrect path._

![image](https://user-images.githubusercontent.com/122591/73077450-cf6fbb00-3e85-11ea-95a7-c5ca8d0ee4f2.png)
