### ISSUE TITLE
graylog2 extractur cut filed function is not cutting

### ISSUE THREAD

**Issue by meyju** [Graylog2/graylog2-server#735]
Hi,

I try to parse an "key:value" part from a (syslog) message as a new field with the expected value.

I choosed "cut" but  "key:value" still stays in the message filed.

```
{
  "extractors": [
    {
      "condition_type": "regex",
      "condition_value": "^mykeyword:(.+?)\\s",
      "converters": [],
      "cursor_strategy": "cut",
      "extractor_config": {
        "index": 1,
        "split_by": " "
      },
      "extractor_type": "split_and_index",
      "order": 0,
      "source_field": "message",
      "target_field": "mykeyword",
      "title": "mykeyword"
    }
  ],
  "version": "0.90.0"
}
```

Example Origin Message:
```
Oct  8 13:20:01 ip-10-5-62-86 APPNAME[17512]: mykeyword:hello some other text
```

With the above extractor I get

Getting message field:
```
Oct  8 13:20:01 ip-10-5-62-86 APPNAME[17512]: mykeyword:hello some other text
```
Getting mykeyword field:
```
hello
```

But I expecte to get the following:
Expected message field:
```
Oct  8 13:20:01 ip-10-5-62-86 APPNAME[17512]:  some other text
```
Expected mykeyword field:
```
hello
```

**Comment by bernd** [comment]
I think you should use a regex extractor here instead of a split & index. Cutting data from the standard message field is not allowed, so using the copy curstor strategy here is fine.

Example:

```
{
  "extractors": [
    {
      "condition_type": "string",
      "condition_value": "mykeyword:",
      "converters": [],
      "cursor_strategy": "copy",
      "extractor_config": {
        "regex_value": "mykeyword:(.+?)\\s"
      },
      "extractor_type": "regex",
      "order": 0,
      "source_field": "message",
      "target_field": "mykeyword",
      "title": "issue-735"
    }
  ],
  "version": "1.1.0-beta.3-SNAPSHOT (b7914c3)"
}
```

This results in the following:

![v9 cy8ytx6waaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/461/7783451/3bc123e6-0143-11e5-947f-d6c0b1918b20.png)

I hope that helps. Please re-open if you still have that issue. Thanks!
