### ISSUE TITLE
Dashboard Dependency Issue

### ISSUE THREAD

**Issue by kurowskydb** [Graylog2/graylog2-server#7570]
It appears that a role cannot only have access to a dashboard without having permissions to the underlying messages the dashboard widgets are based on. 
Prior to upgrade we had a role which had Read Only access to a particular dashboard, no stream access. This worked well. After upgrade, users in that group got “Page cannot be found”. After playing with different combinations of adding/removing permissions, deleting and re-adding users I added access to the underlying stream and the dashboard finally appeared.

## Expected Behavior
Access selected dashboard

## Current Behavior
Party Monkey :: Page not found

## Steps to Reproduce (for bugs)
1.  Create Dashboard
2.  For a particular role assign ro/rw access to only this dashboard, no streams.
3.  Log in with user/role above
4.  Attempt to access said dashboard.

## Your Environment

* Graylog Version:  3.2.2
* Elasticsearch Version:  6.8.6
* MongoDB Version:  4.0.16
* Operating System:  Rhel 7.7
* Browser version:  Firefox / Chrome / IE

**Comment by dennisoelkers** [comment]
@kurowskydb: yes, that is correct. In order to access a dashboard, the user must be the owner, have a dashboard read permission for this dashboard or the dashboard is shared with the user, _and_ the user must have access to all referenced streams. Otherwise this would make a privilege escalation possible. In `3.2` we are showing a very unhelpful 404 page when one of these conditions is violated. We are working on improving this for `3.3` to give more helpful information and if the user is allowed to see a dashboard but is missing permissions for one (or more) of the referenced streams, we are listing those to help the user and dashboard author to debug and solve this.

As this is generally working as intended, I am closing this issue. Please feel free to reopen it if you do consider this to be a bug and you have more information than you already shared in this issue. If you want to follow the progress on improving the error message for `3.3`, feel free to track the referenced issue.

Refs #7505.

**Comment by leepfrog-ger** [comment]
Well this is an issue I ran into unexpectedly. 
This is a pretty significant change from the behaviour in 3.0 where it was possible to only expose dashboards to certain users without granting access to the whole stream.
If that was mentioned anyhwere in the release notes I must have missed it.

I understand that depending on the implementation it could have previously been possible to access data outside the scope of the dashboard's queries, but it made one of my use cases impossible which was creating and exposing dashboards to particular users without granting them access to the actual stream data (so e.g. only certain fields, only certain aggregations, filtered to specific conditions), and this was possible retroactively.

Right now - to my understanding - my options are as follows:

- expose the whole stream (not possible because only data matching a filter may be available)
- configure relevant messages to be routed to a dedicated stream (which is not possible for existing data)

Am I missing something?
