### ISSUE TITLE
Migrated Saved searches are accessible to admins only

### ISSUE THREAD

**Issue by MMeent** [Graylog2/graylog2-server#7640]
Our users lost access to the saved searches when upgrading to 3.2. Admins still have access, but not the users.

## Expected Behavior
Users keep having access to saved searches.

## Current Behavior
Users lost access to saved searches.

## Possible Solution
Add RBAC configuration for saved searches / bookmarks.

## Steps to Reproduce (for bugs)
1. Create an 3.1.x instance with AD integration. 
2. Add a non-admin user,
3. Save a search
     Non-admin can see and execute said saved search 
3. Update to 3.2.2
4. Non-admin now cannot see nor execute saved search.

## Context
We use and share saved searches between the developers for ease of use. This change broke the use case of having an easily accessible search item.

## Your Environment

* Graylog Version: 3.2.2
* Elasticsearch Version: 6.8 (AWS ES service)
* MongoDB Version: 3.6.14
* Operating System: official docker image -> 3.2.2-1
* Browser version: FF 74.0b7 and others.

**Comment by dennisoelkers** [comment]
Hey @MMeent,

thanks for reporting this issue. The former "Saved searches" had no permission model, so every saved search was readable by every other Graylog. Since `3.2.0` this is not the case anymore. For security purposes, we decided to make sharing it an explicit step instead of an accidental one, so migrated searches are not shared per default.

Starting with `3.2.3`, you can now share searches between different users and restore your usage of sharing selected ones with your fellow colleagues. More details here: #7667.
