### ISSUE TITLE
Show surrounding messages option is lost

### ISSUE THREAD

**Issue by MMeent** [Graylog2/graylog2-server#7641]
## Expected Behavior

previously, we had the dropdown "show surrounding messages" with options for 1s, 5s, 10s, 30s, 1m and 5m (iirc). This has been lost in the update from 3.1 to 3.2

## Current Behavior
no easy method to search surrounding messages from the same input

## Possible Solution
Re-add the easy filter option.

## Steps to Reproduce (for bugs)
1. look at the expanded message buttons: There's  no "show surrounding messages" option

## Context

This was one of the easy methods to show a message in it's context: Search for loglevel:ERROR , then "show surrounding messages" and "loglevel:info OR loglevel:ERROR" messages to get the context + some extra logging from other messages.

## Your Environment

* Graylog Version: 3.2.2
* Elasticsearch Version: 6.8
* MongoDB Version: 3.6.14
* Operating System: official docker image 3.2.2-1
* Browser version: FF 74.0b7 and others

**Comment by dennisoelkers** [comment]
Thanks @MMeent for reporting this!

We are tracking this issue in #6408 already. You have probably not found it when you were searching the issues before you opened this one, because it was recently closed. We have reimplemented the surrounding search feature for the new search and backported it to `3.2`, so it will be part of the `3.2.3` patch release coming soon (I would guess next week).
