### ISSUE TITLE
Consistent display of timestamps in message table

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7702]
## What?
We should display timestamps with milliseconds accuracy and with timezone, in the details
and as a field. 

## Why?
With inputs sending multiple messages per seconds a timestamp accuracy of milliseconds can be
really important. Also to see the timezone is important too. Right now the timestamp field does not
show the milliseconds and the message details field does not show the timezone.

![Graylog (12)](https://user-images.githubusercontent.com/448763/76938853-a56fcd80-68f7-11ea-869f-0084fe58f3c9.png)

## Your Environment
* Graylog Version: 3.3 development

**Comment by arrmo** [comment]
Hi,

Somewhat related - I'm sending across log entries in RFC5424 format (so microseconds). Not asking for microseconds, but ... it seems that milliseconds are being dropped, all entries show .000 for seconds (i.e. milliseconds lost).

Is this part of this issue as well? I see the same - I can get misordering of entries in the log table then, just a bit confusing 😉. FYI, running v3.2 here.

Thanks!

**Comment by miguelelvir** [comment]
We are also noticing this on version 3.3.5. Would be nice to see the the milliseconds. Could this somehow be related to the interaction between the three objects here?

[Timestamp](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/common/Timestamp.jsx#L64)
[DateTime](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/logic/datetimes/DateTime.js)
[MessageTableEntry](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx#L99)

Just curious, since the [dateTime property](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/common/Timestamp.jsx#L77) is being passed correctly, but the actual text value is losing the precision after a call to _formatDateTime

/cc @kyleknighted

**Comment by dennisoelkers** [comment]
This is implemented these days.
