### ISSUE TITLE
Disabling enableSmartSearch doesn't disable fields autocompletion

### ISSUE THREAD

**Issue by oinqu** [Graylog2/graylog2-server#7809]
## Description
When I define `enableSmartSearch=false` under user preferences, Graylog doesn’t seem to react and continues to show me fields autocompletion suggestions under the search query box and other boxes with autocompletion feature.
![2020-04-01_11-16](https://user-images.githubusercontent.com/60503434/78133554-49449780-7427-11ea-8fdc-b2f27889b7ce.png)

## Expected Behavior
Graylog stops showing fields autocompletion suggestions under the search query box.

## Current Behavior
Graylog keeps showing fields autocompletion suggestions under the search query box.

## Steps to Reproduce (for bugs)
1. Disable `enableSmartSearch` under users preferences
2. Navigate back to the search menu, start writing search query

## Context
We are experiencing performance issues similar to https://github.com/Graylog2/graylog2-server/issues/7753. There are many unnecessary queries generated for getting those couple thousand fields. We are living with this problem for quite some weeks now, getting the same result using different browsers under users with different privileges.

## Your Environment

* Graylog Version: Graylog 3.2.4+a407287 under Docker
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.16
* Operating System: Linux/Ubuntu 19.10
* Browser version: Chromium 80.0.3987.149, Firefox 74.0

**Comment by dennisoelkers** [comment]
Hey @oinqu,

thanks for reporting this.

> There are many unnecessary queries generated for getting those couple thousand fields.

I do not understand what you mean? Which queries / in which way are they unnecessary?

How many fields do you have (approximately)? I am trying to reproduce the behavior in an environment with ~4000 fields and the autocompletion is not noticeably slowed down.

**Comment by oinqu** [comment]
Thank you for your quick response, @dennisoelkers! 

I'm sorry I wasn't clear enough. I was thinking about mongo queries, that graylog does to fetch all those fields names during auto-completion suggestions. But I'm not sure those performance issues aren't our mongo setup fault. That is why I wanted to try to disable those suggestions altogether.

The main point of this issue ticket is that the `enableSmartSearch` option doesn't seem to do anything. Graylog keeps showing me fields auto-complete suggestions even when `enableSmartSearch=false` is defined. I wasn't been able to track down where the issue might be.

**Comment by dennisoelkers** [comment]
You are right, the `enableSmartSearch` setting is currently not considered. This is an issue and we will fix it in one of the next releases. 

The other issue is _why_ you want to disable the smart search, because we do consider it to be very useful. Therefore I would like to find out what we can do performance wise to convince you to use it. 
We are not doing mongo roundtrips for every keypress, instead we are fetching the field list once upon every search execution and when you are changing the selection of streams you are searching. This should be reasonably efficient, even for large field sets (in my setup ~4000 fields do equal to 15kb sent over the wire). I have just looked into our code which is searching the field names in the auto completion and found one thing to improve that by magnitudes, expect that to land in one of the next releases.

**Comment by jlauro** [comment]
Exhibiting this behavior with 3.3.2-1.  Regression?
