### ISSUE TITLE
Improve readability of numeric values in data tables

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7831]
## What?
Numbers in data tables can be hard to read, because they are always left-aligned and have no digit grouping.

## Why?
Some results may have big numbers which are hard to read without proper formatting.

## Example
Digit grouping:
466533234 vs 466.533.234
see https://community.graylog.org/t/display-thousands-separator-in-aggregation-tables/

Decimal Alignment: 
https://i.stack.imgur.com/x9qvF.png

## Your Environment
* Graylog Version: 3.2

**Comment by macko003** [comment]
![kép](https://user-images.githubusercontent.com/25004494/78547155-e6744700-77fe-11ea-99ed-b37056cc75b4.png)
Just for the problem visualization

**Comment by Mike-FUT** [comment]
Thanks for your support with this issue.
Two more comments:

1. Even I brought up in the Graylog Forum as an example a "dot" as a thousands separator (which would be the standard in Germany where I live) I believe a "comma" would be the better separator to avoid mixing it up with the decimal point (which is more or les IT standard) and to not make it look like an IP address.

2. Besides the thousands separator it would be better to justify all numeric values "right" instead of left.
So for the Sum (rcv) column in the above screenshot:

now
![image](https://user-images.githubusercontent.com/61519363/78548442-1ae90280-7801-11ea-8f87-2c206b770f23.png)

improved
![image](https://user-images.githubusercontent.com/61519363/78548564-479d1a00-7801-11ea-91d6-160b52bf4ce7.png)

**Comment by dennisoelkers** [comment]
Digit grouping was introduced in #9318. What is missing is aligning numbers to the right.

**Comment by dennisoelkers** [comment]
Fixed in #10195.
