### ISSUE TITLE
Search result is autoupdated on date change even if autoupdate is turned off

### ISSUE THREAD

**Issue by aleksei-berezkin** [Graylog2/graylog2-server#7890]
When I change `start` and `end` absolute dates, and navigate between them, the search result is updated even if autoupdate is turned off. This is especially not convenient when I want to search logs month before with some heavy query: I change `start` date, navigate to `end` — and autoupdate triggers which may last for minutes.

## Expected Behavior
Autoupdate is not triggered on absolute date change when autoupdate not enabled

## Current Behavior
Autoupdate is triggered on absolute date change regardless whether autoupdate is turned on or not

## Possible Solution
Do not trigger autoupdate on dates change if autoupdate not enabled

## Steps to Reproduce (for bugs)
1. Make sure search results autoupdate is not enabled
2. Enter any search request
3. Switch to absolute dates
4. Modify any date
5. Navigate to other date or search request field
6. Result: autoupdate triggers

## Context
I was making somewhat heavy requests, the interval was 5 min, I wanted to check what was a month ago in 5-min interval, changed `start` date first and faced this issue

## Your Environment

* Graylog Version: 3.2.4+a407287
* Elasticsearch Version: 6.8.5
* MongoDB Version: 3.2.12
* Operating System: macOS High Sierra 10.13.6
* Browser version: Chrome 80.0.3987.163

**Comment by dennisoelkers** [comment]
Hey @aleksei-berezkin, thanks for your helpful feedback!

We are already tracking this issue in #7572 & #7596. Both issues are being addressed in #7829, which is currently under review and will be part of the upcoming `3.3.0` release.

In order to reduce the number of issues, I am closing this issue. If you feel that the other issues are not covering your specific use case, feel free to reopen it and add more information.
