### ISSUE TITLE
GELF HTTP input accepts invalid GELF messages

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#807]
The GELF HTTP input is accepting invalid GELF messages and replies with Status 202 (Accepted) instead of Status 400 (Bad Request) or 422 (Unprocessable Entity).

# Valid message
```
$ curl -v -X POST -p0 -d '{"short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}' http://localhost:12202/gelf
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 12202 (#0)
> POST /gelf HTTP/1.0
> User-Agent: curl/7.37.1
> Host: localhost:12202
> Accept: */*
> Content-Length: 86
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 86 out of 86 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 202 Accepted
< Content-Length: 0
< Connection: close
<
* Closing connection 0
```

# Invalid message
```
$ curl -v -X POST -p0 -d 'NOT A GELF MESSAGE' http://localhost:12202/gelf
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 12202 (#0)
> POST /gelf HTTP/1.0
> User-Agent: curl/7.37.1
> Host: localhost:12202
> Accept: */*
> Content-Length: 18
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 18 out of 18 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 202 Accepted
< Content-Length: 0
< Connection: close
<
* Closing connection 0
```

**Comment by kroepke** [comment]
This doesn't work because since the transport/codec split the transport accepting the message cannot determine whether a message is malformed or not.
So I think the 202 Accepted is the correct response here.

An alternative could be to add a parameter that tells the server to use its codec to validate the message. Luckily the URL already contains "gelf" (wow such foresight) so we could do the same for other codecs as well and return 400 Bad Request (I wouldn't use 422 because it's a WebDAV extension).
However that is much more work than we should do for 1.0.0 I guess.

Closing this or pushing it to 1.1, @joschi ?

**Comment by kroepke** [comment]
There is no simple way of doing this short term and we do not claim end to end fidelity right now anyway.

**Comment by hydrapolic** [comment]
Our devs were surprised to notice some error logs were not logged albeit they received HTTP 202 Accepted. Switching to UDP solved it, but we thought it's a bug, now we see it's a feature instead. Any chance re-visiting this issue after 3 years @kroepke @joschi please?

**Comment by kroepke** [comment]
@hydrapolic How did switching to UDP solve this? Or did you also switch to a "raw" (aka plain text) "codec"?
Specifically what format has been sent that wasn't decodable?

Graylog's transports, in this case the HTTP transport generates the 202 response, and due to the way Graylog splits transport and codec, it cannot determine whether the content of a GELF message is valid or not.
That is the same for all inputs that accept GELF.

I understand it might be surprising, but there really isn't a simple way to "fix" this without impacting Graylog's performance characteristics.

**Comment by hydrapolic** [comment]
We have two inputs in Graylog - gelf http and gelf udp (both using default values). The devs switched from gelf http to gelf udp and I was told the larger messages (>16KB) were now appearing in Graylog. I'll ask my colleague about the format being used.
