### ISSUE TITLE
delete action is slow (Input Delete, Stream Delete) in FireFox

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8106]
deleting an input or stream results in slowing down of the fire-fox browser.

## Expected Behavior
improve user experience in the firefox browser.

## Current Behavior
![delete_input_slow](https://user-images.githubusercontent.com/6947168/81719971-62d3f880-9443-11ea-927c-282cae5a92f1.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
3.3.0-beta.3-SNAPSHOT
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:
![firefox_version](https://user-images.githubusercontent.com/6947168/81720385-f5749780-9443-11ea-9f0b-05bbfe925360.png)

**Comment by edmundoa** [comment]
It's been a while since this issue was opened and we fixed some performance issues in the meantime. We also did a couple releases and at least I have not seen any more issues on this regard.

In order to see what the problem here is, we need more information about the performance issue, e.g. performance profiling from the browser's developer tools.
