### ISSUE TITLE
Time-based retention: Deflector rotated after restarting server

### ISSUE THREAD

**Issue by Ubay** [Graylog2/graylog2-server#829]
I have a graylog2 server version 0.92.1 with time based rotation strategy enabled. Every time i restart the service, the deflector is rotated even if the current index has not reached the maximun time.

2014-12-23T12:23:14.668Z INFO  [Main] Graylog2 Server up and running.
2014-12-23T12:23:16.037Z INFO  [IndexRotationThread] Deflector index <graylog2_4> should be rotated, Pointing deflector to new index now!

If i use count based rotation strategy the deflector is not rotated when restarting graylog2.

Is it possible to change the behaviour for time based rotation strategy?

Thanks.

**Comment by razvanphp** [comment]
+1. Can you please reconsider this bug?

It's very annoying since we have a policy to keep 30 days back logs, and if I restart the server 3 times in a day, I already lost 3 days of logs.

Since the web interface clearly says that `index_X ... Contains messages up to 3 minutes ago` it means he knows when it was rotated last.

Thank you!

**Comment by kroepke** [comment]
We'll take a look if it's simple enough to do with the new metadata index in 1.2.0.

**Comment by kroepke** [comment]
needs #725
