### ISSUE TITLE
Add Support for parsing JSON Arrays in Processing Pipelines

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#8706]
## What?

We are attempting to switch from json extractors on the input to pipeline processors doing JSON cracking

We need a way to process (flatten?) JSON arrays so that they behave similarly to the extractor, since we won't know the schema beforehand.
## Why?

Bring in logs that are formatted as JSON arrays.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
**Proposal**: add a new pipeline function `JsonFlatten` which takes a nested JSON string and returns a flattened JSON tree, similarly to the JSON extractor. The resulting flattened tree only contains top-level key/value pairs - there are no more objects or arrays of any kind. This JSON tree can then be further processed by any function taking a JSON tree input, e.g. `to_map`; or transformed to a string via `to_string`.

Nested arrays within a multi-dimensional array are anonymous. We use the corresponding array index to uniquely identify these in the flattened tree.

Input:
- value: string - the JSON source string, arbitrarily nested
- key_separator: string - separator used in concatenating the keys of flattened structures

Examples:
```
Input: {k1:v1, o1:{k11:v11, o11:{k111:v111}}}
Output {k1:v1, o1_k11:v11, o1_o11_k111:v111}

Input: {k1:v1, a1:[[k11:v11, k12:v12],[k21:v21, k22:v22]]}
Output: {k1:v1, a1_0_k11:v11, a1_0_k12:v12, a1_1_k21:v21, a1_1_k22:v22}
```

**Comment by boosty** [comment]
LGTM 👍 

@ChristopherKB Would this solve your use-case?

Would also like to get feedback from @bernd.

**Comment by bernd** [comment]
@patrickmann I like the general idea of a separate function that returns a `JsonNode` similar to `parse_json`. :+1: 

> The function is similar to both JSON Extractor (in the way we concatenate keys in flattening) and `parse_json` (in the input and output data types), so it integrates well with the existing functionality.

The behavior you described is not how the JSON extractor works. The JSON extractor is handling list values differently:

**Input:**
```json
{
  "string": "text value",
  "string_list": [
    "one",
    "two"
  ],
  "object_list": [
    {
      "a": 1,
      "b": 2
    },
    {
      "c": 3,
      "d": 4
    }
  ],
  "nested_object": {
    "bool": true,
    "number": 1,
    "object": {
      "float": 1.1
    }
  }
}
```

**Output:**
```json
{
  "string": "text value",
  "object_list": "{a=1, b=2}, {c=3, d=4}",
  "nested_object_object_float": 1.1,
  "nested_object_number": 1,
  "string_list": "one, two",
  "nested_object_bool": true
}
```

There are probably use cases for both ways of flattening list values.

Flatten list values with the index in the field name (as you described above) can lead to an explosion of fields (see beats messages) which can lead to data loss due to the max field limit per index.

On the other hand, the string representation of the list values as shown here might not be very useful for searching.

So the question is what use cases we need to support and if we need to support both ways, what's the default? /cc @boosty @ChristopherKB 

The JSON extractor also supports some more options to add a prefix to each key, to customize the characters that will be used to join list values, and an option to handle whitespace in field names.

**Comment by bernd** [comment]
@patrickmann Regarding the `key_separator` option for the function:

We only allow a few characters for keys (see [Message#VALID_KEY_CHARS](https://github.com/Graylog2/graylog2-server/blob/cb41ac06d67f05376bd97842e5929f3358ba4d2f/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L195)) so I think we shouldn't allow users to choose arbitrary characters for that option. Otherwise they might choose an invalid character which will then be ignored when setting the field on the message.
That brings up the question if we even should offer that option at all or only offer a selection of predefined values. (e.g. `flatten_json(value: json, key_separator: "underscore")`) /cc @boosty

**Comment by bernd** [comment]
> (e.g. `flatten_json(value: json, key_separator: "underscore")`

Okay, I think that was a brain fart. :joy: It's probably enough to validate the characters that users pass in if we want to offer that option...

**Comment by patrickmann** [comment]
Good points @Bernd. Let's see what @ChristopherKB thinks.

What would be the desired behavior for multi-dimensional arrays? JSON Extractor doesn't handle those very well at the moment: #5945

**Comment by boosty** [comment]
> There are probably use cases for both ways of flattening list values.

and

> I think full expansion into proper key/value pairs should at least be an option. Then I could use that if I am interested in further processing them (and know that my input will not exceed the field limit).

I agree on both comments. I would actually let the user decide which option to use in a given case. The field limit might be a problem in either case, so maybe we should address this independently? At least we should clearly document it. 

So I think we should provide both options, either by adding a parameter or by providing different functions.

**Comment by bernd** [comment]
Regarding the question about multidimensional arrays.

The example JSON input in #5945 is the following. (I added `ArrayOfArrays` and `ArrayOfPrimitives` for an example of an array of arrays and an array of primitive values)

```json
{
  "AffectedItems": [
    {
      "Attachments": "image001.jpg (1234b); image002.jpg (1234b); image003.jpg (1234b)",
      "Id": "Rg",
      "InternetMessageId": "DB@outlook.com",
      "ParentFolder": {
        "Id": "Lg",
        "Path": "\\Inbox"
      },
      "Subject": "Quotation"
    },
    {
      "Attachments": "image003.jpg (1234b); image004.jpg (1234b)",
      "Id": "Rg",
      "InternetMessageId": "AM@outlook.com",
      "ParentFolder": {
        "Id": "Lg",
        "Path": "\\Inbox"
      },
      "Subject": "Test"
    }
  ],
  "ArrayOfPrimitives": [
    "one", "two"
  ],
  "ArrayOfArrays": [
    ["one", "two"],
    ["three", "four"]
  ]
}
```

The JSON extractor will parse it into the following message fields: (*option-1*)
```json
{
  "AffectedItems" : "{Attachments=image001.jpg (1234b); image002.jpg (1234b); image003.jpg (1234b), Id=Rg, InternetMessageId=DB@outlook.com, ParentFolder={Id=Lg, Path=\\Inbox}, Subject=Quotation},{Attachments=image003.jpg (1234b); image004.jpg (1234b), Id=Rg, InternetMessageId=AM@outlook.com, ParentFolder={Id=Lg, Path=\\Inbox}, Subject=Test}",
  "ArrayOfPrimitives" : "one,two",
  "ArrayOfArrays" : "[one, two],[three, four]"
}
```

With @patrickmann's proposed behavior (and how we do it in the beats codec) the resulting message would look like this: (*option-2*)

```json
{
  "AffectedItems_0_Attachments": "image001.jpg (1234b); image002.jpg (1234b); image003.jpg (1234b)",
  "AffectedItems_0_Id": "Rg",
  "AffectedItems_0_InternetMessageId": "DB@outlook.com",
  "AffectedItems_0_ParentFolder_Id": "Lg",
  "AffectedItems_0_ParentFolder_Path": "\\Inbox",
  "AffectedItems_0_Subject": "Quotation",
  "AffectedItems_1_Attachments": "image003.jpg (1234b); image004.jpg (1234b)",
  "AffectedItems_1_Id": "Rg",
  "AffectedItems_1_InternetMessageId": "AM@outlook.com",
  "AffectedItems_1_ParentFolder_Id": "Lg",
  "AffectedItems_1_ParentFolder_Path": "\\Inbox",
  "AffectedItems_1_Subject": "Test",
  "ArrayOfPrimitives_0": "one",
  "ArrayOfPrimitives_1": "two",
  "ArrayOfArrays_0_0": "one",
  "ArrayOfArrays_0_1": "two",
  "ArrayOfArrays_1_0": "three",
  "ArrayOfArrays_1_1": "four"
}
```

As @boosty mentioned, we want to support both options (*option-1* and *option-2*).

I think *option-2* we can implement as proposed by @patrickmann using array indices in the field names.

The output of *option-1* is basically the comma separated output  of calling `#toString()` on the array elements. I think this could be okayish for just looking at the data but it's unsuitable for further processing. As mentioned in https://github.com/Graylog2/graylog2-server/issues/5945#issuecomment-510187452, it would be great if the *option-1* field values could be processed further by something like the `parse_json` pipeline function.

An option could be to serialize the field value as JSON again instead of the `#toString()` output. That way users can use the `parse_json` pipeline function to parse the content again if needed.

The output would look like the following in that case:

```json
{
  "AffectedItems" : "[{\"Attachments\":\"image001.jpg (1234b); image002.jpg (1234b); image003.jpg (1234b)\",\"Id\":\"Rg\",\"InternetMessageId\":\"DB@outlook.com\",\"ParentFolder\":{\"Id\":\"Lg\",\"Path\":\"\\\\Inbox\"},\"Subject\":\"Quotation\"},{\"Attachments\":\"image003.jpg (1234b); image004.jpg (1234b)\",\"Id\":\"Rg\",\"InternetMessageId\":\"AM@outlook.com\",\"ParentFolder\":{\"Id\":\"Lg\",\"Path\":\"\\\\Inbox\"},\"Subject\":\"Test\"}]",
  "ArrayOfPrimitives" : "[\"one\",\"two\"]",
  "ArrayOfArrays" : "[[\"one\",\"two\"],[\"three\",\"four\"]]"
}
```

This is not very pleasant to read if it's stored like that in the final message, but at least it can be processed again.

A third possible option we could add (*option-3*) is to ignore all array values in the first place. That way users can still flatten the nested objects but don't have an explosion of fields for array values that are hard to use and also no JSON serialized string values they don't use.

Example input: (*option-3*)

```json
{
  "string": "text value",
  "string_list": [
    "one",
    "two"
  ],
  "object_list": [
    {"a": 1, "b": 2},
    {"c": 3, "d": 4}
  ],
  "nested_object": {
    "bool": true,
    "number": 1,
    "object": {
      "float": 1.1
    }
    "array": [
      1, 2, 3
    ]
  }
}
```

The resulting message would look like this. (*option-3*) With all array fields removed:

```json
{
  "string": "text value",
  "nested_object_bool": true,
  "nested_object_number": 1,
  "nested_object_object_float": 1.1
}
```

The API of the `flatten_json` pipeline function regarding array handling could look like this:

```
flatten_json(value: json, array_handler: 'json-string') // option-1
flatten_json(value: json, array_handler: 'flatten') // option-2
flatten_json(value: json, array_handler: 'ignore') // option-3
```

If we go that way the question is still: what should be the default?

#### *option-1*

Mainly useful for post-processing the field with `parse_json` and not nice to look at in a final message.

#### *option-2*

Can create lots of message fields and can theoretically be used in search queries. I doubt that these fields are really useful to work with in queries and aggregations in reality, though. Because you cannot rely on the order in arrays so you don't know if index `0` always refers to the same element in different messages.

Users in #5945 asked for Splunk-like multi-value field functions, but that doesn't really work with Graylog because we do schema-on-read and Splunk schema-on-write. These Splunk functions extract values at *search time*.

#### *option-3*

Doesn't create any fields in final messages that are hard to use (*option-2*) or hard to look at (*option-1*). The drawback with skipping arrays by default is, that it's not transparent to users why some fields are not present in the message they are looking at.


I personally would vote for *option-3* as default because it avoids the excessive creation of fields and fields that contain huge JSON values.

What do you think @boosty and @patrickmann ?

**Comment by boosty** [comment]
> Instead of choosing a default value, we can also make the array_handler parameter mandatory, of course.

👍 

As much as I would favour option-3 as the default for the reasons you mentioned, I think it's better to make it mandatory to avoid wrong expectations.

**Comment by patrickmann** [comment]
Initially I thought there should be a mode, in which extractor and pipeline function behave exactly the same, so there is a straightforward way of switching from one to the other. But ability to parse the resulting fields has been a complaint for a long time, so it makes sense to address it.
I'm fine with the 3 options and mandatory parameter.

**Comment by boosty** [comment]
Thanks @patrickmann and @AntonEbel for working on this!

Assigned @dulanism for documentation.

**Comment by hughesjs** [comment]
This looks as though it addresses an Issue I'm having atm, did the documentation ever get done, if so, could someone please point me at it?

**Comment by dulanism** [comment]
@hughesjs Thanks for following up. We're in the process of updating the corresponding chapter. I'll notify you when it gets published.

**Comment by bernd** [comment]
@hughesjs You should be able to use the `flatten_json` function for this once 4.3 is released.

Example:
```
set_fields(to_map(flatten_json(value: to_string($message.message), array_handler: "ignore")));
```

**Comment by boosty** [comment]
The Graylog 4.3 release candidate is out by now, providing the `flatten_json` processing pipeline function: https://www.graylog.org/post/announcing-the-graylog-v4-3-release-candidate
