### ISSUE TITLE
Authentication on Gelf HTTP input?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#909]
Hi,

We are researching Gelf HTTP input here, but we like to know if it is possible to add some sort of authentication to it? Because if we open it up to internet, i think anyone can post data to it?

**Comment by joschi** [comment]
Currently it's not possible to add authentication/authorization to the GELF HTTP Input out of the box.

I also doubt that this makes much sense because the requirements are usually very unique. As a best practice you should place a reverse proxy like nginx in front of your Graylog server (at least for the parts being exposed to the Internet) which can also handle your authentication requirements.

**Comment by dennusb** [comment]
Thanks @joschi. That was my idea also :) We will implement a reserve proxy in front! Thank you

**Comment by scm95** [comment]
The authentication on Gelf HTTP input is permited in actually version? and if is available how can i implement it
