### ISSUE TITLE
Collectors Administration: configure filter does't work

### ISSUE THREAD

**Issue by taoyang987** [Graylog2/graylog2-server#9133]
## Steps to Reproduce (for bugs)

1.given Collectors Administration page
2. choose a Log Collectors for one host 
3. in the configure filter type some words of one configuration
4. the exact configuration does't show up

ps. if not chooe a  Log Collectors for host ,the filter works well.
[png1](https://s1.ax1x.com/2020/10/12/02sYvD.png)
[png2](https://s1.ax1x.com/2020/10/12/02s0UI.png)
## Your Environment

* Graylog Version:3.3.7
* Java Version: jdk8
* Elasticsearch Version:6.8
* MongoDB Version: 3
* Operating System: rhel7
* Browser version: chrome85

**Comment by coffee-squirrel** [comment]
Copying from #11338 (which I opened before finding this)...



## Expected Behavior


When on the Collectors Administration page (`/system/sidecars/administration`) and searching for a collector configuration for a given collector type (via [`CollectorConfigurationSelector`](https://github.com/Graylog2/graylog2-server/blob/4.1/graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationSelector.jsx)) the results should include collector configurations whose name matches the filter.

## Current Behavior


The `items` passed to [`SelectPopover`](https://github.com/Graylog2/graylog2-server/blob/4.1/graylog2-web-interface/src/components/common/SelectPopover.jsx) are a list of collector configuration internal `id`s, so the filtering/search is actually on the collector configuration `id`s rather than their `name`s.

## Possible Solution


Switch from `items` being an array of strings to an array of `{id, name}` objects, use `name` when filtering.

## Steps to Reproduce (for bugs)


1. Have a running Sidecar, collector type (will assume `filebeat`), and at least one collector configuration for that collector type + OS (will assume an `id` of `60d0e372fa5d9c5bbaa0fc43` and `name` of `my_collector_config`)
2. Navigate to the Collectors Administration page (`/sidecars/administration`).
3. Select the checkbox for `filebeat` on the aforementioned Sidecar instance
4. Select the "Configure" menu
5. In the "Filter by configuration" input type `my` and note `my_collector_config` **is not** listed
6. In the "Filter by configuration" input type replace `my` with `60d0e3` (some characters from the collector configuration's `id`) and note `my_collector_config` **is** listed

## Context



We have a fair number of collector configurations, so it would be convenient to be able to search by name when assigning collector configurations.

## Your Environment


* Graylog Version:  4.1.5
* Browser version:  Firefox 92.0.1

**Comment by mpfz0r** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/issues/13238
