### ISSUE TITLE
Colors for dark mode are too dark

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9242]
## Expected Behavior

When using dark mode, the colors should still be light enough to pop a bit and enable users to read the text. 

## Current Behavior

* Text on widgets is too dark:
![Screen Shot 2020-10-22 at 10 10 05 AM](https://user-images.githubusercontent.com/898627/96900778-778bd200-1460-11eb-9f2e-eba8cee5f6df.png)

* Color palate for notifications, warnings, etc. seems too gray/dark
<img width="160" alt="Screen Shot 2020-10-22 at 10 48 16 AM" src="https://user-images.githubusercontent.com/898627/96900854-8ecabf80-1460-11eb-8cf6-a3cbea11f620.png">
<img width="250" alt="Screen Shot 2020-10-22 at 12 08 13 PM" src="https://user-images.githubusercontent.com/898627/96900887-9722fa80-1460-11eb-9c4c-96392685436d.png">
<img width="1048" alt="CleanShot 2020-10-22 at 11 58 24@2x" src="https://user-images.githubusercontent.com/898627/96900979-af931500-1460-11eb-84fb-be54b6edc160.png">
<img width="1019" alt="CleanShot 2020-10-22 at 11 48 23@2x" src="https://user-images.githubusercontent.com/898627/96900994-b3bf3280-1460-11eb-8415-aa1e8468614b.png">
<img width="393" alt="CleanShot 2020-10-22 at 12 19 44@2x" src="https://user-images.githubusercontent.com/898627/96901156-e36e3a80-1460-11eb-9421-0b4b871793fa.png">

## Possible Solution

In general, lightening up these colors a bit would make the notifications pop a bit better.

**Comment by kyleknighted** [comment]
Hey @asachs01 thanks for bringing these up.

The Donut chart is obviously an issue, tried to catch all the Charts, but lots of different label types to capture 😀

The rest, are all generated colors using WCAG's AAA color contrast guidlines.

You can see the generator at - src/theme/utils/contrastingColor.js - feel free to provide any ideas that may generate a better color.

The [`Alert`](src/components/graylog/Alert.jsx) elements are using this feature 

The [`Badge`](src/components/graylog/Badge.jsx) elements are using a similar feature called [`readableColor`](src/theme/utils/readableColor.js) which outputs the darkest or lightest text color based on luminance. Since the Badge you are referring to is a user customizable badge, then the best solution is to choose a different background shade that generates a text color more to your liking. Perhaps in a future iteration we could allow the user to choose a text color there as well. Switching this `contrastingColor` has lead to odd results with some color combinations as well.

Will follow-up with a PR for the Donut chart soon.
