### ISSUE TITLE
Upgrade to ES 7.x from 6.8 requires reboot in order for Graylog search to work

### ISSUE THREAD

**Issue by thejoeschmosho** [Graylog2/graylog2-server#9246]
## Expected Behavior
Upgrade to ES 7.x from 6.8 should not require a reboot of the Graylog Servers for Search to work properly

## Current Behavior
Upgraded Graylog to 4.0, upgraded ES to 7.x, and got an error on the search page of a boolean type incompatibility in both the Message Count and All Messages Boxes.  Restarted the service and then began getting stream permission issues on the search screen even though stream permissions had not changed and user had rights to all streams.  Rebooted all Graylog servers in cluster, and everything worked upon the servers coming back up.

## Steps to Reproduce (for bugs)
1. Upgrade GL 3.3.x to 4.0
2. Upgrade ES 6.8 to 7.x
3. Issue will be apparent on the search screen after the upgrade

## Context
This issue would require unnecessary down time of the servers and could lead to an increase in support cases do to how catastrophic the failures appear to be even though the fix is a simple reboot

## Your Environment
This occurred in both Aaron's environment and the SE dev environment in AWS

* Graylog Version: 4.0
* Java Version: 8
* Elasticsearch Version: 7.7 and 7.9
* MongoDB Version:4.0 and 4.2
* Operating System: Ubuntu
* Browser version: Chrome Latest

**Comment by dennisoelkers** [comment]
This is working as designed. When upgrading between two major versions of ES, we need a reboot of the Graylog nodes in order to reinitialize, due to the way the Graylog server's architecture works. This is documented in our [Upgrade Notes](https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#breaking-changes-to-the-elasticsearch-support), so anyone upgrading to 4.0 should know about it in advance (because everyone reads the docs first, right?). For a multi-node GL cluster (so any setup where availability matters), we do outline a procedure that allows upgrading ES between major versions without message loss [here](https://github.com/Graylog2/documentation/pull/971/files#diff-51eb10d3a8e10a839ef4315e6d7c0cca9101b517fc75be0aebc2ae853f7ab091).
