### ISSUE TITLE
UI: Pipeline Processing Rules not showing syntax errors

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#9250]
Firefox: 81

![image](https://user-images.githubusercontent.com/1891183/96907369-259b7a00-1469-11eb-80ee-4914e9d9b58a.png)

Version: 4.0b2

Reproduction Steps: 

- Create an invalid Pipeline Processing Rule
- Click Apply

**Comment by kyleknighted** [comment]
Hey again @BlueTeamNinja 

Again, I am unable to recreate in the latest Firefox. 

![image](https://user-images.githubusercontent.com/122591/97224275-e6d62e80-179e-11eb-8cb7-7ffff5b0e918.png)

**Comment by Gaya** [comment]
Confirmed it happens in Chromium based browsers.

But in both Chrome and Firefox there is an even weirder issue... if I click in the rule source editor all the entered code will disappear.

Will investigate

**Comment by Gaya** [comment]
Only happens when context is used and a `ref` to the editor. Also noticing some race conditions where the code will not load at all from time to time.
When you focus on the editor an `onChange` will fire and wipe all the contents of the editor. Now debugging why this happens and to make it stop doing this.
