### ISSUE TITLE
Upgrade to 1.0rc1 loses input configuration

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-server#936]
I just upgraded from 0.92.4-1 to 1.0.0-8.rc.1 via the Debian packages, and afterwards no inputs were defined. Everything else was still present (that is, the dashboards, streams, and the data itself).

The server log shows no errors.

I've made a dump of the mongo DB, but can't seem to attach it (or the "inputs" collection) here.

**Comment by joschi** [comment]
The inputs are bound to the specific Graylog node using the unique node ID. The node ID is saved in the `node_id_file` specified in `graylog.conf` (https://github.com/Graylog2/graylog2-server/blob/1.0.0-rc.1/misc/graylog2.conf#L5-7).

Please check that you're using the same node ID (and the same node ID file) after upgrading. Since some names have changed from `graylog2` to `graylog` the chances are good that you're just using another node ID.

**Comment by cmock** [comment]
OK, thanks. It may be worthwhile to make a prominent note of this in the release notes.

**Comment by bernd** [comment]
@cmock We did a blog post on that. https://www.graylog2.org/news/post/0019-graylog-v1-0-0-os-packages

And it will also be in the 1.0.0 final release notes.
