### ISSUE TITLE
Search tab message table configuration is not persistent

### ISSUE THREAD

**Issue by pohmelie** [Graylog2/graylog2-server#9387]
I've edited search tab message table to change showing fields.

## Expected Behavior
My changes will be persistent.

## Current Behavior
After page reload everything goes to defaults.

**Comment by dennisoelkers** [comment]
This is working as expected. If you save your search and reload it, the message table will show the fields you selected. There is currently no way to persist this selection for a new search. The workaround would be to create a customized search with the field selection you want and use that one instead of starting a new search.

**Comment by pohmelie** [comment]
Ok, got it. Thank you!
