### ISSUE TITLE
Dashboard error "You caused a org.graylog2.restclient.lib.APIException"

### ISSUE THREAD

**Issue by essence-it** [Graylog2/graylog2-server#957]
Hi,

I've been experimenting with Graylog2. I did a search on the sources, then i highlighted a time and created a dashboard with it. Since then, i keep getting the error as above and the dashboard page says " Reason: Could not get dashboards. We expected HTTP 200, but got a HTTP 500."

Im unsure how to solve this. How do i delete the dashboard and start again?

Here is a screenshot of the whole problem:

http://i.imgur.com/D1sSvkr.jpg

Thank you,
Michael

**Comment by edmundoa** [comment]
Hi Michael,

Thank you for reporting this issue.

Which Graylog version are you using? There is a known bug in Graylog 0.92.4 with absolute time ranges in widgets (it is already solved in 1.0), maybe you are also affected by it: https://github.com/Graylog2/graylog2-server/issues/884.

**Comment by essence-it** [comment]
Hi Edmundoa,

Yes i am using 0.92.4

So do you recommend an upgrade to Graylog2 V1? I assumed it was still in beta.

Thanks

**Comment by edmundoa** [comment]
Then I assume your issue is the same described on #884, I'm closing the ticket unless there is any new information about it.

The current 1.0 version is an RC (number 3), so it's still not final but really close to it. The recommendation depends on your particular use case, we don't recommend to update your production environment, but it should be stable enough for any other use cases. Upgrading would also help us to fix any small glitches that may still be on the current RC to make the final version even better :)
