### ISSUE TITLE
multi node environments: proper start/stop services on all nodes

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9689]
## Expected Behavior

Configuration changes in multi node environemnts need to be proper done on all Graylog nodes. 

Start/Stop of Inputs and Outputs are done on all nodes proper, configuration changes are made and the Input/Output is restarted on all nodes with the new configuration proper. 

## Current Behavior

> When you stop an output, the node you stopped it on updates state in Mongo and sends a notification to the other nodes via the event bus (which is just a mongo table that all nodes monitor). That notification doesn’t have enough info in it for the other nodes to understand what needs to be done.

The result is not predictable for the users, configuration changes need a manual stop/start of the entity - sometimes a restart of the Graylog server. Sometimes fragments are left on nodes and make it needed to connect directly to those nodes and run some API commands to them. 

See also:
https://github.com/Graylog2/graylog2-server/issues/9554
https://github.com/Graylog2/graylog2-server/issues/5634

## Context

It needs to be that clusters behave proper on changes like a single node environment does. 

## Your Environment

* Graylog Version: 3.3 / 4.0

[z#843759]
[z#843752]

HS-768509249

**Comment by thll** [comment]
From what I can tell, this issue is about two topics
1. lookup table cache purges not properly propagated to all nodes
2. output configuration changes not properly propagated to all nodes

1. Is addressed in https://github.com/Graylog2/graylog2-server/issues/9554 and has already been resolved.
2. Is addressed in https://github.com/Graylog2/graylog2-server/issues/5634 which is currently in progress.

@boosty I think we can close this meta-issue because we have separate issues for both topics. What do you think?

**Comment by boosty** [comment]
@thll Yes, good catch. I'll close this as a duplicate.
