### ISSUE TITLE
white lines showing in heat map after upgrading to version 4

### ISSUE THREAD

**Issue by kthordarson** [Graylog2/graylog2-server#9780]
## Expected Behavior
Heat maps should not show white lines.

## Current Behavior
White lines appear horizontally across the heat map. Looks like the go across the center of each box in the heat map.
![image](https://user-images.githubusercontent.com/4698126/101900505-e27b9e80-3baf-11eb-8b4f-c2ca962eb034.png)

## Your Environment

* Graylog Version: 4.0.1
* Java Version: openjdk 11.0.9.1 2020-11-04
* Elasticsearch Version: Version: 7.10.1, Build: oss/deb/1c34507e66d7db1211f66f3513706fdf548736aa/2020-12-05T01:00:33.671820Z, JVM: 15.0.1
* MongoDB Version: v4.0.21
* Operating System: Ubuntu 20.10 (GNU/Linux 5.8.0-25-generic x86_64)
* Browser version: Firefox 83

**Comment by claymen** [comment]
We see the same issues
- Graylog 4.0.7
- Deployed via Docker (Underlying host is Ubuntu 20.04 LTS)
- Elastic Search 7.10.2
- MongoDB 4.2.13

In our instance the lines are black due to dark mode, but is the same issue.
![image](https://user-images.githubusercontent.com/123596/119303492-64f8a600-bc98-11eb-9c6f-7e7abb710760.png)

**Comment by kmerz** [comment]
With Graylog 4.1 we will resolve this issue by removing the background color and make it possible to see undefined/null (if now value was found) or to insert a default value:
![heatmap-default-value](https://user-images.githubusercontent.com/448763/120193246-7869bb00-c21c-11eb-8eb8-24648af3cca1.gif)
